import type { RosterTuple } from '../player-types'

export const GROUP_K_SQUADS: Record<string, RosterTuple[]> = {
  Portugal: [
    ['Diogo Costa', 'GK', 25, 'Porto', 1], ['José Sá', 'GK', 31, 'Wolves', 2],
    ['Rúben Dias', 'DF', 27, 'Manchester City', 3], ['Pepe', 'DF', 41, 'Porto', 4],
    ['Nuno Mendes', 'DF', 22, 'PSG', 5], ['João Cancelo', 'DF', 30, 'Barcelona', 6],
    ['Danilo Pereira', 'DF', 33, 'PSG', 7], ['António Silva', 'DF', 21, 'Benfica', 8],
    ['Bruno Fernandes', 'MF', 30, 'Manchester United', 9], ['Bernardo Silva', 'MF', 30, 'Manchester City', 10],
    ['Vitinha', 'MF', 24, 'PSG', 11], ['Otávio', 'MF', 30, 'Al Nassr', 12],
    ['João Palhinha', 'MF', 29, 'Bayern Munich', 13], ['Cristiano Ronaldo', 'FW', 40, 'Al Nassr', 14],
    ['Rafael Leão', 'FW', 25, 'AC Milan', 15], ['Diogo Jota', 'FW', 28, 'Liverpool', 16],
    ['Gonçalo Ramos', 'FW', 23, 'PSG', 17], ['Francisco Conceição', 'FW', 21, 'Porto', 18],
    ['Pedro Neto', 'FW', 24, 'Chelsea', 19], ['Ricardo Horta', 'FW', 30, 'Braga', 20],
  ],
  Uzbekistan: [
    ['Ignatiy Nesterov', 'GK', 37, 'Pakhtakor', 1], ['Utkir Yusupov', 'GK', 30, 'Navbahor', 2],
    ['Egor Krimets', 'DF', 35, 'Pakhtakor', 3], ['Anzur Ismailov', 'DF', 39, 'Bunyodkor', 4],
    ['Jaloliddin Masharipov', 'DF', 27, 'Al Nassr', 5], ['Utkir Yusupov', 'DF', 30, 'Navbahor', 6],
    ['Egor Krimets', 'DF', 35, 'Pakhtakor', 7], ['Anzur Ismailov', 'DF', 39, 'Bunyodkor', 8],
    ['Jaloliddin Masharipov', 'MF', 27, 'Al Nassr', 9], ['Otabek Shukurov', 'MF', 28, 'Al Wahda', 10],
    ['Jasurbek Juraboev', 'MF', 31, 'Pakhtakor', 11], ['Igor Sergeev', 'MF', 30, 'Pakhtakor', 12],
    ['Otabek Shukurov', 'MF', 28, 'Al Wahda', 13], ['Igor Sergeev', 'FW', 30, 'Pakhtakor', 14],
    ['Eldor Shomurodov', 'FW', 29, 'Roma', 15], ['Jasurbek Juraboev', 'FW', 31, 'Pakhtakor', 16],
    ['Jaloliddin Masharipov', 'FW', 27, 'Al Nassr', 17], ['Eldor Shomurodov', 'FW', 29, 'Roma', 18],
    ['Igor Sergeev', 'FW', 30, 'Pakhtakor', 19], ['Otabek Shukurov', 'FW', 28, 'Al Wahda', 20],
  ],
  Colombia: [
    ['David Ospina', 'GK', 36, 'Al Nassr', 1], ['Camilo Vargas', 'GK', 35, 'Atlas', 2],
    ['Davinson Sánchez', 'DF', 28, 'Galatasaray', 3], ['Yerry Mina', 'DF', 30, 'Cagliari', 4],
    ['Daniel Muñoz', 'DF', 28, 'Crystal Palace', 5], ['Johan Mojica', 'DF', 32, 'Olympiacos', 6],
    ['Davinson Sánchez', 'DF', 28, 'Galatasaray', 7], ['Yerry Mina', 'DF', 30, 'Cagliari', 8],
    ['James Rodríguez', 'MF', 33, 'León', 9], ['Juan Cuadrado', 'MF', 36, 'Inter Milan', 10],
    ['Wilmar Barrios', 'MF', 31, 'Zenit', 11], ['Jefferson Lerma', 'MF', 30, 'Crystal Palace', 12],
    ['Luis Díaz', 'MF', 27, 'Liverpool', 13], ['Luis Díaz', 'FW', 27, 'Liverpool', 14],
    ['Rafael Santos Borré', 'FW', 29, 'Internacional', 15], ['Jhon Córdoba', 'FW', 31, 'Krasnodar', 16],
    ['James Rodríguez', 'FW', 33, 'León', 17], ['Rafael Santos Borré', 'FW', 29, 'Internacional', 18],
    ['Jhon Córdoba', 'FW', 31, 'Krasnodar', 19], ['Jefferson Lerma', 'FW', 30, 'Crystal Palace', 20],
  ],
  'Czech Republic': [
    ['Tomáš Vaclík', 'GK', 35, 'Boavista', 1], ['Jiří Letáček', 'GK', 26, 'Sparta Prague', 2],
    ['Vladimír Coufal', 'DF', 32, 'West Ham', 3], ['Ondřej Kúdela', 'DF', 37, 'Slavia Prague', 4],
    ['David Hovorka', 'DF', 29, 'Slavia Prague', 5], ['Tomáš Holeš', 'DF', 31, 'Slavia Prague', 6],
    ['Vladimír Coufal', 'DF', 32, 'West Ham', 7], ['David Hovorka', 'DF', 29, 'Slavia Prague', 8],
    ['Tomáš Souček', 'MF', 29, 'West Ham', 9], ['Antonín Barák', 'MF', 30, 'Fiorentina', 10],
    ['Michal Sadílek', 'MF', 25, 'Twente', 11], ['Lukáš Provod', 'MF', 27, 'Slavia Prague', 12],
    ['Tomáš Holeš', 'MF', 31, 'Slavia Prague', 13], ['Patrik Schick', 'FW', 28, 'Leverkusen', 14],
    ['Jan Kuchta', 'FW', 28, 'Sparta Prague', 15], ['Michal Sadílek', 'FW', 25, 'Twente', 16],
    ['Patrik Schick', 'FW', 28, 'Leverkusen', 17], ['Jan Kuchta', 'FW', 28, 'Sparta Prague', 18],
    ['Lukáš Provod', 'FW', 27, 'Slavia Prague', 19], ['Antonín Barák', 'FW', 30, 'Fiorentina', 20],
  ],
}