import type { RosterTuple } from '../player-types'

export const GROUP_A_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "Mexico": [
    ["Raúl Rangel", "GK", 26, "Guadalajara", 1],
    ["Jorge Sánchez", "DF", 28, "PAOK", 2],
    ["César Montes", "DF", 29, "Lokomotiv Moscow", 3],
    ["Edson Álvarez", "MF", 28, "West Ham", 4],
    ["Johan Vásquez", "DF", 27, "Genoa", 5],
    ["Érik Lira", "MF", 26, "Cruz Azul", 6],
    ["Luis Romo", "MF", 31, "Guadalajara", 7],
    ["Álvaro Fidalgo", "MF", 29, "Real Betis", 8],
    ["Raúl Jiménez", "FW", 35, "Fulham", 9],
    ["Alexis Vega", "FW", 28, "Toluca", 10],
    ["Santiago Giménez", "FW", 25, "Milan", 11],
    ["Carlos Acevedo", "GK", 30, "Santos Laguna", 12],
    ["Guillermo Ochoa", "GK", 40, "Limassol", 13],
    ["Armando González", "FW", 23, "Guadalajara", 14],
    ["Israel Reyes", "DF", 26, "Club América", 15],
    ["Julián Quiñones", "FW", 29, "Al-Qadsiah", 16],
    ["Orbelín Pineda", "MF", 30, "AEK Athens", 17],
    ["Obed Vargas", "MF", 20, "Atlético Madrid", 18],
    ["Gilberto Mora", "MF", 17, "Club Tijuana", 19],
    ["Mateo Chávez", "DF", 22, "AZ Alkmaar", 20],
    ["César Huerta", "FW", 25, "Anderlecht", 21],
    ["Guillermo Martínez", "FW", 31, "Pumas", 22],
    ["Jesús Gallardo", "DF", 31, "Toluca", 23],
    ["Luis Chávez", "MF", 30, "Dynamo Moscow", 24],
    ["Roberto Alvarado", "FW", 27, "Guadalajara", 25],
    ["Brian Gutiérrez", "MF", 22, "Guadalajara", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "South Africa": [
    ["Ronwen Williams", "GK", 34, "Mamelodi Sundowns", 1],
    ["Thabang Matuludi", "DF", 27, "Polokwane City", 2],
    ["Khulumani Ndamane", "DF", 22, "Mamelodi Sundowns", 3],
    ["Teboho Mokoena", "MF", 29, "Mamelodi Sundowns", 4],
    ["Thalente Mbatha", "MF", 26, "Orlando Pirates", 5],
    ["Aubrey Modiba", "MF", 30, "Mamelodi Sundowns", 6],
    ["Oswin Appollis", "FW", 24, "Orlando Pirates", 7],
    ["Tshepang Moremi", "FW", 25, "Orlando Pirates", 8],
    ["Lyle Foster", "FW", 25, "Burnley", 9],
    ["Relebohile Mofokeng", "FW", 21, "Orlando Pirates", 10],
    ["Themba Zwane", "FW", 36, "Mamelodi Sundowns", 11],
    ["Thapelo Maseko", "FW", 22, "Mamelodi Sundowns", 12],
    ["Sphephelo Sithole", "MF", 27, "CD Tondela", 13],
    ["Mbekezeli Mbokazi", "DF", 20, "Chicago Fire", 14],
    ["Iqraam Rayners", "FW", 30, "Mamelodi Sundowns", 15],
    ["Sipho Chaine", "GK", 29, "Orlando Pirates", 16],
    ["Evidence Makgopa", "FW", 26, "Orlando Pirates", 17],
    ["Samukele Kabini", "DF", 22, "Molde", 18],
    ["Nkosinathi Sibisi", "DF", 30, "Orlando Pirates", 19],
    ["Khuliso Mudau", "DF", 31, "Mamelodi Sundowns", 20],
    ["Ime Okon", "DF", 22, "Hannover 96", 21],
    ["Ricardo Goss", "GK", 32, "Siwelele FC", 22],
    ["Jayden Adams", "MF", 25, "Mamelodi Sundowns", 23],
    ["Olwethu Makhanya", "DF", 22, "Philadelphia Union", 24],
    ["Kamogelo Sebelebele", "DF", 23, "Orlando Pirates", 25],
    ["Bradley Cross", "DF", 25, "Kaizer Chiefs", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "South Korea": [
    ["Kim Seung-gyu", "GK", 35, "FC Tokyo", 1],
    ["Lee Han-beom", "DF", 23, "FC Midtjylland", 2],
    ["Lee Ki-hyuk", "DF", 25, "Gangwon FC", 3],
    ["Kim Min-jae", "DF", 29, "Bayern Munich", 4],
    ["Kim Tae-hyeon", "DF", 25, "Kashima Antlers", 5],
    ["Hwang In-beom", "MF", 29, "Feyenoord", 6],
    ["Son Heung-min", "FW", 33, "Los Angeles FC", 7],
    ["Paik Seung-ho", "MF", 29, "Birmingham City", 8],
    ["Cho Gue-sung", "FW", 28, "FC Midtjylland", 9],
    ["Lee Jae-sung", "MF", 33, "Mainz 05", 10],
    ["Hwang Hee-chan", "FW", 30, "Wolves", 11],
    ["Song Bum-keun", "GK", 28, "Jeonbuk Hyundai Motors", 12],
    ["Lee Tae-seok", "DF", 23, "Austria Wien", 13],
    ["Cho Wi-je", "DF", 24, "Jeonbuk Hyundai Motors", 14],
    ["Kim Moon-hwan", "DF", 30, "Daejeon Hana Citizen", 15],
    ["Park Jin-seob", "DF", 30, "Zhejiang FC", 16],
    ["Bae Jun-ho", "FW", 22, "Stoke City", 17],
    ["Oh Hyeon-gyu", "FW", 25, "Besiktas", 18],
    ["Lee Kang-in", "FW", 25, "Paris St-Germain", 19],
    ["Yang Hyun-jun", "MF", 24, "Celtic", 20],
    ["Jo Hyeon-woo", "GK", 34, "Ulsan HD FC", 21],
    ["Seol Young-woo", "DF", 27, "Red Star Belgrade", 22],
    ["Jens Castrop", "DF", 22, "Borussia Mönchengladbach", 23],
    ["Kim Jin-gyu", "MF", 29, "Jeonbuk Hyundai Motors", 24],
    ["Eom Ji-sung", "FW", 24, "Swansea City", 25],
    ["Lee Dong-gyeong", "MF", 28, "Ulsan Hyundai", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Czech Republic": [
    ["Matej Kovar", "GK", 26, "PSV Eindhoven", 1],
    ["David Zima", "DF", 25, "Slavia Prague", 2],
    ["Tomas Holes", "DF", 33, "Slavia Prague", 3],
    ["Robin Hranac", "DF", 26, "Hoffenheim", 4],
    ["Vladimir Coufal", "DF", 33, "Hoffenheim", 5],
    ["Stepan Chaloupek", "DF", 23, "Slavia Prague", 6],
    ["Ladislav Krejci", "DF", 27, "Wolves", 7],
    ["Vladimír Darida", "MF", 35, "Hradec Kralove", 8],
    ["Adam Hlozek", "FW", 23, "Hoffenheim", 9],
    ["Patrik Schick", "FW", 30, "Bayer Leverkusen", 10],
    ["Jan Kuchta", "FW", 29, "Sparta Prague", 11],
    ["Lukas Cerv", "MF", 25, "Viktoria Plzen", 12],
    ["Mojmir Chytil", "FW", 27, "Slavia Prague", 13],
    ["David Jurasek", "DF", 25, "Slavia Prague", 14],
    ["Pavel Sulc", "MF", 25, "Lyon", 15],
    ["Jindrich Stanek", "GK", 30, "Slavia Prague", 16],
    ["Lukas Provod", "FW", 29, "Slavia Prague", 17],
    ["Michal Sadilek", "MF", 27, "Slavia Prague", 18],
    ["Tomas Chory", "FW", 31, "Slavia Prague", 19],
    ["Jaroslav Zeleny", "DF", 33, "Sparta Prague", 20],
    ["David Doudera", "DF", 28, "Slavia Prague", 21],
    ["Tomas Soucek", "MF", 31, "West Ham", 22],
    ["Lukas Hornicek", "GK", 23, "Braga", 23],
    ["Alexandr Sojka", "MF", 23, "Viktoria Plzen", 24],
    ["Hugo Sochurek", "MF", 18, "Sparta Prague", 25],
    ["Denis Visinsky", "MF", 23, "Viktoria Plzen", 26],
  ],
}
