import type { RosterTuple } from '../player-types'

export const GROUP_F_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "Netherlands": [
    ["Bart Verbruggen", "GK", 23, "Brighton", 1],
    ["Lutsharel Geertruida", "DF", 25, "RB Leipzig", 2],
    ["Marten de Roon", "MF", 35, "Atalanta", 3],
    ["Virgil van Dijk", "DF", 34, "Liverpool", 4],
    ["Nathan Aké", "DF", 31, "Manchester City", 5],
    ["Jan Paul van Hecke", "DF", 26, "Brighton", 6],
    ["Justin Kluivert", "FW", 27, "Bournemouth", 7],
    ["Ryan Gravenberch", "MF", 24, "Liverpool", 8],
    ["Wout Weghorst", "FW", 33, "Ajax", 9],
    ["Memphis Depay", "FW", 32, "Corinthians", 10],
    ["Cody Gakpo", "FW", 27, "Liverpool", 11],
    ["Mats Wieffer", "MF", 26, "Brighton", 12],
    ["Robin Roefs", "GK", 23, "Sunderland", 13],
    ["Tijjani Reijnders", "MF", 27, "Manchester City", 14],
    ["Micky van de Ven", "DF", 25, "Tottenham", 15],
    ["Guus Til", "MF", 28, "PSV Eindhoven", 16],
    ["Noa Lang", "FW", 26, "Napoli", 17],
    ["Donyell Malen", "FW", 27, "Roma", 18],
    ["Brian Brobbey", "FW", 24, "Sunderland", 19],
    ["Teun Koopmeiners", "MF", 28, "Juventus", 20],
    ["Frenkie de Jong", "MF", 29, "Barcelona", 21],
    ["Denzel Dumfries", "DF", 30, "Inter", 22],
    ["Mark Flekken", "GK", 32, "Bayer Leverkusen", 23],
    ["Crysencio Summerville", "FW", 24, "West Ham", 24],
    ["Jorrel Hato", "DF", 20, "Chelsea", 25],
    ["Quinten Timber", "MF", 24, "Marseille", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Japan": [
    ["Zion Suzuki", "GK", 23, "Parma", 1],
    ["Yukinari Sugawara", "DF", 25, "Southampton", 2],
    ["Shogo Taniguchi", "DF", 34, "Sint-Truiden", 3],
    ["Ko Itakura", "DF", 29, "Ajax", 4],
    ["Yuto Nagatomo", "DF", 39, "FC Tokyo", 5],
    ["Wataru Endo", "MF", 33, "Liverpool", 6],
    ["Ao Tanaka", "MF", 27, "Leeds", 7],
    ["Takefusa Kubo", "FW", 25, "Real Sociedad", 8],
    ["Keisuke Goto", "FW", 21, "Sint-Truidense", 9],
    ["Ritsu Doan", "FW", 27, "Eintracht Frankfurt", 10],
    ["Daizen Maeda", "FW", 28, "Celtic", 11],
    ["Keisuke Osako", "GK", 26, "Sanfrecce Hiroshima", 12],
    ["Keito Nakamura", "FW", 25, "Stade de Reims", 13],
    ["Junya Ito", "FW", 33, "KRC Genk", 14],
    ["Daichi Kamada", "MF", 29, "Crystal Palace", 15],
    ["Tsuyoshi Watanabe", "DF", 29, "Feyenoord", 16],
    ["Yuito Suzuki", "MF", 24, "Freiburg", 17],
    ["Ayase Ueda", "FW", 27, "Feyenoord", 18],
    ["Koki Ogawa", "FW", 28, "NEC Nijmegen", 19],
    ["Ayumu Seko", "DF", 26, "Le Havre", 20],
    ["Hiroki Ito", "DF", 27, "Bayern Munich", 21],
    ["Takehiro Tomiyasu", "DF", 27, "Ajax", 22],
    ["Tomoki Hayakawa", "GK", 27, "Kashima Antlers", 23],
    ["Kaishu Sano", "MF", 25, "Mainz", 24],
    ["Junnosuke Suzuki", "DF", 22, "FC Copenhagen", 25],
    ["Kento Shiogai", "FW", 21, "Wolfsburg", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Sweden": [
    ["Jacob Widell Zetterström", "GK", 27, "Derby County", 1],
    ["Gustaf Lagerbielke", "DF", 26, "Braga", 2],
    ["Victor Lindelöf", "DF", 31, "Aston Villa", 3],
    ["Isak Hien", "DF", 27, "Atalanta", 4],
    ["Gabriel Gudmundsson", "DF", 27, "Leeds", 5],
    ["Herman Johansson", "DF", 28, "FC Dallas", 6],
    ["Lucas Bergvall", "MF", 20, "Tottenham", 7],
    ["Daniel Svensson", "DF", 24, "Borussia Dortmund", 8],
    ["Alexander Isak", "FW", 26, "Liverpool", 9],
    ["Benjamin Nygren", "FW", 24, "Celtic", 10],
    ["Anthony Elanga", "FW", 24, "Newcastle", 11],
    ["Viktor Johansson", "GK", 27, "Stoke City", 12],
    ["Ken Sema", "MF", 32, "Pafos FC", 13],
    ["Hjalmar Ekdal", "DF", 27, "Burnley", 14],
    ["Carl Starfelt", "DF", 31, "Celta Vigo", 15],
    ["Jesper Karlström", "MF", 30, "Udinese", 16],
    ["Viktor Gyökeres", "FW", 28, "Arsenal", 17],
    ["Yasin Ayari", "MF", 22, "Brighton", 18],
    ["Mattias Svanberg", "MF", 27, "Wolfsburg", 19],
    ["Eric Smith", "DF", 29, "St Pauli", 20],
    ["Alexander Bernhardsson", "MF", 27, "Holstein Kiel", 21],
    ["Besfort Zeneli", "MF", 23, "Union Saint-Gilloise", 22],
    ["Kristoffer Nordfeldt", "GK", 36, "AIK", 23],
    ["Elliot Stroud", "DF", 23, "Mjällby", 24],
    ["Gustaf Nilsson", "FW", 29, "Club Brugge", 25],
    ["Taha Ali", "FW", 27, "Malmö FF", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Tunisia": [
    ["Mouhib Chamakh", "GK", 24, "Club Africain", 1],
    ["Ali Abdi", "DF", 32, "Nice", 2],
    ["Montassar Talbi", "DF", 28, "Lorient", 3],
    ["Omar Rekik", "DF", 24, "Maribor", 4],
    ["Adem Arous", "DF", 21, "Kasimpasa", 5],
    ["Dylan Bronn", "DF", 30, "Servette", 6],
    ["Elias Achouri", "FW", 27, "FC Copenhagen", 7],
    ["Elias Saad", "FW", 26, "Augsburg", 8],
    ["Hazem Mastouri", "FW", 28, "Dynamo Makhachkala", 9],
    ["Hannibal Mejbri", "MF", 23, "Burnley", 10],
    ["Ismaël Gharbi", "MF", 22, "Braga", 11],
    ["Mortadha Ben Ouanes", "MF", 31, "Kasimpasa", 12],
    ["Rani Khedira", "MF", 32, "Union Berlin", 13],
    ["Khalil Ayari", "FW", 21, "Paris St-Germain", 14],
    ["Hadj Mahmoud", "MF", 26, "Lugano", 15],
    ["Aymen Dahmen", "GK", 29, "CS Sfaxien", 16],
    ["Ellyes Skhiri", "MF", 31, "Eintracht Frankfurt", 17],
    ["Rayan Elloumi", "FW", 18, "Vancouver", 18],
    ["Firas Chaouat", "FW", 30, "Club Africain", 19],
    ["Yan Valery", "DF", 27, "Sheffield Wednesday", 20],
    ["Mohamed Amine Ben Hmida", "DF", 30, "Espérance de Tunis", 21],
    ["Sabri Ben Hessen", "GK", 29, "Étoile du Sahel", 22],
    ["Moutaz Neffati", "DF", 21, "IFK Norrköping", 23],
    ["Raed Chikhaoui", "DF", 22, "US Monastir", 24],
    ["Anis Ben Slimane", "MF", 25, "Norwich City", 25],
    ["Sebastien Tounekti", "FW", 23, "Celtic", 26],
  ],
}
