import type { RosterTuple } from '../player-types'

export const GROUP_G_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "Belgium": [
    ["Thibaut Courtois", "GK", 34, "Real Madrid", 1],
    ["Zeno Debast", "DF", 22, "Sporting", 2],
    ["Arthur Theate", "DF", 26, "Eintracht Frankfurt", 3],
    ["Brandon Mechele", "DF", 34, "Club Brugge", 4],
    ["Maxim De Cuyper", "DF", 25, "Brighton", 5],
    ["Axel Witsel", "MF", 37, "Girona", 6],
    ["Kevin De Bruyne", "MF", 34, "Napoli", 7],
    ["Youri Tielemans", "MF", 29, "Aston Villa", 8],
    ["Romelu Lukaku", "FW", 33, "Napoli", 9],
    ["Leandro Trossard", "FW", 31, "Arsenal", 10],
    ["Jérémy Doku", "FW", 24, "Manchester City", 11],
    ["Senne Lammens", "GK", 23, "Manchester United", 12],
    ["Mike Penders", "GK", 20, "Chelsea", 13],
    ["Dodi Lukébakio", "FW", 28, "Benfica", 14],
    ["Thomas Meunier", "DF", 34, "Lille", 15],
    ["Koni De Winter", "DF", 23, "Milan", 16],
    ["Charles De Ketelaere", "FW", 25, "Atalanta", 17],
    ["Joaquin Seys", "DF", 21, "Club Brugge", 18],
    ["Diego Moreira", "FW", 21, "Strasbourg", 19],
    ["Hans Vanaken", "MF", 33, "Club Brugge", 20],
    ["Timothy Castagne", "DF", 30, "Fulham", 21],
    ["Alexis Saelemaekers", "FW", 26, "Milan", 22],
    ["Nicolas Raskin", "MF", 25, "Rangers", 23],
    ["Amadou Onana", "MF", 24, "Aston Villa", 24],
    ["Nathan Ngoy", "DF", 23, "Lille", 25],
    ["Matias Fernandez-Pardo", "FW", 21, "Lille", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Iran": [
    ["Alireza Beiranvand", "GK", 33, "Tractor", 1],
    ["Saleh Hardani", "DF", 27, "Esteghlal", 2],
    ["Ehsan Hajsafi", "DF", 36, "Sepahan", 3],
    ["Shoja Khalilzadeh", "DF", 37, "Tractor", 4],
    ["Milad Mohammadi", "DF", 32, "Persepolis", 5],
    ["Saeid Ezatolahi", "MF", 29, "Shabab Al-Ahli", 6],
    ["Alireza Jahanbakhsh", "FW", 32, "Dender", 7],
    ["Mohammad Mohebi", "FW", 27, "Rostov", 8],
    ["Mehdi Taremi", "FW", 33, "Olympiakos", 9],
    ["Mehdi Ghaedi", "FW", 27, "Al Nassr", 10],
    ["Ali Alipour", "FW", 30, "Persepolis", 11],
    ["Payam Niazmand", "GK", 31, "Persepolis", 12],
    ["Hossein Kanaani-Zadegan", "DF", 32, "Persepolis", 13],
    ["Saman Ghoddos", "MF", 32, "Al Ittihad Kalba", 14],
    ["Rouzbeh Cheshmi", "MF", 32, "Esteghlal", 15],
    ["Mehdi Torabi", "FW", 31, "Tractor", 16],
    ["Aria Yousefi", "DF", 24, "Sepahan", 17],
    ["Amirhossein Hosseinzadeh", "FW", 25, "Tractor", 18],
    ["Ali Nemati", "DF", 30, "Foolad Khuzestan", 19],
    ["Shahriar Moghanloo", "FW", 31, "Kalba", 20],
    ["Mohammad Ghorbani", "MF", 25, "Al Wahda", 21],
    ["Seyed Hossein Hosseini", "GK", 33, "Sepahan", 22],
    ["Ramin Rezaeian", "DF", 36, "Foolad Khuzestan", 23],
    ["Dennis-Yerai Eckert Ayensa", "FW", 29, "Standard Liège", 24],
    ["Danial Eiri", "DF", 22, "Malavan", 25],
    ["Amirmohammad Razzaghinia", "MF", 20, "Esteghlal", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "New Zealand": [
    ["Max Crocombe", "GK", 32, "Millwall", 1],
    ["Tim Payne", "DF", 32, "Wellington Phoenix", 2],
    ["Francis de Vries", "DF", 31, "Auckland FC", 3],
    ["Tyler Bindon", "DF", 21, "Sheffield United", 4],
    ["Michael Boxall", "DF", 37, "Minnesota United", 5],
    ["Joe Bell", "MF", 27, "Viking", 6],
    ["Matt Garbett", "MF", 24, "Peterborough United", 7],
    ["Marko Stamenić", "MF", 24, "Swansea City", 8],
    ["Chris Wood", "FW", 34, "Nottingham Forest", 9],
    ["Sarpreet Singh", "MF", 27, "Backa Topola", 10],
    ["Eli Just", "FW", 26, "Motherwell", 11],
    ["Alex Paulsen", "GK", 23, "Bournemouth", 12],
    ["Liberato Cacace", "DF", 25, "Wrexham", 13],
    ["Alex Rufer", "MF", 29, "Wellington Phoenix", 14],
    ["Nando Pijnaker", "DF", 27, "Auckland FC", 15],
    ["Finn Surman", "DF", 22, "Portland", 16],
    ["Kosta Barbarouses", "FW", 36, "Western Sydney Wanderers", 17],
    ["Ben Waine", "FW", 25, "Port Vale", 18],
    ["Ben Old", "FW", 23, "St Étienne", 19],
    ["Callum McCowatt", "FW", 27, "Silkeborg", 20],
    ["Jesse Randall", "FW", 23, "Auckland FC", 21],
    ["Michael Woud", "GK", 27, "Auckland FC", 22],
    ["Ryan Thomas", "MF", 31, "PEC Zwolle", 23],
    ["Callan Elliot", "DF", 26, "Auckland FC", 24],
    ["Lachlan Bayliss", "MF", 23, "Newcastle Jets", 25],
    ["Tommy Smith", "DF", 36, "Braintree Town", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Egypt": [
    ["Mohamed El-Shenawy", "GK", 37, "Al Ahly", 1],
    ["Yasser Ibrahim", "DF", 33, "Al Ahly", 2],
    ["Mohamed Hany", "DF", 30, "Al Ahly", 3],
    ["Hossam Abdelmaguid", "DF", 25, "Zamalek", 4],
    ["Ramy Rabia", "DF", 33, "Al Ain", 5],
    ["Mohamed Abdelmonem", "DF", 27, "Nice", 6],
    ["Mahmoud Hassan ‘Trezeguet’", "FW", 31, "Al Ahly", 7],
    ["Emam Ashour", "MF", 28, "Al Ahly", 8],
    ["Hamza Abdelkarim", "FW", 18, "Al Ahly", 9],
    ["Mohamed Salah", "FW", 33, "Liverpool", 10],
    ["Mostafa Ziko", "MF", 29, "Pyramids FC", 11],
    ["Haissem Hassan", "FW", 24, "Real Oviedo", 12],
    ["Ahmed Fatouh", "DF", 28, "Zamalek", 13],
    ["Hamdy Fathy", "MF", 31, "Al-Wakrah", 14],
    ["Karim Hafez", "DF", 30, "Pyramids FC", 15],
    ["El Mahdy Soliman", "GK", 39, "Zamalek", 16],
    ["Mohanad Lasheen", "MF", 30, "Pyramids FC", 17],
    ["Nabil 'Dunga' Emad", "MF", 30, "Al-Najma", 18],
    ["Marwan Attia", "MF", 27, "Al Ahly", 19],
    ["Ibrahim Adel", "FW", 25, "FC Nordsjælland", 20],
    ["Mahmoud Saber", "MF", 24, "Pyramids FC", 21],
    ["Omar Marmoush", "FW", 27, "Manchester City", 22],
    ["Mostafa ‘Oufa’ Shobeir", "GK", 26, "Al Ahly", 23],
    ["Tarek Alaa", "DF", 24, "Pyramids FC", 24],
    ["Ahmed Sayed ‘Zizo’", "FW", 30, "Al Ahly", 25],
    ["Mohamed Alaa", "GK", 27, "El Gouna", 26],
  ],
}
