import type { RosterTuple } from '../player-types'

export const GROUP_L_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "England": [
    ["Jordan Pickford", "GK", 32, "Everton", 1],
    ["Ezri Konsa", "DF", 28, "Aston Villa", 2],
    ["Nico O’Reilly", "DF", 21, "Manchester City", 3],
    ["Declan Rice", "MF", 27, "Arsenal", 4],
    ["John Stones", "DF", 32, "Manchester City", 5],
    ["Marc Guéhi", "DF", 25, "Manchester City", 6],
    ["Bukayo Saka", "FW", 24, "Arsenal", 7],
    ["Elliot Anderson", "MF", 23, "Nottingham Forest", 8],
    ["Harry Kane", "FW", 32, "Bayern Munich", 9],
    ["Jude Bellingham", "MF", 22, "Real Madrid", 10],
    ["Marcus Rashford", "FW", 28, "Manchester United", 11],
    ["Tino Livramento", "DF", 23, "Newcastle", 12],
    ["Dean Henderson", "GK", 29, "Crystal Palace", 13],
    ["Jordan Henderson", "MF", 35, "Brentford", 14],
    ["Dan Burn", "DF", 34, "Newcastle", 15],
    ["Kobbie Mainoo", "MF", 21, "Manchester United", 16],
    ["Morgan Rogers", "MF", 23, "Aston Villa", 17],
    ["Anthony Gordon", "FW", 25, "Newcastle", 18],
    ["Ollie Watkins", "FW", 30, "Aston Villa", 19],
    ["Noni Madueke", "FW", 24, "Arsenal", 20],
    ["Eberechi Eze", "MF", 27, "Arsenal", 21],
    ["Ivan Toney", "FW", 30, "Al-Ahli", 22],
    ["James Trafford", "GK", 23, "Manchester City", 23],
    ["Reece James", "DF", 26, "Chelsea", 24],
    ["Djed Spence", "DF", 25, "Tottenham", 25],
    ["Jarell Quansah", "DF", 23, "Bayer Leverkusen", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Croatia": [
    ["Dominik Livakovic", "GK", 31, "Fenerbahce", 1],
    ["Josip Stanisic", "DF", 26, "Bayern Munich", 2],
    ["Marin Pongracic", "DF", 28, "Fiorentina", 3],
    ["Josko Gvardiol", "DF", 24, "Manchester City", 4],
    ["Duje Caleta-Car", "DF", 29, "Lyon", 5],
    ["Josip Sutalo", "DF", 26, "Ajax", 6],
    ["Nikola Moro", "MF", 28, "Bologna", 7],
    ["Mateo Kovacic", "MF", 32, "Manchester City", 8],
    ["Andrej Kramaric", "FW", 34, "Hoffenheim", 9],
    ["Luka Modric", "MF", 40, "Milan", 10],
    ["Ante Budimir", "FW", 34, "Osasuna", 11],
    ["Ivor Pandur", "GK", 26, "Hull City", 12],
    ["Nikola Vlasic", "MF", 28, "Torino", 13],
    ["Ivan Perisic", "FW", 37, "PSV Eindhoven", 14],
    ["Mario Pasalic", "MF", 31, "Atalanta", 15],
    ["Martin Baturina", "MF", 23, "Como", 16],
    ["Petar Sucic", "MF", 22, "Inter", 17],
    ["Kristijan Jakic", "MF", 29, "Augsburg", 18],
    ["Toni Fruk", "MF", 25, "Rijeka", 19],
    ["Igor Matanovic", "FW", 23, "Freiburg", 20],
    ["Luka Sucic", "MF", 23, "Real Sociedad", 21],
    ["Luka Vuskovic", "DF", 19, "Tottenham", 22],
    ["Dominik Kotarski", "GK", 26, "FC Copenhagen", 23],
    ["Marco Pasalic", "FW", 25, "Orlando City", 24],
    ["Martin Erlic", "DF", 28, "Midtjylland", 25],
    ["Petar Musa", "FW", 28, "FC Dallas", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Ghana": [
    ["Lawrence Ati-Zigi", "GK", 29, "St Gallen", 1],
    ["Alidu Seidu", "DF", 26, "Rennes", 2],
    ["Caleb Yirenkyi", "MF", 20, "FC Nordsjælland", 3],
    ["Jonas Adjetey", "DF", 22, "Wolfsburg", 4],
    ["Thomas Partey", "MF", 32, "Villarreal", 5],
    ["Abdul Mumin", "DF", 28, "Rayo Vallecano", 6],
    ["Abdul Fatawu", "FW", 22, "Leicester", 7],
    ["Kwasi Sibo", "MF", 27, "Real Oviedo", 8],
    ["Jordan Ayew", "FW", 34, "Leicester", 9],
    ["Brandon Thomas-Asante", "FW", 27, "Coventry City", 10],
    ["Antoine Semenyo", "FW", 26, "Manchester City", 11],
    ["Joseph Anang", "GK", 26, "St Patrick's Athletic", 12],
    ["Christopher Bonsu Baah", "FW", 21, "Al-Qadsiah", 13],
    ["Gideon Mensah", "DF", 27, "Auxerre", 14],
    ["Elisha Owusu", "MF", 28, "Auxerre", 15],
    ["Benjamin Asare", "GK", 33, "Hearts of Oak", 16],
    ["Baba Rahman", "DF", 31, "PAOK", 17],
    ["Jerome Opoku", "DF", 27, "Basaksehir", 18],
    ["Iñaki Williams", "FW", 31, "Athletic Bilbao", 19],
    ["Augustine Boakye", "MF", 25, "Saint-Étienne", 20],
    ["Kojo Peprah Oppong", "DF", 22, "Nice", 21],
    ["Kamaldeen Sulemana", "FW", 24, "Atalanta", 22],
    ["Derrick Luckassen", "DF", 30, "Pafos", 23],
    ["Ernest Nuamah", "FW", 22, "Lyon", 24],
    ["Prince Kwabena Adu", "FW", 22, "Viktoria Plzen", 25],
    ["Marvin Senaya", "DF", 25, "Auxerre", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Panama": [
    ["Luis Mejía", "GK", 35, "Nacional", 1],
    ["César Blackman", "DF", 28, "Slovan Bratislava", 2],
    ["José Córdoba", "DF", 25, "Norwich", 3],
    ["Fidel Escobar", "DF", 31, "Saprissa", 4],
    ["Edgardo Fariña", "DF", 24, "Nizhny Novgorod", 5],
    ["Cristian Martínez", "MF", 29, "Kiryat Shmona", 6],
    ["José Luis Rodríguez", "FW", 27, "FC Juárez", 7],
    ["Adalberto Carrasquilla", "MF", 27, "Pumas", 8],
    ["Tomás Rodríguez", "FW", 27, "Saprissa", 9],
    ["Ismael Díaz", "FW", 29, "Club León", 10],
    ["Édgar Yoel Bárcenas", "FW", 32, "Mazatlán", 11],
    ["César Samudio", "GK", 32, "Marathón", 12],
    ["Jiovany Ramos", "DF", 29, "Academia Puerto Cabello", 13],
    ["Carlos Harvey", "MF", 26, "Minnesota United", 14],
    ["Eric Davis", "DF", 35, "Plaza Amador", 15],
    ["Andrés Andrade", "DF", 27, "LASK", 16],
    ["José Fajardo", "FW", 32, "Universidad Católica", 17],
    ["Cecilio Waterman", "FW", 35, "Universidad de Concepción", 18],
    ["Alberto Quintero", "FW", 38, "Plaza Amador", 19],
    ["Aníbal Godoy", "MF", 36, "San Diego FC", 20],
    ["César Yanis", "FW", 30, "Cobresal", 21],
    ["Orlando Mosquera", "GK", 31, "Al-Fayha", 22],
    ["Michael Amir Murillo", "DF", 30, "Besiktas", 23],
    ["Azarías Londoño", "FW", 24, "Universidad Católica", 24],
    ["Roderick Miller", "DF", 34, "Turan Tovuz", 25],
    ["Jorge Gutiérrez", "DF", 27, "Deportivo La Guaira", 26],
  ],
}
