import type { RosterTuple } from '../player-types'

export const GROUP_G_SQUADS: Record<string, RosterTuple[]> = {
  Belgium: [
    ['Koen Casteels', 'GK', 32, 'Wolfsburg', 1], ['Matz Sels', 'GK', 32, 'Strasbourg', 2],
    ['Timothy Castagne', 'DF', 29, 'Fulham', 3], ['Jan Vertonghen', 'DF', 37, 'Anderlecht', 4],
    ['Arthur Theate', 'DF', 24, 'Rennes', 5], ['Zeno Debast', 'DF', 21, 'Sporting CP', 6],
    ['Thomas Meunier', 'DF', 33, 'Lille', 7], ['Arthur Theate', 'DF', 24, 'Rennes', 8],
    ['Kevin De Bruyne', 'MF', 33, 'Manchester City', 9], ['Youri Tielemans', 'MF', 27, 'Aston Villa', 10],
    ['Amadou Onana', 'MF', 23, 'Everton', 11], ['Orel Mangala', 'MF', 26, 'Lyon', 12],
    ['Jeremy Doku', 'MF', 22, 'Manchester City', 13], ['Romelu Lukaku', 'FW', 31, 'Roma', 14],
    ['Loïs Openda', 'FW', 25, 'Leipzig', 15], ['Dodi Lukebakio', 'FW', 27, 'Sevilla', 16],
    ['Charles De Ketelaere', 'FW', 23, 'Atalanta', 17], ['Jérémy Doku', 'FW', 22, 'Manchester City', 18],
    ['Michy Batshuayi', 'FW', 31, 'Fenerbahçe', 19], ['Loïs Openda', 'FW', 25, 'Leipzig', 20],
  ],
  Iran: [
    ['Alireza Beiranvand', 'GK', 32, 'Persepolis', 1], ['Hossein Hosseini', 'GK', 32, 'Esteghlal', 2],
    ['Morteza Pouraliganji', 'DF', 32, 'Persepolis', 3], ['Hossein Kanaani', 'DF', 30, 'Sepahan', 4],
    ['Shojae Khalilzadeh', 'DF', 35, 'Tractor', 5], ['Milad Mohammadi', 'DF', 30, 'Akhmat Grozny', 6],
    ['Roozbeh Cheshmi', 'DF', 31, 'Esteghlal', 7], ['Sadegh Moharrami', 'DF', 28, 'Dinamo Zagreb', 8],
    ['Alireza Jahanbakhsh', 'MF', 31, 'Feyenoord', 9], ['Saeid Ezatolahi', 'MF', 28, 'Anderlecht', 10],
    ['Mehdi Torabi', 'MF', 29, 'Persepolis', 11], ['Ali Gholizadeh', 'MF', 28, 'Charleroi', 12],
    ['Vahid Amiri', 'MF', 36, 'Persepolis', 13], ['Sardar Azmoun', 'FW', 30, 'Shabab Al Ahli', 14],
    ['Mehdi Taremi', 'FW', 33, 'Inter Milan', 15], ['Kaveh Rezaei', 'FW', 32, 'Club Brugge', 16],
    ['Ali Gholizadeh', 'FW', 28, 'Charleroi', 17], ['Ramin Rezaian', 'FW', 34, 'Sepahan', 18],
    ['Vahid Amiri', 'FW', 36, 'Persepolis', 19], ['Sardar Azmoun', 'FW', 30, 'Shabab Al Ahli', 20],
  ],
  'New Zealand': [
    ['Oliver Sail', 'GK', 28, 'Wellington Phoenix', 1], ['Michael Boxall', 'GK', 35, 'Minnesota United', 2],
    ['Michael Boxall', 'DF', 35, 'Minnesota United', 3], ['Nando Pijankic', 'DF', 26, 'Auckland FC', 4],
    ['Liberato Cacace', 'DF', 24, 'Wellington Phoenix', 5], ['Bill Tuiloma', 'DF', 29, 'Portland Timbers', 6],
    ['Nando Pijankic', 'DF', 26, 'Auckland FC', 7], ['Liberato Cacace', 'DF', 24, 'Wellington Phoenix', 8],
    ['Marko Stamenic', 'MF', 23, 'Nottingham Forest', 9], ['Joe Bell', 'MF', 26, 'Viking', 10],
    ['Alex Paulsen', 'MF', 22, 'Bournemouth', 11], ['Sarpreet Singh', 'MF', 25, 'Wellington Phoenix', 12],
    ['Marko Stamenic', 'MF', 23, 'Nottingham Forest', 13], ['Chris Wood', 'FW', 33, 'Nottingham Forest', 14],
    ['Ben Waine', 'FW', 23, 'Wellington Phoenix', 15], ['Elijah Just', 'FW', 25, 'HJK Helsinki', 16],
    ['Garbett Marco', 'FW', 31, 'Auckland FC', 17], ['Ben Waine', 'FW', 23, 'Wellington Phoenix', 18],
    ['Chris Wood', 'FW', 33, 'Nottingham Forest', 19], ['Elijah Just', 'FW', 25, 'HJK Helsinki', 20],
  ],
  Egypt: [
    ['Mohamed El Shenawy', 'GK', 36, 'Al Ahly', 1], ['Mohamed Abou Gabal', 'GK', 35, 'Zamalek', 2],
    ['Ahmed Hegazi', 'DF', 33, 'Al Ittihad', 3], ['Mohamed Abdelmonsef', 'DF', 32, 'Zamalek', 4],
    ['Ayman Ashraf', 'DF', 33, 'Al Ahly', 5], ['Mohamed Hany', 'DF', 28, 'Al Ahly', 6],
    ['Ahmed Fatouh', 'DF', 26, 'Zamalek', 7], ['Omar Kamal', 'DF', 30, 'National Bank', 8],
    ['Mohamed Elneny', 'MF', 32, 'Arsenal', 9], ['Emam Ashour', 'MF', 26, 'Al Ahly', 10],
    ['Trézéguet', 'MF', 30, 'Al Ahly', 11], ['Mohamed Salah', 'MF', 32, 'Liverpool', 12],
    ['Emam Ashour', 'MF', 26, 'Al Ahly', 13], ['Mohamed Salah', 'FW', 32, 'Liverpool', 14],
    ['Omar Marmoush', 'FW', 25, 'Eintracht Frankfurt', 15], ['Mostafa Mohamed', 'FW', 27, 'Nantes', 16],
    ['Trézéguet', 'FW', 30, 'Al Ahly', 17], ['Omar Marmoush', 'FW', 25, 'Eintracht Frankfurt', 18],
    ['Ahmed Hassan', 'FW', 31, 'Panathinaikos', 19], ['Mostafa Mohamed', 'FW', 27, 'Nantes', 20],
  ],
}