import type { RosterTuple } from '../player-types'

export const GROUP_J_SQUADS: Record<string, RosterTuple[]> = {
  Argentina: [
    ['Emiliano Martínez', 'GK', 32, 'Aston Villa', 1], ['Franco Armani', 'GK', 37, 'River Plate', 2],
    ['Cristian Romero', 'DF', 27, 'Tottenham', 3], ['Nicolás Otamendi', 'DF', 36, 'Benfica', 4],
    ['Nahuel Molina', 'DF', 27, 'Atlético Madrid', 5], ['Marcos Acuña', 'DF', 33, 'Flamengo', 6],
    ['Nicolás Tagliafico', 'DF', 32, 'Lyon', 7], ['Germán Pezzella', 'DF', 33, 'River Plate', 8],
    ['Rodrigo De Paul', 'MF', 30, 'Atlético Madrid', 9], ['Leandro Paredes', 'MF', 30, 'Roma', 10],
    ['Enzo Fernández', 'MF', 24, 'Chelsea', 11], ['Alexis Mac Allister', 'MF', 26, 'Liverpool', 12],
    ['Giovani Lo Celso', 'MF', 28, 'Real Betis', 13], ['Lionel Messi', 'FW', 38, 'Inter Miami', 14],
    ['Lautaro Martínez', 'FW', 28, 'Inter Milan', 15], ['Ángel Di María', 'FW', 36, 'Benfica', 16],
    ['Julián Álvarez', 'FW', 25, 'Atlético Madrid', 17], ['Nicolás González', 'FW', 26, 'Juventus', 18],
    ['Alejandro Garnacho', 'FW', 20, 'Manchester United', 19], ['Paulo Dybala', 'FW', 31, 'Roma', 20],
  ],
  Algeria: [
    ['Raïs M\'Bolhi', 'GK', 38, 'CR Belouizdad', 1], ['Anthony Mandrea', 'GK', 28, 'Caen', 2],
    ['Aïssa Mandi', 'DF', 32, 'Villarreal', 3], ['Ramy Bensebaini', 'DF', 29, 'Borussia Dortmund', 4],
    ['Youcef Atal', 'DF', 28, 'Nice', 5], ['Mehdi Zeffane', 'DF', 32, 'CR Belouizdad', 6],
    ['Amin Ghezali', 'DF', 24, 'Belouizdad', 7], ['Houssem Aouar', 'DF', 26, 'Al Ittihad', 8],
    ['Ismaël Bennacer', 'MF', 27, 'AC Milan', 9], ['Ramiz Zerrouki', 'MF', 26, 'Twente', 10],
    ['Houssem Aouar', 'MF', 26, 'Al Ittihad', 11], ['Youcef Belaïli', 'MF', 32, 'Qadsia', 12],
    ['Riyad Mahrez', 'MF', 33, 'Al Ahli', 13], ['Baghdad Bounedjah', 'FW', 33, 'Al Shabab', 14],
    ['Riyad Mahrez', 'FW', 33, 'Al Ahli', 15], ['Islam Slimani', 'FW', 36, 'Anderlecht', 16],
    ['Youcef Belaïli', 'FW', 32, 'Qadsia', 17], ['Baghdad Bounedjah', 'FW', 33, 'Al Shabab', 18],
    ['Hilal El Hilali', 'FW', 24, 'Belouizdad', 19], ['Islam Slimani', 'FW', 36, 'Anderlecht', 20],
  ],
  Austria: [
    ['Heinz Lindner', 'GK', 34, 'Union Berlin', 1], ['Daniel Siebenhandl', 'GK', 33, 'LASK', 2],
    ['David Alaba', 'DF', 32, 'Real Madrid', 3], ['Kevin Wimmer', 'DF', 31, 'Gent', 4],
    ['Philipp Lienhart', 'DF', 28, 'Freiburg', 5], ['Stefan Posch', 'DF', 27, 'Bologna', 6],
    ['Andreas Ulmer', 'DF', 34, 'Salzburg', 7], ['Flavius Daniliuc', 'DF', 23, 'Salernitana', 8],
    ['Marcel Sabitzer', 'MF', 30, 'Borussia Dortmund', 9], ['Konrad Laimer', 'MF', 27, 'Bayern Munich', 10],
    ['Florian Grillitsch', 'MF', 29, 'Ajax', 11], ['Christoph Baumgartner', 'MF', 25, 'Leipzig', 12],
    ['Romano Schmid', 'MF', 24, 'Werder Bremen', 13], ['Marko Arnautović', 'FW', 35, 'Inter Milan', 14],
    ['Michael Gregoritsch', 'FW', 30, 'Freiburg', 15], ['Christoph Baumgartner', 'FW', 25, 'Leipzig', 16],
    ['Marko Arnautović', 'FW', 35, 'Inter Milan', 17], ['Michael Gregoritsch', 'FW', 30, 'Freiburg', 18],
    ['Romano Schmid', 'FW', 24, 'Werder Bremen', 19], ['Andreas Weimann', 'FW', 33, 'Stoke City', 20],
  ],
  Jordan: [
    ['Yazeed Abulaila', 'GK', 28, 'Al Ahli', 1], ['Amir Shafi', 'GK', 37, 'Al Hussein', 2],
    ['Yazan Al-Naimat', 'DF', 25, 'Al Arabi', 3], ['Bara Al-Rawashdeh', 'DF', 27, 'Al Faisaly', 4],
    ['Salem Al-Ajalin', 'DF', 29, 'Al Wehdat', 5], ['Mousa Al-Taamari', 'DF', 27, 'Montpellier', 6],
    ['Yazan Al-Naimat', 'DF', 25, 'Al Arabi', 7], ['Bara Al-Rawashdeh', 'DF', 27, 'Al Faisaly', 8],
    ['Mousa Al-Taamari', 'MF', 27, 'Montpellier', 9], ['Mahmoud Al-Mardi', 'MF', 28, 'Al Wehdat', 10],
    ['Ali Olwan', 'MF', 24, 'Al Faisaly', 11], ['Yazan Al-Naimat', 'MF', 25, 'Al Arabi', 12],
    ['Mahmoud Al-Mardi', 'MF', 28, 'Al Wehdat', 13], ['Ali Olwan', 'FW', 24, 'Al Faisaly', 14],
    ['Mousa Al-Taamari', 'FW', 27, 'Montpellier', 15], ['Mahmoud Al-Mardi', 'FW', 28, 'Al Wehdat', 16],
    ['Yazan Al-Naimat', 'FW', 25, 'Al Arabi', 17], ['Bara Al-Rawashdeh', 'FW', 27, 'Al Faisaly', 18],
    ['Ali Olwan', 'FW', 24, 'Al Faisaly', 19], ['Mousa Al-Taamari', 'FW', 27, 'Montpellier', 20],
  ],
}