import type { RosterTuple } from '../player-types'

export const GROUP_I_SQUADS: Record<string, RosterTuple[]> = {
  France: [
    ['Mike Maignan', 'GK', 29, 'AC Milan', 1], ['Brice Samba', 'GK', 30, 'Lens', 2],
    ['William Saliba', 'DF', 24, 'Arsenal', 3], ['Dayot Upamecano', 'DF', 26, 'Bayern Munich', 4],
    ['Jules Koundé', 'DF', 26, 'Barcelona', 5], ['Théo Hernandez', 'DF', 27, 'AC Milan', 6],
    ['Ibrahima Konaté', 'DF', 25, 'Liverpool', 7], ['Benjamin Pavard', 'DF', 28, 'Inter Milan', 8],
    ['Aurélien Tchouaméni', 'MF', 25, 'Real Madrid', 9], ['N\'Golo Kanté', 'MF', 33, 'Al Ittihad', 10],
    ['Adrien Rabiot', 'MF', 29, 'Marseille', 11], ['Warren Zaïre-Emery', 'MF', 19, 'PSG', 12],
    ['Antoine Griezmann', 'MF', 34, 'Atlético Madrid', 13], ['Kylian Mbappé', 'FW', 27, 'Real Madrid', 14],
    ['Ousmane Dembélé', 'FW', 27, 'PSG', 15], ['Olivier Giroud', 'FW', 38, 'AC Milan', 16],
    ['Randal Kolo Muani', 'FW', 26, 'PSG', 17], ['Marcus Thuram', 'FW', 27, 'Inter Milan', 18],
    ['Bradley Barcola', 'FW', 22, 'PSG', 19], ['Kingsley Coman', 'FW', 28, 'Bayern Munich', 20],
  ],
  Senegal: [
    ['Édouard Mendy', 'GK', 32, 'Al Ahli', 1], ['Bingourou Kamara', 'GK', 24, 'Casa Pia', 2],
    ['Kalidou Koulibaly', 'DF', 33, 'Al Hilal', 3], ['Abdou Diallo', 'DF', 28, 'Al Arabi', 4],
    ['Youssouf Sabaly', 'DF', 31, 'Al Ettifaq', 5], ['Fodé Ballo-Touré', 'DF', 28, 'Fulham', 6],
    ['Formose Mendy', 'DF', 29, 'Brest', 7], ['Pape Gueye', 'DF', 25, 'Marseille', 8],
    ['Idrissa Gueye', 'MF', 35, 'Everton', 9], ['Cheikh Kouyaté', 'MF', 34, 'Nottingham Forest', 10],
    ['Pape Matar Sarr', 'MF', 22, 'Tottenham', 11], ['Nampalys Mendy', 'MF', 32, 'Lens', 12],
    ['Sadio Mané', 'MF', 32, 'Al Nassr', 13], ['Nicolas Jackson', 'FW', 23, 'Chelsea', 14],
    ['Boulaye Dia', 'FW', 28, 'Lazio', 15], ['Ismaïla Sarr', 'FW', 26, 'Crystal Palace', 16],
    ['Sadio Mané', 'FW', 32, 'Al Nassr', 17], ['Habib Diallo', 'FW', 29, 'Al Shabab', 18],
    ['Bamba Dieng', 'FW', 24, 'Lorient', 19], ['Nicolas Jackson', 'FW', 23, 'Chelsea', 20],
  ],
  Bolivia: [
    ['Carlos Lampe', 'GK', 35, 'Always Ready', 1], ['Javier Roca', 'GK', 28, 'Blooming', 2],
    ['Luis Haquin', 'DF', 28, 'Atlético Mineiro', 3], ['José Sagredo', 'DF', 30, 'The Strongest', 4],
    ['Adrián Jusino', 'DF', 31, 'The Strongest', 5], ['Diego Bejarano', 'DF', 33, 'Always Ready', 6],
    ['Luis Haquin', 'DF', 28, 'Atlético Mineiro', 7], ['José Sagredo', 'DF', 30, 'The Strongest', 8],
    ['Erwin Saavedra', 'MF', 28, 'Bolívar', 9], ['Ramiro Vaca', 'MF', 26, 'Bolívar', 10],
    ['Moisés Villarroel', 'MF', 27, 'The Strongest', 11], ['Bruno Miranda', 'MF', 25, 'Always Ready', 12],
    ['Erwin Saavedra', 'MF', 28, 'Bolívar', 13], ['Marcelo Martins', 'FW', 37, 'Always Ready', 14],
    ['Rodrigo Tello', 'FW', 28, 'Bolívar', 15], ['Ramiro Ballivián', 'FW', 33, 'The Strongest', 16],
    ['Javier Roca', 'FW', 28, 'Blooming', 17], ['Bruno Miranda', 'FW', 25, 'Always Ready', 18],
    ['Marcelo Martins', 'FW', 37, 'Always Ready', 19], ['Rodrigo Tello', 'FW', 28, 'Bolívar', 20],
  ],
  Norway: [
    ['Bernd Leno', 'GK', 33, 'Fulham', 1], ['Ørjan Nyland', 'GK', 34, 'Brest', 2],
    ['Kristoffer Ajer', 'DF', 26, 'Brentford', 3], ['Stefan Strandberg', 'DF', 34, 'Rosenborg', 4],
    ['Felix Myhre', 'DF', 24, 'Viking', 5], ['Marcus Pedersen', 'DF', 24, 'Torino', 6],
    ['Kristoffer Ajer', 'DF', 26, 'Brentford', 7], ['Felix Myhre', 'DF', 24, 'Viking', 8],
    ['Martin Ødegaard', 'MF', 26, 'Arsenal', 9], ['Sander Berge', 'MF', 26, 'Fulham', 10],
    ['Patrick Berg', 'MF', 27, 'Lillestrøm', 11], ['Fredrik Aursnes', 'MF', 29, 'Benfica', 12],
    ['Martin Ødegaard', 'MF', 26, 'Arsenal', 13], ['Erling Haaland', 'FW', 25, 'Manchester City', 14],
    ['Alexander Sørloth', 'FW', 29, 'Villarreal', 15], ['Joshua King', 'FW', 32, 'Toulouse', 16],
    ['Erling Haaland', 'FW', 25, 'Manchester City', 17], ['Alexander Sørloth', 'FW', 29, 'Villarreal', 18],
    ['Aron Einar Malm', 'FW', 22, 'Bodø/Glimt', 19], ['Joshua King', 'FW', 32, 'Toulouse', 20],
  ],
}