import type { RosterTuple } from '../player-types'

export const GROUP_B_SQUADS: Record<string, RosterTuple[]> = {
  Canada: [
    ['Milan Borjan', 'GK', 37, 'Red Star Belgrade', 1], ['Maxime Crépeau', 'GK', 30, 'Portland Timbers', 2],
    ['Alphonso Davies', 'DF', 24, 'Bayern Munich', 3], ['Sam Adekugbe', 'DF', 29, 'Hatayspor', 4],
    ['Derek Cornelius', 'DF', 26, 'Malmö', 5], ['Alistair Johnston', 'DF', 25, 'Celtic', 6],
    ['Richie Laryea', 'DF', 29, 'Toronto FC', 7], ['Kamal Miller', 'DF', 27, 'Portland Timbers', 8],
    ['Stephen Eustáquio', 'MF', 27, 'Porto', 9], ['Samuel Piette', 'MF', 29, 'CF Montréal', 10],
    ['Ismaël Koné', 'MF', 22, 'Watford', 11], ['Liam Fraser', 'MF', 27, 'Dundee', 12],
    ['Tajon Buchanan', 'MF', 25, 'Inter Milan', 13], ['Jonathan David', 'FW', 25, 'Lille', 14],
    ['Cyle Larin', 'FW', 29, 'Mallorca', 15], ['Jacob Shaffelburg', 'FW', 24, 'Nashville SC', 16],
    ['Lucas Cavallini', 'FW', 32, 'Vancouver FC', 17], ['Junior Hoilett', 'FW', 34, 'Reading', 18],
    ['Iké Ugbo', 'FW', 26, 'Troyes', 19], ['Theo Bair', 'FW', 25, 'Vancouver FC', 20],
  ],
  Switzerland: [
    ['Yann Sommer', 'GK', 36, 'Inter Milan', 1], ['Gregor Kobel', 'GK', 27, 'Dortmund', 2],
    ['Manuel Akanji', 'DF', 29, 'Manchester City', 3], ['Nico Elvedi', 'DF', 28, 'Borussia Mönchengladbach', 4],
    ['Fabian Schär', 'DF', 32, 'Newcastle', 5], ['Ricardo Rodríguez', 'DF', 32, 'Torino', 6],
    ['Silvan Widmer', 'DF', 31, 'Mainz', 7], ['Jordan Lotomba', 'DF', 26, 'Nice', 8],
    ['Granit Xhaka', 'MF', 32, 'Leverkusen', 9], ['Denis Zakaria', 'MF', 28, 'Monaco', 10],
    ['Ruben Vargas', 'MF', 26, 'Augsburg', 11], ['Michel Aebischer', 'MF', 27, 'Bologna', 12],
    ['Xherdan Shaqiri', 'MF', 33, 'Chicago Fire', 13], ['Breel Embolo', 'FW', 28, 'Monaco', 14],
    ['Noah Okafor', 'FW', 25, 'AC Milan', 15], ['Dan Ndoye', 'FW', 24, 'Nottingham Forest', 16],
    ['Zeki Amdouni', 'FW', 24, 'Burnley', 17], ['Karlton Mills', 'FW', 22, 'Young Boys', 18],
    ['Steven Zuber', 'FW', 32, 'AEK Athens', 19], ['Antoine Bernhard', 'FW', 21, 'Basel', 20],
  ],
  Qatar: [
    ['Saad Al Sheeb', 'GK', 34, 'Al Sadd', 1], ['Meshaal Barsham', 'GK', 28, 'Al Sadd', 2],
    ['Bassam Al Rawi', 'DF', 28, 'Al Duhail', 3], ['Abdelkarim Hassan', 'DF', 31, 'Al Sadd', 4],
    ['Boualem Khoukhi', 'DF', 34, 'Al Arabi', 5], ['Tarek Salman', 'DF', 27, 'Al Sadd', 6],
    ['Ro-Ro', 'DF', 30, 'Al Sadd', 7], ['Pedro Miguel', 'DF', 33, 'Al Sadd', 8],
    ['Hassan Al Haydos', 'MF', 34, 'Al Sadd', 9], ['Akram Afif', 'MF', 28, 'Al Sadd', 10],
    ['Homam Al Amin', 'MF', 26, 'Al Duhail', 11], ['Karim Boudiaf', 'MF', 33, 'Al Duhail', 12],
    ['Mohammed Muntari', 'MF', 31, 'Al Duhail', 13], ['Almoez Ali', 'FW', 29, 'Al Duhail', 14],
    ['Akram Hassan', 'FW', 27, 'Al Rayyan', 15], ['Yusuf Abdurisag', 'FW', 24, 'Al Sadd', 16],
    ['Mohammed Waad', 'FW', 25, 'Al Sadd', 17], ['Ghanim Hassan', 'FW', 23, 'Al Arabi', 18],
    ['Tameem Al Abed', 'FW', 22, 'Al Wakrah', 19], ['Mubarak Shannan', 'FW', 26, 'Al Gharafa', 20],
  ],
  Italy: [
    ['Gianluigi Donnarumma', 'GK', 27, 'PSG', 1], ['Alex Meret', 'GK', 28, 'Napoli', 2],
    ['Alessandro Bastoni', 'DF', 26, 'Inter Milan', 3], ['Francesco Acerbi', 'DF', 36, 'Inter Milan', 4],
    ['Giovanni Di Lorenzo', 'DF', 31, 'Napoli', 5], ['Federico Dimarco', 'DF', 27, 'Inter Milan', 6],
    ['Matteo Darmian', 'DF', 35, 'Inter Milan', 7], ['Riccardo Calafiori', 'DF', 22, 'Arsenal', 8],
    ['Nicolò Barella', 'MF', 28, 'Inter Milan', 9], ['Marco Verratti', 'MF', 32, 'Al Arabi', 10],
    ['Jorginho', 'MF', 33, 'Arsenal', 11], ['Sandro Tonali', 'MF', 25, 'Newcastle', 12],
    ['Davide Frattesi', 'MF', 25, 'Inter Milan', 13], ['Federico Chiesa', 'FW', 27, 'Liverpool', 14],
    ['Giacomo Raspadori', 'FW', 25, 'Napoli', 15], ['Matteo Politano', 'FW', 31, 'Napoli', 16],
    ['Lorenzo Lucca', 'FW', 24, 'Udinese', 17], ['Moise Kean', 'FW', 25, 'Fiorentina', 18],
    ['Gianluca Scamacca', 'FW', 26, 'Atalanta', 19], ['Wilfried Gnonto', 'FW', 21, 'Leeds United', 20],
  ],
}