import type { RosterTuple } from '../player-types'

export const GROUP_B_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "Canada": [
    ["Dayne St. Clair", "GK", 29, "Inter Miami", 1],
    ["Alistair Johnston", "DF", 27, "Celtic", 2],
    ["Alfie Jones", "DF", 28, "Middlesbrough", 3],
    ["Luc De Fougerolles", "DF", 20, "Fulham", 4],
    ["Joel Waterman", "DF", 30, "Chicago Fire", 5],
    ["Mathieu Choinière", "MF", 27, "Los Angeles FC", 6],
    ["Stephen Eustáquio", "MF", 29, "Porto", 7],
    ["Ismaël Koné", "MF", 23, "Sassuolo", 8],
    ["Cyle Larin", "FW", 31, "Mallorca", 9],
    ["Jonathan David", "FW", 26, "Juventus", 10],
    ["Liam Millar", "FW", 26, "Hull City", 11],
    ["Tani Oluwaseyi", "FW", 26, "Villarreal", 12],
    ["Derek Cornelius", "DF", 28, "Marseille", 13],
    ["Jacob Shaffelburg", "MF", 26, "Los Angeles FC", 14],
    ["Moïse Bombito", "DF", 26, "Nice", 15],
    ["Maxime Crépeau", "GK", 32, "Orlando City", 16],
    ["Tajon Buchanan", "FW", 27, "Villarreal", 17],
    ["Owen Goodman", "GK", 22, "Crystal Palace", 18],
    ["Alphonso Davies", "DF", 25, "Bayern Munich", 19],
    ["Ali Ahmed", "FW", 25, "Norwich City", 20],
    ["Jonathan Osorio", "MF", 33, "Toronto FC", 21],
    ["Richie Laryea", "DF", 31, "Toronto FC", 22],
    ["Niko Sigur", "DF", 22, "Hajduk Split", 23],
    ["Promise David", "FW", 24, "Union Saint-Gilloise", 24],
    ["Nathan-Dylan Saliba", "MF", 22, "Anderlecht", 25],
    ["Jayden Nelson", "FW", 23, "Austin FC", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Bosnia and Herzegovina": [
    ["Nikola Vasilj", "GK", 30, "St Pauli", 1],
    ["Nihad Mujakic", "DF", 28, "Gaziantep", 2],
    ["Dennis Hadzikadunic", "DF", 27, "Sampdoria", 3],
    ["Tarik Muharemovic", "DF", 23, "Sassuolo", 4],
    ["Sead Kolasinac", "DF", 32, "Atalanta", 5],
    ["Benjamin Tahirovic", "MF", 23, "Brøndby", 6],
    ["Amar Dedic", "DF", 23, "Benfica", 7],
    ["Armin Gigovic", "MF", 24, "Young Boys", 8],
    ["Samed Bazdar", "FW", 22, "Real Zaragoza", 9],
    ["Ermedin Demirovic", "FW", 28, "Stuttgart", 10],
    ["Edin Dzeko", "FW", 40, "Schalke", 11],
    ["Mladen Jurkas", "GK", 18, "Borac Banja Luka", 12],
    ["Ivan Basic", "MF", 24, "Astana", 13],
    ["Ivan Sunjic", "MF", 29, "Pafos", 14],
    ["Amar Memic", "FW", 25, "Viktoria Plzen", 15],
    ["Amir Hadziahmetovic", "MF", 29, "Hull City", 16],
    ["Dzenis Burnic", "MF", 28, "Karlsruhe", 17],
    ["Nikola Katic", "DF", 29, "Schalke", 18],
    ["Kerim Alajbegovic", "FW", 18, "Bayer Leverkusen", 19],
    ["Esmir Bajraktarevic", "FW", 21, "PSV Eindhoven", 20],
    ["Stjepan Radeljic", "DF", 28, "HNK Rijeka", 21],
    ["Martin Zlomislic", "GK", 27, "HNK Rijeka", 22],
    ["Haris Tabakovic", "FW", 31, "Borussia Mönchengladbach", 23],
    ["Nidal Celik", "DF", 19, "Lens", 24],
    ["Jovo Lukic", "FW", 27, "Universitatea Cluj", 25],
    ["Ermin Mahmic", "MF", 21, "Slovan Liberec", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Qatar": [
    ["Mahmoud Abunada", "GK", 26, "Al-Rayyan", 1],
    ["Pedro Miguel", "DF", 35, "Al-Sadd", 2],
    ["Lucas Mendes", "DF", 35, "Al-Wakrah", 3],
    ["Issa Laye", "DF", 28, "Al-Arabi", 4],
    ["Jassem Gaber", "MF", 24, "Al-Rayyan", 5],
    ["Abdulaziz Hatem", "MF", 35, "Al-Rayyan", 6],
    ["Ahmed Alaaeldin", "FW", 33, "Al-Rayyan", 7],
    ["Edmilson Junior", "FW", 31, "Al-Duhail", 8],
    ["Mohammed Muntari", "FW", 32, "Al-Gharafa", 9],
    ["Hassan Al-Haydos", "FW", 35, "Al-Sadd", 10],
    ["Akram Afif", "FW", 29, "Al-Sadd", 11],
    ["Karim Boudiaf", "MF", 35, "Al-Duhail", 12],
    ["Ayoub Alawi", "DF", 21, "Al-Gharafa", 13],
    ["Homam Ahmed", "DF", 26, "Cultural Leonesa", 14],
    ["Yusuf Abdurisag", "FW", 26, "Al-Wakrah", 15],
    ["Boualem Khoukhi", "DF", 35, "Al-Sadd", 16],
    ["Ahmed Al-Ganehi", "FW", 25, "Al-Gharafa", 17],
    ["Sultan Al-Brake", "DF", 30, "Al-Duhail", 18],
    ["Almoez Ali", "FW", 29, "Al-Duhail", 19],
    ["Ahmed Fathy", "MF", 33, "Al-Arabi", 20],
    ["Salah Zakaria", "GK", 27, "Al-Duhail", 21],
    ["Meshaal Barsham", "GK", 28, "Al-Sadd", 22],
    ["Assim Madibo", "MF", 29, "Al-Wakrah", 23],
    ["Tahsin Mohammed Jamshid", "FW", 19, "Al-Duhail SC", 24],
    ["Hashmi Hussein", "DF", 22, "Al-Arabi", 25],
    ["Mohamed Al-Mannai", "MF", 22, "Al-Shamal", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Switzerland": [
    ["Gregor Kobel", "GK", 28, "Borussia Dortmund", 1],
    ["Miro Muheim", "DF", 28, "Hamburg", 2],
    ["Silvan Widmer", "DF", 33, "Mainz", 3],
    ["Nico Elvedi", "DF", 29, "Borussia Mönchengladbach", 4],
    ["Manuel Akanji", "DF", 30, "Inter", 5],
    ["Denis Zakaria", "MF", 29, "Monaco", 6],
    ["Breel Embolo", "FW", 29, "Rennes", 7],
    ["Remo Freuler", "MF", 34, "Bologna", 8],
    ["Johan Manzambi", "FW", 20, "Freiburg", 9],
    ["Granit Xhaka", "MF", 33, "Sunderland", 10],
    ["Dan Ndoye", "FW", 25, "Nottingham Forest", 11],
    ["Yvon Mvogo", "GK", 32, "Lorient", 12],
    ["Ricardo Rodriguez", "DF", 33, "Real Betis", 13],
    ["Ardon Jashari", "MF", 23, "Milan", 14],
    ["Djibril Sow", "MF", 29, "Sevilla", 15],
    ["Christian Fassnacht", "MF", 32, "Young Boys", 16],
    ["Ruben Vargas", "FW", 27, "Sevilla", 17],
    ["Eray Cömert", "DF", 28, "Valencia", 18],
    ["Noah Okafor", "FW", 26, "Leeds", 19],
    ["Michel Aebischer", "MF", 29, "Pisa", 20],
    ["Marvin Keller", "GK", 23, "Young Boys", 21],
    ["Fabian Rieder", "MF", 24, "Augsburg", 22],
    ["Zeki Amdouni", "FW", 25, "Burnley", 23],
    ["Aurèle Amenda", "DF", 22, "Eintracht Frankfurt", 24],
    ["Luca Jaquez", "DF", 23, "Stuttgart", 25],
    ["Cedric Itten", "FW", 29, "Fortuna Düsseldorf", 26],
  ],
}
