import type { RosterTuple } from '../player-types'

export const GROUP_C_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "Brazil": [
    ["Alisson", "GK", 33, "Liverpool", 1],
    ["Éderson", "MF", 26, "Atalanta", 2],
    ["Gabriel Magalhães", "DF", 28, "Arsenal", 3],
    ["Marquinhos", "DF", 32, "Paris St-Germain", 4],
    ["Casemiro", "MF", 34, "Manchester United", 5],
    ["Alex Sandro", "DF", 35, "Flamengo", 6],
    ["Vinícius Júnior", "FW", 25, "Real Madrid", 7],
    ["Bruno Guimarães", "MF", 28, "Newcastle", 8],
    ["Matheus Cunha", "FW", 27, "Manchester United", 9],
    ["Neymar", "FW", 34, "Santos", 10],
    ["Raphinha", "FW", 29, "Barcelona", 11],
    ["Weverton", "GK", 38, "Grêmio", 12],
    ["Danilo", "DF", 34, "Flamengo", 13],
    ["Bremer", "DF", 29, "Juventus", 14],
    ["Léo Pereira", "DF", 30, "Flamengo", 15],
    ["Douglas Santos", "DF", 32, "Zenit St Petersburg", 16],
    ["Fabinho", "MF", 32, "Al-Ittihad", 17],
    ["Danilo Santos", "MF", 25, "Botafogo", 18],
    ["Endrick", "FW", 19, "Real Madrid", 19],
    ["Lucas Paquetá", "MF", 28, "Flamengo", 20],
    ["Luiz Henrique", "FW", 25, "Zenit St Petersburg", 21],
    ["Gabriel Martinelli", "FW", 24, "Arsenal", 22],
    ["Ederson", "GK", 32, "Fenerbahce", 23],
    ["Roger Ibañez", "DF", 27, "Al-Ahli", 24],
    ["Igor Thiago", "FW", 24, "Brentford", 25],
    ["Rayan", "FW", 19, "Bournemouth", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Morocco": [
    ["Yassine Bounou", "GK", 35, "Al-Hilal", 1],
    ["Achraf Hakimi", "DF", 27, "Paris St-Germain", 2],
    ["Noussair Mazraoui", "DF", 28, "Manchester United", 3],
    ["Sofyan Amrabat", "MF", 29, "Real Betis", 4],
    ["Marwane Saâdane", "DF", 34, "Al-Fateh", 5],
    ["Ayyoub Bouaddi", "MF", 18, "Lille", 6],
    ["Chemsdine Talbi", "FW", 21, "Sunderland", 7],
    ["Azzedine Ounahi", "MF", 26, "Girona", 8],
    ["Soufiane Rahimi", "FW", 30, "Al Ain", 9],
    ["Brahim Díaz", "FW", 26, "Real Madrid", 10],
    ["Ismael Saibari", "MF", 25, "PSV Eindhoven", 11],
    ["Munir El Kajoui", "GK", 37, "RS Berkane", 12],
    ["Zakaria El Ouahdi", "DF", 24, "Genk", 13],
    ["Issa Diop", "DF", 29, "Fulham", 14],
    ["Samir El Mourabet", "MF", 20, "Strasbourg", 15],
    ["Gessime Yassine", "MF", 20, "Strasbourg", 16],
    ["Amine Sbaï", "FW", 25, "Angers", 17],
    ["Chadi Riad", "DF", 22, "Crystal Palace", 18],
    ["Youssef Belammari", "DF", 27, "Al Ahly", 19],
    ["Ayoub El Kaabi", "FW", 32, "Olympiakos", 20],
    ["Ayoube Amaimouni", "FW", 21, "Eintracht Frankfurt", 21],
    ["Ahmed Reda Tagnaouti", "GK", 30, "AS FAR Rabat", 22],
    ["Bilal El Khannouss", "MF", 22, "Stuttgart", 23],
    ["Neil El Aynaoui", "MF", 24, "Roma", 24],
    ["Redouane Halhal", "DF", 23, "Mechelen", 25],
    ["Anass Salah-Eddine", "DF", 24, "Roma", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Haiti": [
    ["Johny Placide", "GK", 38, "Bastia", 1],
    ["Carlens Arcus", "DF", 29, "Angers", 2],
    ["Keeto Thermoncy", "DF", 20, "Young Boys", 3],
    ["Ricardo Adé", "DF", 36, "LDU Quito", 4],
    ["Hannes Delcroix", "DF", 27, "Lugano", 5],
    ["Carl Fred Sainté", "MF", 23, "El Paso Locomotive", 6],
    ["Derrick Etienne Jr", "FW", 29, "Toronto FC", 7],
    ["Martin Expérience", "DF", 27, "AS Nancy", 8],
    ["Duckens Nazon", "FW", 32, "Esteghlal", 9],
    ["Jean-Ricner Bellegarde", "MF", 27, "Wolves", 10],
    ["Louicius Deedson", "FW", 25, "FC Dallas", 11],
    ["Alexandre Pierre", "GK", 25, "Sochaux", 12],
    ["Duke Lacroix", "DF", 32, "Colorado Springs Switchbacks", 13],
    ["Leverton Pierre", "MF", 28, "Vizela", 14],
    ["Ruben Providence", "FW", 24, "Almere City FC", 15],
    ["Lenny Joseph", "FW", 25, "Ferencvaros", 16],
    ["Danley Jean Jacques", "MF", 26, "Philadelphia Union", 17],
    ["Wilson Isidor", "FW", 25, "Sunderland", 18],
    ["Yassin Fortuné", "FW", 27, "Vizela", 19],
    ["Frantzdy Pierrot", "FW", 31, "AEK Athens", 20],
    ["Josué Casimir", "FW", 24, "Auxerre", 21],
    ["Jean-Kévin Duverne", "DF", 28, "Nantes", 22],
    ["Josué Duverger", "GK", 26, "Cosmos Koblenz", 23],
    ["Wilguens Paugain", "DF", 24, "Zulte Waregem", 24],
    ["Dominique Simon", "MF", 25, "Tatran Presov", 25],
    ["Woodensky Pierre", "MF", 21, "Violette AC", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Scotland": [
    ["Angus Gunn", "GK", 30, "Nottingham Forest", 1],
    ["Aaron Hickey", "DF", 24, "Brentford", 2],
    ["Andy Robertson", "DF", 32, "Liverpool", 3],
    ["Scott McTominay", "MF", 29, "Napoli", 4],
    ["Grant Hanley", "DF", 34, "Hibernian", 5],
    ["Kieran Tierney", "DF", 29, "Celtic", 6],
    ["John McGinn", "MF", 31, "Aston Villa", 7],
    ["Tyler Fletcher", "MF", 19, "Manchester United", 8],
    ["Lyndon Dykes", "FW", 30, "Charlton", 9],
    ["Che Adams", "FW", 29, "Torino", 10],
    ["Ryan Christie", "MF", 31, "Bournemouth", 11],
    ["Liam Kelly", "GK", 30, "Rangers", 12],
    ["Jack Hendry", "DF", 31, "At-Ettifaq", 13],
    ["Ross Stewart", "FW", 29, "Southampton", 14],
    ["John Souttar", "DF", 29, "Rangers", 15],
    ["Dominic Hyam", "DF", 30, "Wrexham", 16],
    ["Ben Gannon-Doak", "FW", 20, "Bournemouth", 17],
    ["George Hirst", "FW", 27, "Ipswich", 18],
    ["Lewis Ferguson", "MF", 26, "Bologna", 19],
    ["Lawrence Shankland", "FW", 30, "Rangers", 20],
    ["Craig Gordon", "GK", 43, "Hearts", 21],
    ["Nathan Patterson", "DF", 24, "Everton", 22],
    ["Kenny McLean", "MF", 34, "Norwich City", 23],
    ["Anthony Ralston", "DF", 27, "Celtic", 24],
    ["Findlay Curtis", "FW", 19, "Rangers", 25],
    ["Scott McKenna", "DF", 29, "Dinamo Zagreb", 26],
  ],
}
