import type { RosterTuple } from '../player-types'

export const GROUP_D_SQUADS: Record<string, RosterTuple[]> = {
  'United States': [
    ['Matt Turner', 'GK', 30, 'Nottingham Forest', 1], ['Ethan Horvath', 'GK', 29, 'Cardiff City', 2],
    ['Antonee Robinson', 'DF', 27, 'Fulham', 3], ['Chris Richards', 'DF', 24, 'Crystal Palace', 4],
    ['Tim Ream', 'DF', 37, 'Fulham', 5], ['Walker Zimmerman', 'DF', 31, 'Dallas', 6],
    ['Sergiño Dest', 'DF', 24, 'PSV', 7], ['Erik Palmer-Brown', 'DF', 27, 'Troyes', 8],
    ['Tyler Adams', 'MF', 25, 'Bournemouth', 9], ['Weston McKennie', 'MF', 26, 'Juventus', 10],
    ['Yunus Musah', 'MF', 22, 'AC Milan', 11], ['Gio Reyna', 'MF', 22, 'Borussia Dortmund', 12],
    ['Johnny Cardoso', 'MF', 23, 'Real Betis', 13], ['Christian Pulisic', 'FW', 26, 'AC Milan', 14],
    ['Brenden Aaronson', 'FW', 24, 'Leeds United', 15], ['Folarin Balogun', 'FW', 23, 'Monaco', 16],
    ['Ricardo Pepi', 'FW', 22, 'PSV', 17], ['Haji Wright', 'FW', 26, 'Coventry City', 18],
    ['Jordan Morris', 'FW', 30, 'Seattle Sounders', 19], ['Timothy Tillman', 'FW', 25, 'LAFC', 20],
  ],
  Paraguay: [
    ['Anthony Silva', 'GK', 37, 'Olimpia', 1], ['Juan Espínola', 'GK', 29, 'Cerro Porteño', 2],
    ['Omar Alderete', 'DF', 28, 'Getafe', 3], ['Gustavo Gómez', 'DF', 31, 'Palmeiras', 4],
    ['Júnior Alonso', 'DF', 32, 'Krasnodar', 5], ['Blas Riveros', 'DF', 26, 'Braga', 6],
    ['Robert Rojas', 'DF', 28, 'River Plate', 7], ['Iván Torres', 'DF', 27, 'Olimpia', 8],
    ['Miguel Almirón', 'MF', 30, 'Newcastle', 9], ['Mathías Rojas', 'MF', 28, 'Racing Club', 10],
    ['Diego Gómez', 'MF', 21, 'Brighton', 11], ['Andrés Cubas', 'MF', 28, 'Vancouver Whitecaps', 12],
    ['Richard Sánchez', 'MF', 28, 'América', 13], ['Antonio Sanabria', 'FW', 28, 'Torino', 14],
    ['Adam Bareiro', 'FW', 28, 'San Lorenzo', 15], ['Óscar Romero', 'FW', 32, 'Boca Juniors', 16],
    ['Gabriel Ávalos', 'FW', 33, 'Internacional', 17], ['Julio Enciso', 'FW', 21, 'Brighton', 18],
    ['Hernán Pérez', 'FW', 35, 'Olimpia', 19], ['Carlos González', 'FW', 27, 'Cerro Porteño', 20],
  ],
  Australia: [
    ['Mathew Ryan', 'GK', 33, 'Roma', 1], ['Lawrence Thomas', 'GK', 32, 'Melbourne Victory', 2],
    ['Harry Souttar', 'DF', 26, 'Leicester City', 3], ['Kye Rowles', 'DF', 26, 'Hearts', 4],
    ['Bailey Wright', 'DF', 32, 'Coventry City', 5], ['Aziz Behich', 'DF', 34, 'Dundee United', 6],
    ['Fran Karačić', 'DF', 28, 'Bayer Leverkusen', 7], ['Rhyan Grant', 'DF', 31, 'Sydney FC', 8],
    ['Jackson Irvine', 'MF', 31, 'St. Pauli', 9], ['Riley McGree', 'MF', 25, 'Middlesbrough', 10],
    ['Aiden O\'Neill', 'MF', 26, 'Standard Liège', 11], ['Connor Metcalfe', 'MF', 25, 'St. Pauli', 12],
    ['Craig Goodwin', 'MF', 32, 'Adelaide United', 13], ['Mitchell Duke', 'FW', 33, 'Machida Zelvia', 14],
    ['Mathew Leckie', 'FW', 33, 'Melbourne City', 15], ['Martin Boyle', 'FW', 33, 'Hibernian', 16],
    ['Garang Kuol', 'FW', 20, 'Hartberg', 17], ['Brandon Borrello', 'FW', 29, 'Western Sydney', 18],
    ['Nestory Irankunda', 'FW', 18, 'Watford', 19], ['Adam Taggart', 'FW', 31, 'Gold Coast United', 20],
  ],
  Turkey: [
    ['Uğurcan Çakır', 'GK', 28, 'Trabzonspor', 1], ['Altay Bayındır', 'GK', 26, 'Manchester United', 2],
    ['Çağlar Söyüncü', 'DF', 28, 'Fenerbahçe', 3], ['Merih Demiral', 'DF', 26, 'Al-Ahli', 4],
    ['Zeki Çelik', 'DF', 27, 'Roma', 5], ['Ferdi Kadıoğlu', 'DF', 24, 'Brighton', 6],
    ['Mert Müldür', 'DF', 25, 'Fenerbahçe', 7], ['Abdülkerim Bardakcı', 'DF', 30, 'Galatasaray', 8],
    ['Hakan Çalhanoğlu', 'MF', 30, 'Inter Milan', 9], ['Orkun Kökçü', 'MF', 23, 'Benfica', 10],
    ['İrfan Can Kahveci', 'MF', 29, 'Fenerbahçe', 11], ['Salih Özcan', 'MF', 26, 'Dortmund', 12],
    ['Arda Güler', 'MF', 20, 'Real Madrid', 13], ['Cengiz Ünder', 'FW', 27, 'Fenerbahçe', 14],
    ['Kerem Aktürkoğlu', 'FW', 25, 'Galatasaray', 15], ['Barış Alper Yılmaz', 'FW', 24, 'Galatasaray', 16],
    ['Enes Ünal', 'FW', 27, 'Bournemouth', 17], ['Kenan Yıldız', 'FW', 19, 'Juventus', 18],
    ['Cenk Tosun', 'FW', 33, 'Beşiktaş', 19], ['Burak Yılmaz', 'FW', 39, 'Kayserispor', 20],
  ],
}