import type { RosterTuple } from '../player-types'

export const GROUP_L_SQUADS: Record<string, RosterTuple[]> = {
  England: [
    ['Jordan Pickford', 'GK', 30, 'Everton', 1], ['Nick Pope', 'GK', 32, 'Newcastle', 2],
    ['John Stones', 'DF', 30, 'Manchester City', 3], ['Harry Maguire', 'DF', 31, 'Manchester United', 4],
    ['Kyle Walker', 'DF', 34, 'Manchester City', 5], ['Luke Shaw', 'DF', 29, 'Manchester United', 6],
    ['Ezri Konsa', 'DF', 27, 'Aston Villa', 7], ['Marc Guéhi', 'DF', 24, 'Crystal Palace', 8],
    ['Declan Rice', 'MF', 26, 'Arsenal', 9], ['Jude Bellingham', 'MF', 22, 'Real Madrid', 10],
    ['Phil Foden', 'MF', 25, 'Manchester City', 11], ['Conor Gallagher', 'MF', 24, 'Chelsea', 12],
    ['Kobbie Mainoo', 'MF', 19, 'Manchester United', 13], ['Harry Kane', 'FW', 32, 'Bayern Munich', 14],
    ['Bukayo Saka', 'FW', 24, 'Arsenal', 15], ['Ollie Watkins', 'FW', 29, 'Aston Villa', 16],
    ['Ivan Toney', 'FW', 28, 'Al Ahli', 17], ['Anthony Gordon', 'FW', 24, 'Newcastle', 18],
    ['Jarrod Bowen', 'FW', 28, 'West Ham', 19], ['Eberechi Eze', 'FW', 26, 'Crystal Palace', 20],
  ],
  Ghana: [
    ['Lawrence Ati-Zigi', 'GK', 28, 'St. Gallen', 1], ['Ibrahim Danlad', 'GK', 24, 'Asante Kotoko', 2],
    ['Daniel Amartey', 'DF', 29, 'Leicester City', 3], ['Alexander Djiku', 'DF', 30, 'Strasbourg', 4],
    ['Gideon Mensah', 'DF', 26, 'Auxerre', 5], ['Mohammed Salisu', 'DF', 25, 'Monaco', 6],
    ['Daniel Amartey', 'DF', 29, 'Leicester City', 7], ['Gideon Mensah', 'DF', 26, 'Auxerre', 8],
    ['Thomas Partey', 'MF', 31, 'Arsenal', 9], ['Mohammed Kudus', 'MF', 24, 'West Ham', 10],
    ['André Ayew', 'MF', 35, 'Le Havre', 11], ['Jordan Ayew', 'MF', 33, 'Crystal Palace', 12],
    ['Mohammed Kudus', 'MF', 24, 'West Ham', 13], ['Mohammed Kudus', 'FW', 24, 'West Ham', 14],
    ['Inaki Williams', 'FW', 30, 'Athletic Bilbao', 15], ['Jordan Ayew', 'FW', 33, 'Crystal Palace', 16],
    ['André Ayew', 'FW', 35, 'Le Havre', 17], ['Antoine Semenyo', 'FW', 25, 'Bournemouth', 18],
    ['Inaki Williams', 'FW', 30, 'Athletic Bilbao', 19], ['Jordan Ayew', 'FW', 33, 'Crystal Palace', 20],
  ],
  Panama: [
    ['Luis Mejía', 'GK', 33, 'Nacional', 1], ['Orlando Mosquera', 'GK', 24, 'Universitario', 2],
    ['Fidel Escobar', 'DF', 31, 'Saprissa', 3], ['Harold Cummings', 'DF', 32, 'Saprissa', 4],
    ['Michael Murillo', 'DF', 28, 'Marseille', 5], ['Roberto Chen', 'DF', 32, 'Plaza Amador', 6],
    ['Fidel Escobar', 'DF', 31, 'Saprissa', 7], ['Michael Murillo', 'DF', 28, 'Marseille', 8],
    ['Aníbal Godoy', 'MF', 34, 'Nashville SC', 9], ['Alberto Quintero', 'MF', 37, 'Universitario', 10],
    ['Génesis Díaz', 'MF', 26, 'Saprissa', 11], ['José Fajardo', 'MF', 28, 'Saprissa', 12],
    ['Aníbal Godoy', 'MF', 34, 'Nashville SC', 13], ['Ismael Díaz', 'FW', 28, 'Mazatlán', 14],
    ['José Fajardo', 'FW', 28, 'Saprissa', 15], ['Alberto Quintero', 'FW', 37, 'Universitario', 16],
    ['Ismael Díaz', 'FW', 28, 'Mazatlán', 17], ['Génesis Díaz', 'FW', 26, 'Saprissa', 18],
    ['José Fajardo', 'FW', 28, 'Saprissa', 19], ['Ismael Díaz', 'FW', 28, 'Mazatlán', 20],
  ],
  Croatia: [
    ['Dominik Livaković', 'GK', 29, 'Fenerbahçe', 1], ['Ivo Grbić', 'GK', 25, 'Atlético Madrid', 2],
    ['Joško Gvardiol', 'DF', 23, 'Manchester City', 3], ['Dejan Lovren', 'DF', 35, 'Fenerbahçe', 4],
    ['Borna Sosa', 'DF', 26, 'Ajax', 5], ['Josip Juranović', 'DF', 29, 'Union Berlin', 6],
    ['Joško Gvardiol', 'DF', 23, 'Manchester City', 7], ['Borna Sosa', 'DF', 26, 'Ajax', 8],
    ['Luka Modrić', 'MF', 39, 'Real Madrid', 9], ['Mateo Kovačić', 'MF', 30, 'Manchester City', 10],
    ['Marcelo Brozović', 'MF', 32, 'Al Nassr', 11], ['Mario Pašalić', 'MF', 29, 'Atalanta', 12],
    ['Luka Modrić', 'MF', 39, 'Real Madrid', 13], ['Bruno Petković', 'FW', 31, 'Dinamo Zagreb', 14],
    ['Andrej Kramarić', 'FW', 33, 'Hoffenheim', 15], ['Marko Livaja', 'FW', 31, 'Hajduk Split', 16],
    ['Bruno Petković', 'FW', 31, 'Dinamo Zagreb', 17], ['Andrej Kramarić', 'FW', 33, 'Hoffenheim', 18],
    ['Marko Livaja', 'FW', 31, 'Hajduk Split', 19], ['Mario Pašalić', 'FW', 29, 'Atalanta', 20],
  ],
}