import type { RosterTuple } from '../player-types'

export const GROUP_D_SQUADS: Record<string, RosterTuple[]> = {
  /** Official 26 — FOX Sports, Jun 10 2026 (Guardian override skipped) */
  "United States": [
    ["Matt Turner", "GK", 31, "New England Revolution", 1],
    ["Sergiño Dest", "DF", 25, "PSV", 2],
    ["Chris Richards", "DF", 26, "Crystal Palace", 3],
    ["Tyler Adams", "MF", 27, "Bournemouth", 4],
    ["Antonee Robinson", "DF", 28, "Fulham", 5],
    ["Auston Trusty", "DF", 27, "Celtic", 6],
    ["Gio Reyna", "MF", 23, "Gladbach", 7],
    ["Weston McKennie", "MF", 27, "Juventus", 8],
    ["Ricardo Pepi", "FW", 23, "PSV", 9],
    ["Christian Pulisic", "FW", 27, "AC Milan", 10],
    ["Brenden Aaronson", "FW", 25, "Leeds", 11],
    ["Miles Robinson", "DF", 29, "FC Cincinnati", 12],
    ["Tim Ream", "DF", 38, "Charlotte FC", 13],
    ["Sebastian Berhalter", "MF", 25, "Vancouver Whitecaps", 14],
    ["Cristian Roldan", "MF", 31, "Seattle Sounders", 15],
    ["Alex Freeman", "DF", 21, "Villarreal", 16],
    ["Malik Tillman", "MF", 24, "Bayer Leverkusen", 17],
    ["Max Arfsten", "DF", 25, "Columbus Crew", 18],
    ["Haji Wright", "FW", 28, "Coventry City", 19],
    ["Folarin Balogun", "FW", 24, "Monaco", 20],
    ["Tim Weah", "FW", 26, "Marseille", 21],
    ["Mark McKenzie", "DF", 27, "Toulouse", 22],
    ["Joe Scally", "DF", 23, "Gladbach", 23],
    ["Matt Freese", "GK", 27, "NYCFC", 24],
    ["Chris Brady", "GK", 22, "Chicago Fire", 25],
    ["Alex Zendejas", "FW", 28, "Club América", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Paraguay": [
    ["Roberto Junior Fernández", "GK", 38, "Cerro Porteño", 1],
    ["Gustavo Velázquez", "DF", 35, "Cerro Porteño", 2],
    ["Omar Alderete", "DF", 29, "Sunderland", 3],
    ["Juan José Cáceres", "DF", 26, "Dynamo Moscow", 4],
    ["Fabián Balbuena", "DF", 34, "Grêmio", 5],
    ["Junior Alonso", "DF", 33, "Atlético Mineiro", 6],
    ["Ramón Sosa", "FW", 26, "Palmeiras", 7],
    ["Diego Gómez", "MF", 23, "Brighton", 8],
    ["Antonio Sanabria", "FW", 30, "Cremonese", 9],
    ["Miguel Almirón", "FW", 32, "Atlanta United", 10],
    ["Maurício", "MF", 24, "Palmeiras", 11],
    ["Orlando Gill", "GK", 26, "San Lorenzo de Almagro", 12],
    ["José Canale", "DF", 29, "Lanus", 13],
    ["Andrés Cubas", "MF", 30, "Vancouver Whitecaps", 14],
    ["Gustavo Gómez", "DF", 33, "Palmeiras", 15],
    ["Damián Bobadilla", "MF", 24, "São Paulo", 16],
    ["Alejandro ‘Kaku’ Romero", "MF", 31, "Al-Ain", 17],
    ["Álex Arce", "FW", 30, "Independiente de Rivadavia", 18],
    ["Julio Enciso", "FW", 22, "Racing Strasbourg", 19],
    ["Braian Ojeda", "MF", 25, "Orlando City", 20],
    ["Gabriel Ávalos", "FW", 35, "Independiente de Avellaneda", 21],
    ["Gastón Oliveira", "GK", 33, "Olimpia", 22],
    ["Matías Galarza", "MF", 24, "Atlanta United", 23],
    ["Gustavo Caballero", "FW", 24, "Portsmouth", 24],
    ["Isidro Pitta", "FW", 26, "Red Bull Bragantino", 25],
    ["Alexandro Maidana", "DF", 20, "Talleres", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Australia": [
    ["Mathew Ryan", "GK", 34, "Levante", 1],
    ["Milos Degenek", "DF", 32, "Apoel", 2],
    ["Alessandro Circati", "DF", 22, "Parma", 3],
    ["Jacob Italiano", "DF", 24, "Grazer AK", 4],
    ["Jordan Bos", "DF", 23, "Feyenoord", 5],
    ["Jason Geria", "DF", 33, "Albirex Niigata", 6],
    ["Mathew Leckie", "MF", 35, "Melbourne City", 7],
    ["Connor Metcalfe", "MF", 26, "St Pauli", 8],
    ["Mohamed Touré", "FW", 22, "Norwich", 9],
    ["Ajdin Hrustic", "MF", 29, "Heracles Almelo", 10],
    ["Awer Mabil", "FW", 30, "Castellón", 11],
    ["Paul Izzo", "GK", 31, "Randers", 12],
    ["Aiden O’Neill", "MF", 27, "New York City", 13],
    ["Cameron Devlin", "MF", 28, "Hearts", 14],
    ["Kai Trewin", "DF", 25, "New York City", 15],
    ["Aziz Behich", "DF", 35, "Melbourne City", 16],
    ["Nestory Irankunda", "FW", 20, "Watford", 17],
    ["Patrick Beach", "GK", 22, "Melbourne City", 18],
    ["Harry Souttar", "DF", 27, "Leicester", 19],
    ["Cristian Volpato", "MF", 22, "Sassuolo", 20],
    ["Cameron Burgess", "DF", 30, "Swansea", 21],
    ["Jackson Irvine", "MF", 33, "St Pauli", 22],
    ["Nishan Velupillay", "FW", 25, "Melbourne Victory", 23],
    ["Paul Okon-Engstler", "MF", 21, "Sydney FC", 24],
    ["Lucas Herrington", "DF", 18, "Colorado Rapids", 25],
    ["Tete Yengi", "FW", 25, "Machida Zelvia", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Turkey": [
    ["Mert Gunok", "GK", 37, "Fenerbahce", 1],
    ["Zeki Celik", "DF", 29, "Roma", 2],
    ["Merih Demiral", "DF", 28, "Al-Ahli", 3],
    ["Caglar Soyuncu", "DF", 30, "Fenerbahce", 4],
    ["Salih Özcan", "MF", 28, "Borussia Dortmund", 5],
    ["Orkun Kokcu", "MF", 25, "Besiktas", 6],
    ["Kerem Akturkoglu", "FW", 27, "Fenerbahce", 7],
    ["Arda Guler", "MF", 21, "Real Madrid", 8],
    ["Deniz Gul", "FW", 21, "Porto", 9],
    ["Hakan Calhanoglu", "MF", 32, "Inter", 10],
    ["Kenan Yildiz", "FW", 21, "Juventus", 11],
    ["Altay Bayindir", "GK", 28, "Manchester United", 12],
    ["Eren Elmali", "DF", 25, "Galatasaray", 13],
    ["Abdulkerim Bardakci", "DF", 31, "Galatasaray", 14],
    ["Ozan Kabak", "DF", 26, "Hoffenheim", 15],
    ["Ismail Yuksek", "MF", 27, "Fenerbahce", 16],
    ["Irfan Can Kahveci", "FW", 30, "Fenerbahce", 17],
    ["Mert Muldur", "DF", 27, "Fenerbahce", 18],
    ["Yunus Akgun", "FW", 25, "Galatasaray", 19],
    ["Ferdi Kadioglu", "DF", 26, "Brighton", 20],
    ["Baris Alper Yilmaz", "FW", 26, "Galatasaray", 21],
    ["Kaan Ayhan", "DF", 31, "Galatasaray", 22],
    ["Ugurcan Cakir", "GK", 30, "Galatasaray", 23],
    ["Oguz Aydin", "FW", 25, "Fenerbahce", 24],
    ["Samet Akaydin", "DF", 32, "Caykur Rizespor", 25],
    ["Can Uzun", "MF", 20, "Eintracht Frankfurt", 26],
  ],
}
