import type { RosterTuple } from '../player-types'

export const GROUP_A_SQUADS: Record<string, RosterTuple[]> = {
  Mexico: [
    ['Guillermo Ochoa', 'GK', 39, 'Salernitana', 1], ['Luis Malagón', 'GK', 27, 'América', 2],
    ['Jorge Sánchez', 'DF', 27, 'Ajax', 3], ['César Montes', 'DF', 27, 'Almería', 4],
    ['Johan Vásquez', 'DF', 26, 'Genoa', 5], ['Gerardo Arteaga', 'DF', 26, 'Monterrey', 6],
    ['Kevin Álvarez', 'DF', 25, 'Pachuca', 7], ['Luis Chávez', 'DF', 28, 'Dynamo Moscow', 8],
    ['Edson Álvarez', 'MF', 27, 'West Ham', 9], ['Orbelín Pineda', 'MF', 28, 'AEK Athens', 10],
    ['Carlos Rodríguez', 'MF', 27, 'Cruz Azul', 11], ['Érick Gutiérrez', 'MF', 29, 'PSV', 12],
    ['Luis Quiñones', 'MF', 28, 'Tigres', 13], ['Hirving Lozano', 'FW', 29, 'PSV', 14],
    ['Santiago Giménez', 'FW', 24, 'Feyenoord', 15], ['Raúl Jiménez', 'FW', 34, 'Fulham', 16],
    ['Alexis Vega', 'FW', 27, 'Toluca', 17], ['Uriel Antuna', 'FW', 27, 'América', 18],
    ['Henry Martín', 'FW', 32, 'América', 19], ['Roberto Alvarado', 'FW', 26, 'Guadalajara', 20],
  ],
  'South Africa': [
    ['Ronwen Williams', 'GK', 32, 'Mamelodi Sundowns', 1], ['Veli Mothwa', 'GK', 28, 'AmaZulu', 2],
    ['Grant Kekana', 'DF', 33, 'Mamelodi Sundowns', 3], ['Teboho Mokoena', 'DF', 27, 'Mamelodi Sundowns', 4],
    ['Khuliso Mudau', 'DF', 28, 'Mamelodi Sundowns', 5], ['Aubrey Modiba', 'DF', 29, 'Mamelodi Sundowns', 6],
    ['Mosa Lebusa', 'DF', 30, 'Mamelodi Sundowns', 7], ['Nkosinathi Sibisi', 'DF', 28, 'Orlando Pirates', 8],
    ['Themba Zwane', 'MF', 35, 'Mamelodi Sundowns', 9], ['Sphephelo Sithole', 'MF', 25, 'Orlando Pirates', 10],
    ['Yusuf Maart', 'MF', 29, 'Kaizer Chiefs', 11], ['Sphelele Mkhulise', 'MF', 28, 'Mamelodi Sundowns', 12],
    ['Sphelele Mthethwa', 'MF', 26, 'AmaZulu', 13], ['Percy Tau', 'FW', 30, 'Al Ahly', 14],
    ['Evidence Makgopa', 'FW', 24, 'Orlando Pirates', 15], ['Zakhele Lepasa', 'FW', 28, 'Stellenbosch', 16],
    ['Thapelo Maseko', 'FW', 21, 'Mamelodi Sundowns', 17], ['Monnapule Saleng', 'FW', 26, 'Orlando Pirates', 18],
    ['Iqraam Rayners', 'FW', 29, 'Stellenbosch', 19], ['Bradley Grobler', 'FW', 36, 'SuperSport United', 20],
  ],
  'South Korea': [
    ['Kim Seung-gyu', 'GK', 33, 'Al Shabab', 1], ['Jo Hyeon-woo', 'GK', 33, 'Ulsan HD', 2],
    ['Kim Min-jae', 'DF', 28, 'Bayern Munich', 3], ['Kim Young-gwon', 'DF', 34, 'Ulsan HD', 4],
    ['Jung Seung-hyun', 'DF', 27, 'Ulsan HD', 5], ['Kim Jin-su', 'DF', 32, 'Jeonbuk Motors', 6],
    ['Hong Chi-gook', 'DF', 26, 'Jeonbuk Motors', 7], ['Kim Tae-hyeon', 'DF', 24, 'Suwon Samsung', 8],
    ['Lee Kang-in', 'MF', 24, 'PSG', 9], ['Hwang Hee-chan', 'MF', 28, 'Wolves', 10],
    ['Paik Seung-ho', 'MF', 27, 'Birmingham City', 11], ['Jeong Woo-yeong', 'MF', 25, 'Stuttgart', 12],
    ['Hong Hyun-seok', 'MF', 25, 'Genk', 13], ['Son Heung-min', 'FW', 33, 'Tottenham', 14],
    ['Cho Gue-sung', 'FW', 26, 'Midtjylland', 15], ['Oh Hyeon-gyu', 'FW', 23, 'Celtic', 16],
    ['Hwang Ui-jo', 'FW', 32, 'Alanyaspor', 17], ['Yang Hyun-jun', 'FW', 22, 'Celtic', 18],
    ['Lee Seung-won', 'FW', 21, 'Huddersfield', 19], ['Jung Ho-yeon', 'FW', 24, 'Minnesota United', 20],
  ],
  Denmark: [
    ['Kasper Schmeichel', 'GK', 38, 'Anderlecht', 1], ['Mads Hermansen', 'GK', 24, 'Leicester City', 2],
    ['Joachim Andersen', 'DF', 28, 'Crystal Palace', 3], ['Simon Kjær', 'DF', 35, 'AC Milan', 4],
    ['Victor Nelsson', 'DF', 26, 'Roma', 5], ['Rasmus Kristensen', 'DF', 27, 'Leeds United', 6],
    ['Jens Stryger Larsen', 'DF', 33, 'Club Brugge', 7], ['Alexander Bah', 'DF', 26, 'Benfica', 8],
    ['Christian Eriksen', 'MF', 33, 'Manchester United', 9], ['Thomas Delaney', 'MF', 33, 'Anderlecht', 10],
    ['Mattias Jensen', 'MF', 28, 'Brentford', 11], ['Morten Hjulmand', 'MF', 25, 'Sporting CP', 12],
    ['Pierre-Emile Højbjerg', 'MF', 29, 'Marseille', 13], ['Rasmus Højlund', 'FW', 22, 'Manchester United', 14],
    ['Andreas Skov Olsen', 'FW', 25, 'Club Brugge', 15], ['Jonas Wind', 'FW', 25, 'Wolfsburg', 16],
    ['Yussuf Poulsen', 'FW', 30, 'Copenhagen', 17], ['Gustav Isaksen', 'FW', 24, 'Lazio', 18],
    ['Jacob Bruun Larsen', 'FW', 26, 'Burnley', 19], ['Kasper Dolberg', 'FW', 27, 'Anderlecht', 20],
  ],
}