import type { RosterTuple } from '../player-types'

export const GROUP_J_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "Argentina": [
    ["Juan Musso", "GK", 32, "Atlético Madrid", 1],
    ["Leonardo Balerdi", "DF", 27, "Marseille", 2],
    ["Nicolás Tagliafico", "DF", 33, "Lyon", 3],
    ["Gonzalo Montiel", "DF", 29, "River Plate", 4],
    ["Leandro Paredes", "MF", 31, "Boca Juniors", 5],
    ["Lisandro Martínez", "DF", 28, "Manchester United", 6],
    ["Rodrigo De Paul", "MF", 32, "Inter Miami", 7],
    ["Valentín Barco", "MF", 21, "Strasbourg", 8],
    ["Julián Álvarez", "FW", 26, "Atlético Madrid", 9],
    ["Lionel Messi", "FW", 38, "Inter Miami", 10],
    ["Giovani Lo Celso", "MF", 30, "Real Betis", 11],
    ["Gerónimo Rulli", "GK", 34, "Marseille", 12],
    ["Cristian Romero", "DF", 28, "Tottenham", 13],
    ["Exequiel Palacios", "MF", 27, "Bayer Leverkusen", 14],
    ["Nicolás González", "MF", 28, "Atlético Madrid", 15],
    ["Thiago Almada", "MF", 25, "Atlético Madrid", 16],
    ["Giuliano Simeone", "FW", 23, "Atlético Madrid", 17],
    ["Nico Paz", "MF", 21, "Como", 18],
    ["Nicolás Otamendi", "DF", 38, "Benfica", 19],
    ["Alexis Mac Allister", "MF", 27, "Liverpool", 20],
    ["José López", "FW", 25, "Palmeiras", 21],
    ["Lautaro Martínez", "FW", 28, "Inter", 22],
    ["Emiliano Martínez", "GK", 33, "Aston Villa", 23],
    ["Enzo Fernández", "MF", 25, "Chelsea", 24],
    ["Facundo Medina", "DF", 27, "Marseille", 25],
    ["Nahuel Molina", "DF", 28, "Atlético Madrid", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Algeria": [
    ["Melvin Mastil", "GK", 26, "Lausanne-Sport", 1],
    ["Aissa Mandi", "DF", 34, "Lille", 2],
    ["Achraf Abada", "DF", 26, "USM Alger", 3],
    ["Mohamed Tougai", "DF", 26, "Espérance de Tunis", 4],
    ["Zineddine Belaid", "DF", 27, "JS Kabylie", 5],
    ["Ramiz Zerrouki", "MF", 28, "Feyenoord", 6],
    ["Riyad Mahrez", "FW", 35, "Al-Ahli", 7],
    ["Houssem Aouar", "MF", 27, "Al-Ittihad", 8],
    ["Amine Gouiri", "FW", 26, "Marseille", 9],
    ["Farès Chaïbi", "MF", 23, "Eintracht Frankfurt", 10],
    ["Anis Hadj Moussa", "FW", 24, "Feyenoord", 11],
    ["Nadhir Benbouali", "FW", 26, "Eto FC", 12],
    ["Jaouen Hadjam", "DF", 23, "Young Boys", 13],
    ["Hicham Boudaoui", "MF", 26, "Nice", 14],
    ["Rayan Aït-Nouri", "DF", 25, "Manchester City", 15],
    ["Oussama Benbot", "GK", 31, "USM Alger", 16],
    ["Rafik Belghali", "DF", 24, "Verona", 17],
    ["Mohamed Amine Amoura", "FW", 26, "Wolfsburg", 18],
    ["Nabil Bentaleb", "MF", 31, "Lille", 19],
    ["Adil Boulbina", "FW", 23, "Al-Duhail", 20],
    ["Ramy Bensebaini", "DF", 31, "Borussia Dortmund", 21],
    ["Ibrahim Maza", "MF", 20, "Bayer Leverkusen", 22],
    ["Luca Zidane", "GK", 28, "Granada", 23],
    ["Yacine Titraoui", "MF", 22, "Royal Charleroi", 24],
    ["Farès Ghedjemis", "FW", 23, "Frosinone", 25],
    ["Samir Chergui", "DF", 27, "Paris FC", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Austria": [
    ["Alexander Schlager", "GK", 30, "Red Bull Salzburg", 1],
    ["David Affengruber", "DF", 25, "Elche", 2],
    ["Kevin Danso", "DF", 27, "Tottenham", 3],
    ["Xaver Schlager", "MF", 28, "RB Leipzig", 4],
    ["Stefan Posch", "DF", 29, "Como", 5],
    ["Nicolas Seiwald", "MF", 25, "RB Leipzig", 6],
    ["Marko Arnautović", "FW", 37, "Red Star Belgrade", 7],
    ["David Alaba", "DF", 33, "Real Madrid", 8],
    ["Marcel Sabitzer", "MF", 32, "Borussia Dortmund", 9],
    ["Florian Grillitsch", "MF", 30, "Sporting Braga", 10],
    ["Michael Gregoritsch", "FW", 32, "Brøndby", 11],
    ["Florian Wiegele", "GK", 25, "Viktoria Plzeň", 12],
    ["Patrick Pentz", "GK", 29, "Brøndby", 13],
    ["Saša Kalajdžić", "FW", 28, "Wolves", 14],
    ["Philipp Lienhart", "DF", 29, "Freiburg", 15],
    ["Phillipp Mwene", "DF", 32, "Mainz 05", 16],
    ["Carney Chukwuemeka", "MF", 22, "Borussia Dortmund", 17],
    ["Romano Schmid", "MF", 26, "Werder Bremen", 18],
    ["Christoph Baumgartner", "MF", 26, "RB Leipzig", 19],
    ["Konrad Laimer", "MF", 29, "Bayern Munich", 20],
    ["Patrick Wimmer", "MF", 25, "Wolfsburg", 21],
    ["Alexander Prass", "DF", 25, "Hoffenheim", 22],
    ["Marco Friedl", "DF", 28, "Werder Bremen", 23],
    ["Paul Wanner", "MF", 20, "PSV Eindhoven", 24],
    ["Michael Svoboda", "DF", 27, "Venezia", 25],
    ["Alessandro Schöpf", "MF", 32, "Wolfsberger", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Jordan": [
    ["Yazeed Abulaila", "GK", 33, "Al-Hussien", 1],
    ["Mohammad Abu Hashish", "DF", 31, "Al-Karma", 2],
    ["Abdallah Nasib", "DF", 32, "Al-Zawraa", 3],
    ["Husam Abu Dahab", "DF", 26, "Al-Faisaly", 4],
    ["Yazan Al-Arab", "DF", 30, "FC Seoul", 5],
    ["Amer Jamous", "MF", 23, "Al-Zawraa", 6],
    ["Mohammad Abu Zrayq", "FW", 28, "Raja Club Athletic", 7],
    ["Noor Al-Rawabdeh", "MF", 29, "Selangor", 8],
    ["Ali Olwan", "FW", 26, "Al-Sailiya", 9],
    ["Musa Al-Taamari", "FW", 29, "Rennes", 10],
    ["Odeh Al-Fakhouri", "FW", 20, "Pyramids", 11],
    ["Nour Bani Attiah", "GK", 33, "Al-Faisaly", 12],
    ["Mahmoud Al-Mardi", "FW", 32, "Al-Hussein", 13],
    ["Rajaei Ayed", "MF", 32, "Al-Hussein SC", 14],
    ["Ibrahim Sadeh", "MF", 26, "Al-Karma", 15],
    ["Mohammad Abualnadi", "DF", 25, "Selangor", 16],
    ["Salim Obaid", "DF", 34, "Al-Hussein", 17],
    ["Mohammad Abu Ghoush", "FW", 20, "Shabab Al-Ordon", 18],
    ["Saed Al-Rosan", "DF", 29, "Al-Hussein", 19],
    ["Mohannad Abu Taha", "DF", 23, "Al-Quwa Al-Jawiya", 20],
    ["Nizar Al-Rashdan", "MF", 27, "Qatar SC", 21],
    ["Abdallah Al Fakhouri", "GK", 26, "Al-Wehdat", 22],
    ["Ehsan Haddad", "DF", 32, "Al-Hussein", 23],
    ["Ali Azaizeh", "FW", 22, "Al-Shabab", 24],
    ["Mohammad Al-Dawoud", "MF", 33, "Al-Wehdat", 25],
    ["Anas Badawi", "DF", 28, "Al-Faisaly", 26],
  ],
}
