import type { RosterTuple } from '../player-types'

export const GROUP_H_SQUADS: Record<string, RosterTuple[]> = {
  Spain: [
    ['Unai Simón', 'GK', 27, 'Athletic Bilbao', 1], ['David Raya', 'GK', 29, 'Arsenal', 2],
    ['Aymeric Laporte', 'DF', 30, 'Al Nassr', 3], ['Robin Le Normand', 'DF', 28, 'Atlético Madrid', 4],
    ['Daniel Carvajal', 'DF', 32, 'Real Madrid', 5], ['Jules Koundé', 'DF', 26, 'Barcelona', 6],
    ['Marc Cucurella', 'DF', 27, 'Chelsea', 7], ['Pedro Porro', 'DF', 25, 'Tottenham', 8],
    ['Rodri', 'MF', 28, 'Manchester City', 9], ['Pedri', 'MF', 22, 'Barcelona', 10],
    ['Gavi', 'MF', 20, 'Barcelona', 11], ['Fabián Ruiz', 'MF', 28, 'PSG', 12],
    ['Mikel Merino', 'MF', 28, 'Real Sociedad', 13], ['Lamine Yamal', 'FW', 18, 'Barcelona', 14],
    ['Nico Williams', 'FW', 22, 'Athletic Bilbao', 15], ['Álvaro Morata', 'FW', 32, 'AC Milan', 16],
    ['Dani Olmo', 'FW', 26, 'Barcelona', 17], ['Ferran Torres', 'FW', 24, 'Barcelona', 18],
    ['Joselu', 'FW', 34, 'Real Madrid', 19], ['Mikel Oyarzabal', 'FW', 27, 'Real Sociedad', 20],
  ],
  'Cape Verde': [
    ['Vozinha', 'GK', 38, 'Nacional', 1], ['Marcílio Dias', 'GK', 28, 'Nacional', 2],
    ['Stopira', 'DF', 35, 'Moreirense', 3], ['Jójó', 'DF', 32, 'Nacional', 4],
    ['Roberto Lopes', 'DF', 29, 'Shamrock Rovers', 5], ['Diney', 'DF', 31, 'Famalicão', 6],
    ['Patrick Andrade', 'DF', 30, 'Qadsia', 7], ['Steven Moreira', 'DF', 30, 'Columbus Crew', 8],
    ['Nuno Rocha', 'MF', 31, 'CSKA Sofia', 9], ['Jamiro Monteiro', 'MF', 30, 'San Jose Earthquakes', 10],
    ['Djaniny', 'MF', 33, 'Al Fateh', 11], ['Ryan Mendes', 'MF', 34, 'Al Nasr', 12],
    ['Patrick Andrade', 'MF', 30, 'Qadsia', 13], ['Ryan Mendes', 'FW', 34, 'Al Nasr', 14],
    ['Djaniny', 'FW', 33, 'Al Fateh', 15], ['Bébé', 'FW', 34, 'Rayo Vallecano', 16],
    ['Jovane Cabral', 'FW', 26, 'Sion', 17], ['Garissone Innocent', 'FW', 24, 'Le Havre', 18],
    ['Heldon Ramos', 'FW', 36, 'Nacional', 19], ['Ryan Mendes', 'FW', 34, 'Al Nasr', 20],
  ],
  'Saudi Arabia': [
    ['Mohammed Al-Owais', 'GK', 33, 'Al Hilal', 1], ['Yasser Al Mosailem', 'GK', 35, 'Al Ahli', 2],
    ['Ali Al-Bulaihi', 'DF', 35, 'Al Hilal', 3], ['Mohammed Al-Breik', 'DF', 32, 'Al Hilal', 4],
    ['Sultan Al-Ghannam', 'DF', 31, 'Al Nassr', 5], ['Yasser Al-Shahrani', 'DF', 32, 'Al Hilal', 6],
    ['Abdulelah Al-Amri', 'DF', 27, 'Al Nassr', 7], ['Hassan Al-Tambakti', 'DF', 28, 'Al Shabab', 8],
    ['Salem Al-Dawsari', 'MF', 33, 'Al Hilal', 9], ['Firas Al-Buraikan', 'MF', 25, 'Al Ahli', 10],
    ['Mohammed Kanno', 'MF', 30, 'Al Hilal', 11], ['Sami Al-Najei', 'MF', 27, 'Al Nassr', 12],
    ['Ayman Yahya', 'MF', 24, 'Al Nassr', 13], ['Saleh Al-Shehri', 'FW', 31, 'Al Hilal', 14],
    ['Firas Al-Buraikan', 'FW', 25, 'Al Ahli', 15], ['Abdullah Al-Hamdan', 'FW', 25, 'Al Hilal', 16],
    ['Salem Al-Dawsari', 'FW', 33, 'Al Hilal', 17], ['Fahad Al-Muwallad', 'FW', 33, 'Al Shabab', 18],
    ['Abdulrahman Ghareeb', 'FW', 27, 'Al Ahli', 19], ['Saleh Al-Shehri', 'FW', 31, 'Al Hilal', 20],
  ],
  Uruguay: [
    ['Sergio Rochet', 'GK', 31, 'Nacional', 1], ['Franco Israel', 'GK', 24, 'Porto', 2],
    ['José María Giménez', 'DF', 29, 'Atlético Madrid', 3], ['Ronald Araújo', 'DF', 25, 'Barcelona', 4],
    ['Sebastián Coates', 'DF', 33, 'Nacional', 5], ['Matías Viña', 'DF', 27, 'Flamengo', 6],
    ['Guillermo Varela', 'DF', 31, 'Flamengo', 7], ['Joaquín Piqueras', 'DF', 24, 'Penarol', 8],
    ['Federico Valverde', 'MF', 26, 'Real Madrid', 9], ['Rodrigo Bentancur', 'MF', 27, 'Tottenham', 10],
    ['Manuel Ugarte', 'MF', 23, 'Manchester United', 11], ['Nicolás de la Cruz', 'MF', 27, 'Flamengo', 12],
    ['Giorgian Arrascaeta', 'MF', 30, 'Flamengo', 13], ['Darwin Núñez', 'FW', 25, 'Liverpool', 14],
    ['Luis Suárez', 'FW', 38, 'Inter Miami', 15], ['Facundo Pellistri', 'FW', 23, 'Panathinaikos', 16],
    ['Maxi Gómez', 'FW', 28, 'Trabzonspor', 17], ['Facundo Torres', 'FW', 24, 'Orlando City', 18],
    ['Giorgian Arrascaeta', 'FW', 30, 'Flamengo', 19], ['Darwin Núñez', 'FW', 25, 'Liverpool', 20],
  ],
}