import type { RosterTuple } from '../player-types'

export const GROUP_F_SQUADS: Record<string, RosterTuple[]> = {
  Netherlands: [
    ['Bart Verbruggen', 'GK', 22, 'Brighton', 1], ['Mark Flekken', 'GK', 31, 'Brentford', 2],
    ['Virgil van Dijk', 'DF', 33, 'Liverpool', 3], ['Nathan Aké', 'DF', 29, 'Manchester City', 4],
    ['Denzel Dumfries', 'DF', 28, 'Inter Milan', 5], ['Jeremie Frimpong', 'DF', 24, 'Leverkusen', 6],
    ['Micky van de Ven', 'DF', 23, 'Tottenham', 7], ['Ian Maatsen', 'DF', 22, 'Aston Villa', 8],
    ['Frenkie de Jong', 'MF', 27, 'Barcelona', 9], ['Tijjani Reijnders', 'MF', 26, 'AC Milan', 10],
    ['Georginio Wijnaldum', 'MF', 34, 'Al Ettifaq', 11], ['Ryan Gravenberch', 'MF', 22, 'Liverpool', 12],
    ['Steven Bergwijn', 'MF', 27, 'Al Ittihad', 13], ['Memphis Depay', 'FW', 30, 'Corinthians', 14],
    ['Cody Gakpo', 'FW', 25, 'Liverpool', 15], ['Brian Brobbey', 'FW', 22, 'Ajax', 16],
    ['Steven Bergwijn', 'FW', 27, 'Al Ittihad', 17], ['Wout Weghorst', 'FW', 32, 'Ajax', 18],
    ['Xavi Simons', 'FW', 21, 'Leipzig', 19], ['Joshua Zirkzee', 'FW', 23, 'Manchester United', 20],
  ],
  Japan: [
    ['Gonda Shuichi', 'GK', 35, 'Shonan Bellmare', 1], ['Suzuki Zion', 'GK', 22, 'Parma', 2],
    ['Itakura Ko', 'DF', 27, 'Ajax', 3], ['Tomiyasu Takehiro', 'DF', 26, 'Arsenal', 4],
    ['Taniguchi Ko', 'DF', 33, 'Kawasaki Frontale', 5], ['Sugawara Yukinari', 'DF', 24, 'Southampton', 6],
    ['Hiroki Ito', 'DF', 25, 'Stuttgart', 7], ['Miki Yamane', 'DF', 29, 'Kawasaki Frontale', 8],
    ['Kamada Daichi', 'MF', 28, 'Lazio', 9], ['Endo Wataru', 'MF', 31, 'Liverpool', 10],
    ['Mitoma Kaoru', 'MF', 27, 'Brighton', 11], ['Kubo Takefusa', 'MF', 23, 'Real Sociedad', 12],
    ['Tanaka Ao', 'MF', 26, 'Fortuna Düsseldorf', 13], ['Minamino Takumi', 'FW', 29, 'Monaco', 14],
    ['Asano Takuma', 'FW', 30, 'Mainz', 15], ['Kubo Takefusa', 'FW', 23, 'Real Sociedad', 16],
    ['Furuhashi Kyogo', 'FW', 29, 'Celtic', 17], ['Doan Ritsu', 'FW', 26, 'Freiburg', 18],
    ['Soma Yuki', 'FW', 27, 'Cerezo Osaka', 19], ['Ueda Ayase', 'FW', 26, 'Feyenoord', 20],
  ],
  Ukraine: [
    ['Andriy Lunin', 'GK', 25, 'Real Madrid', 1], ['Anatoliy Trubin', 'GK', 23, 'Benfica', 2],
    ['Mykola Matviyenko', 'DF', 29, 'Shakhtar Donetsk', 3], ['Oleksandr Zinchenko', 'DF', 28, 'Arsenal', 4],
    ['Viktor Korniyenko', 'DF', 24, 'Shakhtar Donetsk', 5], ['Illia Zabarnyi', 'DF', 22, 'Bournemouth', 6],
    ['Yukhym Konoplya', 'DF', 25, 'Shakhtar Donetsk', 7], ['Bogdan Mykhaylichenko', 'DF', 27, 'Wolfsberger', 8],
    ['Ruslan Malinovskyi', 'MF', 31, 'Genoa', 9], ['Oleksandr Zinchenko', 'MF', 28, 'Arsenal', 10],
    ['Mykhailo Mudryk', 'MF', 23, 'Chelsea', 11], ['Heorhiy Sudakov', 'MF', 22, 'Shakhtar Donetsk', 12],
    ['Viktor Tsygankov', 'MF', 27, 'Girona', 13], ['Artem Dovbyk', 'FW', 27, 'Roma', 14],
    ['Roman Yaremchuk', 'FW', 29, 'Valencia', 15], ['Viktor Tsygankov', 'FW', 27, 'Girona', 16],
    ['Mykhailo Mudryk', 'FW', 23, 'Chelsea', 17], ['Artem Dovbyk', 'FW', 27, 'Roma', 18],
    ['Zinchenko Oleksandr', 'FW', 28, 'Arsenal', 19], ['Malinovskyi Ruslan', 'FW', 31, 'Genoa', 20],
  ],
  Tunisia: [
    ['Aymen Mathlouthi', 'GK', 38, 'Espérance', 1], ['Mouez Hassen', 'GK', 28, 'Club Africain', 2],
    ['Montassar Talbi', 'DF', 26, 'Lorient', 3], ['Yassine Meriah', 'DF', 31, 'Espérance', 4],
    ['Ali Maaloul', 'DF', 34, 'Al Ahly', 5], ['Wajdi Kechrida', 'DF', 28, 'Espérance', 6],
    ['Nader Ghandri', 'DF', 28, 'Club Africain', 7], ['Hamza Mathlouthi', 'DF', 25, 'Espérance', 8],
    ['Ellyes Skhiri', 'MF', 29, 'Eintracht Frankfurt', 9], ['Aïssa Laïdouni', 'MF', 28, 'Union Berlin', 10],
    ['Hamza Rafia', 'MF', 25, 'Lecce', 11], ['Saîf-Eddine Khaoui', 'MF', 29, 'Metz', 12],
    ['Hamza Rafia', 'MF', 25, 'Lecce', 13], ['Wahbi Khazri', 'FW', 33, 'Montpellier', 14],
    ['Issam Jebali', 'FW', 33, 'Odense', 15], ['Youssef Msakni', 'FW', 34, 'Al Arabi', 16],
    ['Taha Yassine Khenissi', 'FW', 32, 'Espérance', 17], ['Haythem Tlili', 'FW', 24, 'Club Africain', 18],
    ['Seifeddine Jaziri', 'FW', 31, 'Zamalek', 19], ['Hamza Rafia', 'FW', 25, 'Lecce', 20],
  ],
}