import type { RosterTuple } from '../player-types'

export const GROUP_I_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "France": [
    ["Brice Samba", "GK", 32, "Rennes", 1],
    ["Malo Gusto", "DF", 23, "Chelsea", 2],
    ["Lucas Digne", "DF", 32, "Aston Villa", 3],
    ["Dayot Upamecano", "DF", 27, "Bayern Munich", 4],
    ["Jules Koundé", "DF", 27, "Barcelona", 5],
    ["Manu Koné", "MF", 25, "Roma", 6],
    ["Ousmane Dembélé", "FW", 29, "Paris St-Germain", 7],
    ["Aurélien Tchouaméni", "MF", 26, "Real Madrid", 8],
    ["Marcus Thuram", "FW", 28, "Inter", 9],
    ["Kylian Mbappé", "FW", 27, "Real Madrid", 10],
    ["Michael Olise", "FW", 24, "Bayern Munich", 11],
    ["Bradley Barcola", "FW", 23, "Paris St-Germain", 12],
    ["N'Golo Kanté", "MF", 35, "Fenerbahce", 13],
    ["Adrien Rabiot", "MF", 31, "Milan", 14],
    ["Ibrahima Konaté", "DF", 27, "Free agent", 15],
    ["Mike Maignan", "GK", 30, "Milan", 16],
    ["William Saliba", "DF", 25, "Arsenal", 17],
    ["Warren Zaïre-Emery", "MF", 20, "Paris St-Germain", 18],
    ["Théo Hernández", "DF", 28, "Al-Hilal", 19],
    ["Désiré Doué", "FW", 21, "Paris St-Germain", 20],
    ["Lucas Hernández", "DF", 30, "Paris St-Germain", 21],
    ["Jean-Philippe Mateta", "FW", 28, "Crystal Palace", 22],
    ["Robin Risser", "GK", 21, "Lens", 23],
    ["Rayan Cherki", "FW", 22, "Manchester City", 24],
    ["Maghnes Akliouche", "FW", 24, "Monaco", 25],
    ["Maxence Lacroix", "DF", 26, "Crystal Palace", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Senegal": [
    ["Yehvann Diouf", "GK", 26, "Nice", 1],
    ["Mamadou Sarr", "DF", 20, "Chelsea", 2],
    ["Kalidou Koulibaly", "DF", 34, "Al-Hilal", 3],
    ["Abdoulaye Seck", "DF", 34, "Maccabi Haifa", 4],
    ["Idrissa ‘Gana’ Gueye", "MF", 36, "Everton", 5],
    ["Pathé Ciss", "MF", 32, "Rayo Vallecano", 6],
    ["Assane Diao", "FW", 20, "Como", 7],
    ["Lamine Camara", "MF", 22, "Monaco", 8],
    ["Bamba Dieng", "FW", 26, "Lorient", 9],
    ["Sadio Mané", "FW", 34, "Al-Nassr", 10],
    ["Nicolas Jackson", "FW", 24, "Chelsea", 11],
    ["Cherif Ndiaye", "FW", 30, "Samsunspor", 12],
    ["Iliman Ndiaye", "FW", 26, "Everton", 13],
    ["Ismail Jakobs", "DF", 26, "Galatasaray", 14],
    ["Krépin Diatta", "DF", 27, "Monaco", 15],
    ["Édouard Mendy", "GK", 34, "Al-Ahli", 16],
    ["Pape Matar Sarr", "MF", 23, "Tottenham", 17],
    ["Ismaïla Sarr", "FW", 28, "Crystal Palace", 18],
    ["Moussa Niakhaté", "DF", 30, "Lyon", 19],
    ["Ibrahim Mbaye", "FW", 18, "Paris St-Germain", 20],
    ["Habib Diarra", "MF", 22, "Sunderland", 21],
    ["Bara Sapoko Ndiaye", "MF", 18, "Bayern Munich", 22],
    ["Mory Diaw", "GK", 32, "Le Havre", 23],
    ["Antoine Mendy", "DF", 22, "Nice", 24],
    ["El Hadji Malick Diouf", "DF", 21, "West Ham", 25],
    ["Pape Gueye", "MF", 27, "Villarreal", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Iraq": [
    ["Fahad Talib", "GK", 31, "Al-Talaba", 1],
    ["Rebin Sulaka", "DF", 34, "FC Port", 2],
    ["Hussein Ali", "DF", 24, "Pogon Szczecin", 3],
    ["Zaid Tahseen", "DF", 25, "Pakhtakor FC", 4],
    ["Akam Hashem", "DF", 27, "Al-Zawraa", 5],
    ["Manaf Younis", "DF", 29, "Al-Shorta", 6],
    ["Youssef Amyn", "MF", 22, "AEK Larnaca", 7],
    ["Ibrahim Bayesh", "MF", 26, "Al-Dhafra", 8],
    ["Ali Al-Hamadi", "FW", 24, "Ipswich", 9],
    ["Mohanad Ali", "FW", 25, "Dibba", 10],
    ["Ahmed Qasim", "MF", 22, "Nashville", 11],
    ["Jalal Hassan", "GK", 35, "Al-Zawraa", 12],
    ["Ali Yousef", "FW", 30, "Al-Talaba", 13],
    ["Zidane Iqbal", "MF", 23, "Utrectht", 14],
    ["Ahmed Maknzi", "DF", 26, "", 15],
    ["Amir Al-Ammari", "MF", 28, "Cracovia", 16],
    ["Ali Jassim", "FW", 22, "Como", 17],
    ["Aymen Hussein", "FW", 30, "Al-Karma", 18],
    ["Kevin Yakob", "MF", 25, "AGF", 19],
    ["Aimar Sher", "MF", 23, "Sarpsborg", 20],
    ["Marko Farji", "FW", 22, "Venezia", 21],
    ["Ahmed Basil", "GK", 29, "Al-Shorta", 22],
    ["Merchas Doski", "DF", 26, "Viktoria Plzen", 23],
    ["Zaid Ismail", "MF", 24, "Al-Talaba", 24],
    ["Mustafa Saadoon", "DF", 25, "Al-Shorta", 25],
    ["Frans Putros", "DF", 32, "Persib Bandung", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Norway": [
    ["Ørjan Håskjold Nyland", "GK", 35, "Sevilla", 1],
    ["Morten Thorsby", "MF", 30, "Cremonese", 2],
    ["Kristoffer Ajer", "DF", 28, "Brentford", 3],
    ["Leo Østigård", "DF", 26, "Genoa", 4],
    ["David Møller Wolfe", "DF", 24, "Wolves", 5],
    ["Patrick Berg", "MF", 28, "Bodø/Glimt", 6],
    ["Alexander Sørloth", "FW", 30, "Atlético Madrid", 7],
    ["Sander Berge", "MF", 28, "Fulham", 8],
    ["Erling Haaland", "FW", 25, "Manchester City", 9],
    ["Martin Ødegaard", "MF", 27, "Arsenal", 10],
    ["Jørgen Strand Larsen", "FW", 26, "Crystal Palace", 11],
    ["Sander Tangvik", "GK", 23, "Hamburg", 12],
    ["Egil Selvik", "GK", 28, "Watford", 13],
    ["Fredrik Aursnes", "MF", 30, "Benfica", 14],
    ["Fredrik André Bjørkan", "DF", 27, "Bodø/Glimt", 15],
    ["Marcus Holmgren Pedersen", "DF", 25, "Torino", 16],
    ["Torbjørn Heggem", "DF", 27, "Bologna", 17],
    ["Kristian Thorstvedt", "MF", 27, "Sassuolo", 18],
    ["Thelo Aasgaard", "MF", 24, "Rangers", 19],
    ["Antonio Nusa", "FW", 21, "RB Leipzig", 20],
    ["Andreas Schjelderup", "FW", 22, "Benfica", 21],
    ["Oscar Bobb", "FW", 22, "Fulham", 22],
    ["Jens Petter Hauge", "FW", 26, "Bodø/Glimt", 23],
    ["Sondre Langås", "DF", 25, "Derby County", 24],
    ["Henrik Falchener", "DF", 23, "Viking", 25],
    ["Julian Ryerson", "DF", 28, "Borussia Dortmund", 26],
  ],
}
