import type { RosterTuple } from '../player-types'

export const GROUP_C_SQUADS: Record<string, RosterTuple[]> = {
  Brazil: [
    ['Alisson', 'GK', 32, 'Liverpool', 1], ['Ederson', 'GK', 31, 'Manchester City', 2],
    ['Marquinhos', 'DF', 30, 'PSG', 3], ['Danilo', 'DF', 33, 'Juventus', 4],
    ['Éder Militão', 'DF', 26, 'Real Madrid', 5], ['Gabriel Magalhães', 'DF', 27, 'Arsenal', 6],
    ['Wendell', 'DF', 31, 'Porto', 7], ['Vanderson', 'DF', 23, 'Monaco', 8],
    ['Bruno Guimarães', 'MF', 27, 'Newcastle', 9], ['Lucas Paquetá', 'MF', 27, 'West Ham', 10],
    ['André', 'MF', 24, 'Wolves', 11], ['Joelinton', 'MF', 28, 'Newcastle', 12],
    ['Rodrygo', 'MF', 24, 'Real Madrid', 13], ['Vinícius Jr.', 'FW', 25, 'Real Madrid', 14],
    ['Raphinha', 'FW', 28, 'Barcelona', 15], ['Richarlison', 'FW', 27, 'Tottenham', 16],
    ['Endrick', 'FW', 19, 'Real Madrid', 17], ['Evanilson', 'FW', 25, 'Bournemouth', 18],
    ['Savinho', 'FW', 21, 'Manchester City', 19], ['Martinelli', 'FW', 24, 'Arsenal', 20],
  ],
  Morocco: [
    ['Yassine Bounou', 'GK', 34, 'Al Hilal', 1], ['Munir El Kajoui', 'GK', 35, 'Wydad AC', 2],
    ['Achraf Hakimi', 'DF', 26, 'PSG', 3], ['Nayef Aguerd', 'DF', 28, 'Real Sociedad', 4],
    ['Romain Saïss', 'DF', 34, 'Al Shabab', 5], ['Noussair Mazraoui', 'DF', 27, 'Manchester United', 6],
    ['Azzedine Ounahi', 'DF', 24, 'Marseille', 7], ['Yahya Attiat-Allah', 'DF', 25, 'Panathinaikos', 8],
    ['Sofyan Amrabat', 'MF', 28, 'Manchester United', 9], ['Azzedine Ounahi', 'MF', 24, 'Marseille', 10],
    ['Selim Amallah', 'MF', 28, 'Valencia', 11], ['Bilal El Khannouss', 'MF', 20, 'Genk', 12],
    ['Amine Harit', 'MF', 27, 'Marseille', 13], ['Youssef En-Nesyri', 'FW', 27, 'Sevilla', 14],
    ['Brahim Díaz', 'FW', 25, 'Real Madrid', 15], ['Hakim Ziyech', 'FW', 31, 'Galatasaray', 16],
    ['Abde Ezzalzouli', 'FW', 23, 'Real Betis', 17], ['Ez Abde', 'FW', 22, 'Real Betis', 18],
    ['Sofiane Boufal', 'FW', 31, 'Lille', 19], ['Walid Cheddira', 'FW', 26, 'Frosinone', 20],
  ],
  Haiti: [
    ['Johny Placide', 'GK', 37, 'Valenciennes', 1], ['Josué Duverger', 'GK', 28, 'Violette AC', 2],
    ['Derrick Etienne', 'DF', 27, 'Atlético San Luis', 3], ['Carlens Arcus', 'DF', 29, 'Brest', 4],
    ['Jems Geffrard', 'DF', 30, 'Miami FC', 5], ['Henry Herold', 'DF', 24, 'Dynamo Dresden', 6],
    ['Ricardo Adé', 'DF', 26, 'Grenoble', 7], ['Martin Experience', 'DF', 25, 'Violette AC', 8],
    ['Duckens Nazon', 'MF', 27, 'Sheriff', 9], ['Bryan Alceus', 'MF', 32, 'Miami FC', 10],
    ['Steeven Saba', 'MF', 30, 'Miami FC', 11], ['Zachary Herivaux', 'MF', 28, 'Rhode Island FC', 12],
    ['Derrick Etienne Jr.', 'MF', 27, 'Atlético San Luis', 13], ['Frantzdy Pierrot', 'FW', 27, 'Anderlecht', 14],
    ['Mondy Prunier', 'FW', 24, 'Violette AC', 15], ['Carnejy Antoine', 'FW', 26, 'Portland Hearts of Pine', 16],
    ['Widzer Saintcyr', 'FW', 23, 'Violette AC', 17], ['Danley Jean', 'FW', 25, 'Miami FC', 18],
    ['Jeberson Bastien', 'FW', 28, 'Grenoble', 19], ['Béla Látori', 'FW', 22, 'Violette AC', 20],
  ],
  Scotland: [
    ['Angus Gunn', 'GK', 30, 'Norwich City', 1], ['Zander Clark', 'GK', 32, 'Hearts', 2],
    ['Kieran Tierney', 'DF', 28, 'Real Sociedad', 3], ['Andrew Robertson', 'DF', 30, 'Liverpool', 4],
    ['Grant Hanley', 'DF', 32, 'Bristol City', 5], ['Jack Hendry', 'DF', 29, 'Al Ettifaq', 6],
    ['Ross McCrorie', 'DF', 26, 'Bristol City', 7], ['Anthony Ralston', 'DF', 26, 'Celtic', 8],
    ['Scott McTominay', 'MF', 27, 'Napoli', 9], ['John McGinn', 'MF', 30, 'Aston Villa', 10],
    ['Billy Gilmour', 'MF', 23, 'Napoli', 11], ['Ryan Christie', 'MF', 29, 'Bournemouth', 12],
    ['Kenny McLean', 'MF', 32, 'Norwich City', 13], ['Che Adams', 'FW', 28, 'Torino', 14],
    ['Lyndon Dykes', 'FW', 29, 'QPR', 15], ['Lawrence Shankland', 'FW', 29, 'Rangers', 16],
    ['James Forrest', 'FW', 33, 'Celtic', 17], ['Ryan Gauld', 'FW', 28, 'Vancouver Whitecaps', 18],
    ['Kevin Nisbet', 'FW', 27, 'Millwall', 19], ['Lewis Morgan', 'FW', 28, 'New York Red Bulls', 20],
  ],
}