import type { RosterTuple } from '../player-types'

export const GROUP_H_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "Spain": [
    ["David Raya", "GK", 30, "Arsenal", 1],
    ["Marc Pubill", "DF", 22, "Atlético Madrid", 2],
    ["Álex Grimaldo", "DF", 30, "Bayer Leverkusen", 3],
    ["Eric García", "DF", 25, "Barcelona", 4],
    ["Marcos Llorente", "DF", 31, "Atlético Madrid", 5],
    ["Mikel Merino", "MF", 29, "Arsenal", 6],
    ["Ferran Torres", "FW", 26, "Barcelona", 7],
    ["Fabián Ruiz", "MF", 30, "Paris St-Germain", 8],
    ["Gavi", "MF", 21, "Barcelona", 9],
    ["Dani Olmo", "MF", 28, "Barcelona", 10],
    ["Yéremy Pino", "FW", 23, "Crystal Palace", 11],
    ["Pedro Porro", "DF", 26, "Tottenham", 12],
    ["Joan García", "GK", 25, "Barcelona", 13],
    ["Aymeric Laporte", "DF", 32, "Athletic Club", 14],
    ["Álex Baena", "MF", 24, "Atlético Madrid", 15],
    ["Rodri", "MF", 29, "Manchester City", 16],
    ["Nico Williams", "FW", 23, "Athletic Club", 17],
    ["Martín Zubimendi", "MF", 27, "Arsenal", 18],
    ["Lamine Yamal", "FW", 18, "Barcelona", 19],
    ["Pedri", "MF", 23, "Barcelona", 20],
    ["Mikel Oyarzabal", "FW", 29, "Real Sociedad", 21],
    ["Pau Cubarsí", "DF", 19, "Barcelona", 22],
    ["Unai Simón", "GK", 29, "Athletic Club", 23],
    ["Marc Cucurella", "DF", 27, "Chelsea", 24],
    ["Víctor Muñoz", "FW", 22, "Osasuna", 25],
    ["Borja Iglesias", "FW", 33, "Celta Vigo", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Cape Verde": [
    ["Josimar ‘Vozinha’ Dias", "GK", 40, "Chaves", 1],
    ["Ianique ‘Stopira’ Tavares", "DF", 38, "Torrense", 2],
    ["‘Diney’ Borges", "DF", 31, "Al Bataeh", 3],
    ["Roberto ‘Pico’ Lopes", "DF", 33, "Shamrock Rovers", 4],
    ["Logan Costa", "DF", 25, "Villarreal", 5],
    ["Kevin Lenini Pina", "MF", 29, "Krasnodar", 6],
    ["Jovane Cabral", "FW", 27, "Unattached", 7],
    ["João Paulo Fernandes", "DF", 28, "FCSB", 8],
    ["Gilson ‘Benchimol’ Tavares", "FW", 24, "Akron Tolyatti", 9],
    ["Jamiro Monteiro", "MF", 32, "PEC Zwolle", 10],
    ["Garry Rodrigues", "MF", 35, "Apollon Limassol", 11],
    ["Marcio da Rosa", "GK", 29, "PFC Montana", 12],
    ["Sidny Lopes Cabral", "DF", 23, "Benfica", 13],
    ["Deroy Duarte", "MF", 26, "Ludogorets Razgrad", 14],
    ["Laros Duarte", "MF", 29, "Puskás Akadémia", 15],
    ["Yannick Semedo", "MF", 30, "Farense", 16],
    ["Willy Semedo", "FW", 32, "Omonia Nicosia", 17],
    ["Telmo Arcanjo", "MF", 24, "Vitória de Guimarães", 18],
    ["Dailon Livramento", "FW", 25, "Casa Pia", 19],
    ["Ryan Mendes", "MF", 36, "Igdir", 20],
    ["Nuno da Costa", "FW", 35, "Basaksehir", 21],
    ["Steven Moreira", "DF", 31, "Columbus Crew", 22],
    ["Carlos ‘CJ’ Dos Santos", "GK", 25, "San Diego FC", 23],
    ["Wagner Pina", "DF", 23, "Trabzonspor", 24],
    ["Kelvin Pires", "DF", 26, "SJK", 25],
    ["Helio Varela", "FW", 24, "Maccabi Tel-Aviv", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Saudi Arabia": [
    ["Nawaf Al-Aqidi", "GK", 26, "Al-Nassr", 1],
    ["Ali Majrashi", "DF", 26, "Al-Ahli", 2],
    ["Ali Lajami", "DF", 30, "Al-Hilal", 3],
    ["Abdulelah Al-Amri", "DF", 29, "Al-Nassr", 4],
    ["Hassan Al-Tambakti", "DF", 27, "Al-Hilal", 5],
    ["Nasser Al-Dawsari", "MF", 27, "Al-Hilal", 6],
    ["Musab Al-Juwayr", "MF", 22, "Al-Qadsiah", 7],
    ["Ayman Yahya", "MF", 25, "Al-Nassr", 8],
    ["Firas Al-Buraikan", "FW", 26, "Al-Ahli", 9],
    ["Salem Al-Dawsari", "FW", 34, "Al-Hilal", 10],
    ["Saleh Al-Shehri", "FW", 32, "Al-Ittihad", 11],
    ["Saud Abdulhamid", "DF", 26, "Lens", 12],
    ["Nawaf Boushal", "DF", 26, "Al-Nassr", 13],
    ["Hassan Kadesh", "DF", 33, "Al-Ittihad", 14],
    ["Abdullah Al-Khaibari", "MF", 29, "Al-Nassr", 15],
    ["Ziyad Al-Johani", "MF", 24, "Al-Ahli", 16],
    ["Khalid Al-Ghannam", "MF", 25, "Al-Ettifaq", 17],
    ["Alaa Al-Hejji", "MF", 30, "Neom", 18],
    ["Abdullah Al-Hamdan", "FW", 26, "Al-Nassr", 19],
    ["Sultan Mandash", "FW", 31, "Al-Hilal", 20],
    ["Mohammed Al-Owais", "GK", 34, "Al-Ula", 21],
    ["Ahmed Al-Kassar", "GK", 35, "Al-Qadsiah", 22],
    ["Mohamed Kanno", "MF", 31, "Al-Hilal", 23],
    ["Moteb Al-Harbi", "DF", 26, "Al-Hilal", 24],
    ["Jehad Thakri", "DF", 24, "Al-Qadsiah", 25],
    ["Mohammed Abu Al-Shamat", "DF", 23, "Al-Qadsiah", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Uruguay": [
    ["Sergio Rochet", "GK", 33, "Internacional", 1],
    ["José María Giménez", "DF", 31, "Atlético Madrid", 2],
    ["Sebastián Cáceres", "DF", 26, "Club América", 3],
    ["Ronald Araújo", "DF", 27, "Barcelona", 4],
    ["Manuel Ugarte", "MF", 25, "Manchester United", 5],
    ["Rodrigo Bentancur", "MF", 28, "Tottenham", 6],
    ["Nicolás de la Cruz", "MF", 29, "Flamengo", 7],
    ["Federico Valverde", "MF", 27, "Real Madrid", 8],
    ["Darwin Núñez", "FW", 26, "Al-Hilal", 9],
    ["Giorgian de Arrascaeta", "MF", 32, "Flamengo", 10],
    ["Facundo Pellistri", "FW", 24, "Panathinaikos", 11],
    ["Santiago Mele", "GK", 28, "Monterrey", 12],
    ["Guillermo Varela", "DF", 33, "Flamengo", 13],
    ["Agustín Canobbio", "MF", 27, "Fluminense", 14],
    ["Emiliano Martínez", "MF", 26, "Palmeiras", 15],
    ["Mathías Olivera", "DF", 28, "Napoli", 16],
    ["Matías Viña", "DF", 28, "River Plate", 17],
    ["Brian Rodríguez", "FW", 26, "Club América", 18],
    ["Rodrigo Aguirre", "FW", 31, "Tigres", 19],
    ["Maximiliano Araújo", "FW", 26, "Sporting", 20],
    ["Federico Viñas", "FW", 27, "León", 21],
    ["Joaquín Piquerez", "DF", 27, "Palmeiras", 22],
    ["Fernando Muslera", "GK", 39, "Estudiantes de La Plata", 23],
    ["Santiago Bueno", "DF", 27, "Wolves", 24],
    ["Juan Manuel Sanabria", "DF", 26, "Real Salt Lake", 25],
    ["Rodrigo Zalazar", "MF", 26, "Braga", 26],
  ],
}
