import type { RosterTuple } from '../player-types'

export const GROUP_E_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "Germany": [
    ["Manuel Neuer", "GK", 40, "Bayern Munich", 1],
    ["Antonio Rüdiger", "DF", 33, "Real Madrid", 2],
    ["Waldemar Anton", "DF", 29, "Borussia Dortmund", 3],
    ["Jonathan Tah", "DF", 30, "Bayern Munich", 4],
    ["Aleksandar Pavlovic", "MF", 22, "Bayern Munich", 5],
    ["Joshua Kimmich", "DF", 31, "Bayern Munich", 6],
    ["Kai Havertz", "FW", 27, "Arsenal", 7],
    ["Leon Goretzka", "MF", 31, "Bayern Munich", 8],
    ["Jamie Leweling", "MF", 25, "Stuttgart", 9],
    ["Jamal Musiala", "MF", 23, "Bayern Munich", 10],
    ["Nick Woltemade", "FW", 24, "Newcastle", 11],
    ["Oliver Baumann", "GK", 36, "Hoffenheim", 12],
    ["Pascal Gross", "MF", 34, "Brighton", 13],
    ["Maximilian Beier", "FW", 23, "Borussia Dortmund", 14],
    ["Nico Schlotterbeck", "DF", 26, "Borussia Dortmund", 15],
    ["Angelo Stiller", "MF", 25, "Stuttgart", 16],
    ["Florian Wirtz", "MF", 23, "Liverpool", 17],
    ["Nathaniel Brown", "DF", 22, "Eintracht Frankfurt", 18],
    ["Leroy Sané", "FW", 30, "Galatasaray", 19],
    ["Nadiem Amiri", "MF", 29, "Mainz", 20],
    ["Alexander Nübel", "GK", 29, "Stuttgart", 21],
    ["David Raum", "DF", 28, "RB Leipzig", 22],
    ["Felix Nmecha", "MF", 25, "Borussia Dortmund", 23],
    ["Malick Thiaw", "DF", 24, "Newcastle", 24],
    ["Assan Ouédraogo", "MF", 20, "RB Leipzig", 25],
    ["Deniz Undav", "FW", 29, "Stuttgart", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Curaçao": [
    ["Eloy Room", "GK", 37, "Miami FC", 1],
    ["Shurandy Sambo", "DF", 24, "Burnley", 2],
    ["Juriën Gaari", "DF", 32, "Abha", 3],
    ["Roshon van Eijma", "DF", 28, "RKC Waalwijk", 4],
    ["Sherel Floranus", "DF", 27, "PEC Zwolle", 5],
    ["Godfried Roemeratoe", "MF", 26, "RKC Waalwijk", 6],
    ["Juninho Bacuna", "MF", 28, "Gaziantep", 7],
    ["Livano Comenencia", "MF", 22, "FC Zurich", 8],
    ["Jürgen Locadia", "FW", 32, "Miami FC", 9],
    ["Leandro Bacuna", "MF", 34, "Igdir", 10],
    ["Jeremy Antonisse", "FW", 24, "Kifisia", 11],
    ["Sontje Hansen", "FW", 24, "Middlesbrough", 12],
    ["Tyrese Noslin", "MF", 23, "SC Telstar", 13],
    ["Kenji Gorré", "FW", 31, "Maccabi Haifa", 14],
    ["Ar'jany Martha", "MF", 22, "Rotherham", 15],
    ["Jearl Margaritha", "FW", 26, "Beveren", 16],
    ["Brandley Kuwas", "FW", 33, "Volendam", 17],
    ["Armando Obispo", "DF", 27, "PSV Eindhoven", 18],
    ["Gervane Kastaneer", "FW", 30, "Terengganu FC", 19],
    ["Joshua Brenet", "DF", 32, "Kayserispor", 20],
    ["Tahith Chong", "FW", 26, "Sheffield United", 21],
    ["Kevin Felida", "MF", 26, "FC Den Bosch", 22],
    ["Riechedly Bazoer", "DF", 29, "Konyaspor", 23],
    ["Deveron Fonville", "DF", 23, "NEC Nigmegen", 24],
    ["Tyrick Bodak", "GK", 24, "Telstar", 25],
    ["Trevor Doornbusch", "GK", 26, "VVV-Venlo", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Ivory Coast": [
    ["Yahia Fofana", "GK", 25, "Caykur Rizespor", 1],
    ["Ousmane Diomande", "DF", 22, "Sporting", 2],
    ["Ghislain Konan", "DF", 30, "Gil Vicente", 3],
    ["Jean Michaël Seri", "MF", 34, "Maribor", 4],
    ["Wilfried Singo", "DF", 25, "Galatasaray", 5],
    ["Séko Fofana", "MF", 31, "Porto", 6],
    ["Odilon Kossounou", "DF", 25, "Atalanta", 7],
    ["Franck Kessié", "MF", 29, "Al-Ahli", 8],
    ["Ange-Yoan Bonny", "FW", 22, "Inter", 9],
    ["Simon Adingra", "FW", 24, "Sunderland", 10],
    ["Yan Diomande", "FW", 19, "RB Leipzig", 11],
    ["Elye Wahi", "FW", 23, "Eintracht Frankfurt", 12],
    ["Christopher Opéri", "DF", 29, "Basaksehir", 13],
    ["Oumar Diakité", "FW", 22, "Cercle Bruges", 14],
    ["Amad Diallo", "FW", 23, "Manchester United", 15],
    ["Mohamed Koné", "GK", 24, "Charleroi", 16],
    ["Guela Doué", "DF", 23, "Strasbourg", 17],
    ["Ibrahim Sangaré", "MF", 28, "Nottingham Forest", 18],
    ["Nicolas Pépé", "FW", 31, "Villareal", 19],
    ["Emmanuel Agbadou", "DF", 28, "Besiktas", 20],
    ["Evan Ndicka", "DF", 26, "Roma", 21],
    ["Evann Guessand", "FW", 24, "Aston Villa", 22],
    ["Alban Lafont", "GK", 27, "Nantes", 23],
    ["Bazoumana Touré", "FW", 20, "Hoffenheim", 24],
    ["Parfait Guiagon", "MF", 25, "Charleroi", 25],
    ["Christ Inao Oulaï", "MF", 20, "Trabzonspor", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Ecuador": [
    ["Hernán Galíndez", "GK", 39, "CA Huracán", 1],
    ["Félix Torres", "DF", 29, "Internacional", 2],
    ["Piero Hincapié", "DF", 24, "Arsenal", 3],
    ["Joel Ordóñez", "DF", 22, "Club Brugge", 4],
    ["Jordy Alcívar", "MF", 26, "Independiente del Valle", 5],
    ["Willian Pacho", "DF", 24, "Paris St-Germain", 6],
    ["Pervis Estupiñán", "DF", 28, "Milan", 7],
    ["Anthony Valencia", "FW", 22, "Royal Antwerp", 8],
    ["John Yeboah", "FW", 25, "Venezia", 9],
    ["Kendry Páez", "FW", 19, "River Plate", 10],
    ["Kevin Rodríguez", "FW", 26, "Union Saint-Gilloise", 11],
    ["Moisés Ramírez", "GK", 25, "Kifisia", 12],
    ["Enner Valencia", "FW", 36, "Pachuca", 13],
    ["Alan Minda", "FW", 23, "Atlético Mineiro", 14],
    ["Pedro Vite", "FW", 24, "Pumas UNAM", 15],
    ["Jordy Caicedo", "FW", 28, "CA Huracán", 16],
    ["Ángelo Preciado", "DF", 24, "Atlético Mineiro", 17],
    ["Denil Castillo", "MF", 22, "Midtjylland", 18],
    ["Gonzalo Plata", "FW", 25, "Flamengo", 19],
    ["Nilson Angulo", "FW", 22, "Sunderland", 20],
    ["Alan Franco", "MF", 27, "Atlético Mineiro", 21],
    ["Gonzalo Valle", "GK", 30, "LDU Quito", 22],
    ["Moisés Caicedo", "MF", 24, "Chelsea", 23],
    ["Jeremy Arévalo", "FW", 21, "Stuttgart", 24],
    ["Jackson Porozo", "DF", 25, "Tijuana", 25],
    ["Yaimar Medina", "DF", 21, "Genk", 26],
  ],
}
