import type { RosterTuple } from '../player-types'

export const GROUP_K_SQUADS: Record<string, RosterTuple[]> = {
  /** Guardian WC2026 guide, Jun 2026 */
  "Portugal": [
    ["Diogo Costa", "GK", 26, "Porto", 1],
    ["Nélson Semedo", "DF", 32, "Fenerbahce", 2],
    ["Rúben Dias", "DF", 29, "Manchester City", 3],
    ["Tomás Araújo", "DF", 24, "Benfica", 4],
    ["Diogo Dalot", "DF", 27, "Manchester United", 5],
    ["Matheus Nunes", "DF", 27, "Manchester City", 6],
    ["Cristiano Ronaldo", "FW", 41, "Al-Nassr", 7],
    ["Bruno Fernandes", "MF", 31, "Manchester United", 8],
    ["Gonçalo Ramos", "FW", 24, "Paris St-Germain", 9],
    ["Bernardo Silva", "MF", 31, "Manchester City", 10],
    ["João Félix", "FW", 26, "Al-Nassr", 11],
    ["José Sá", "GK", 33, "Wolves", 12],
    ["Renato Veiga", "DF", 22, "Villarreal", 13],
    ["Gonçalo Inácio", "DF", 24, "Sporting", 14],
    ["João Neves", "MF", 21, "Paris St-Germain", 15],
    ["Francisco Trincão", "MF", 26, "Sporting", 16],
    ["Rafael Leão", "FW", 27, "Milan", 17],
    ["Pedro Neto", "FW", 26, "Chelsea", 18],
    ["Gonçalo Guedes", "FW", 29, "Real Sociedad", 19],
    ["João Cancelo", "DF", 32, "Barcelona", 20],
    ["Rúben Neves", "MF", 29, "Al-Hilal", 21],
    ["Rui Silva", "GK", 32, "Sporting", 22],
    ["Vitinha", "MF", 26, "Paris St-Germain", 23],
    ["Samú Costa", "MF", 25, "Real Mallorca", 24],
    ["Nuno Mendes", "DF", 23, "Paris St-Germain", 25],
    ["Francisco Conceição", "FW", 23, "Juventus", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "DR Congo": [
    ["Lionel Mpasi", "GK", 31, "Le Havre", 1],
    ["Aaron Wan-Bissaka", "DF", 28, "West Ham", 2],
    ["Steve Kapuadi", "DF", 28, "Widzew Lodz", 3],
    ["Axel Tuanzebe", "DF", 28, "Burnley", 4],
    ["Dylan Batubinsika", "DF", 30, "AE Larissa", 5],
    ["Ngal’ayel Mukau", "MF", 21, "Lille", 6],
    ["Nathanaël Mbuku", "FW", 24, "Montpellier", 7],
    ["Samuel Moutoussamy", "MF", 29, "Atromitos", 8],
    ["Brian Cipenga", "FW", 28, "Castellón", 9],
    ["Théo Bongonda", "FW", 30, "Spartak Moscow", 10],
    ["Gaël Kakuta", "MF", 34, "AE Larissa", 11],
    ["Joris Kayembe", "DF", 31, "Genk", 12],
    ["Meschack Elia", "FW", 28, "Alanyaspor", 13],
    ["Noah Sadiki", "MF", 21, "Sunderland", 14],
    ["Aaron Tshibola", "DF", 31, "Kilmarnock", 15],
    ["Timothy Fayulu", "GK", 26, "FC Noah", 16],
    ["Cédric Bakambu", "FW", 35, "Real Betis", 17],
    ["Charles Pickel", "MF", 29, "Espanyol", 18],
    ["Fiston Mayele", "FW", 31, "Pyramids", 19],
    ["Yoane Wissa", "FW", 29, "Newcastle", 20],
    ["Matthieu Epolo", "GK", 21, "Standard Liège", 21],
    ["Chancel Mbemba", "DF", 31, "Lille", 22],
    ["Simon Banza", "FW", 29, "Al Jazira", 23],
    ["Gédéon Kalulu", "DF", 28, "Aris Limassol", 24],
    ["Edo Kayembe", "MF", 28, "Watford", 25],
    ["Arthur Masuaku", "DF", 32, "Lens", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Uzbekistan": [
    ["Utkir Yusupov", "GK", 35, "Navbakhor", 1],
    ["Abdukodir Khusanov", "DF", 22, "Manchester City", 2],
    ["Khojiakbar Alijonov", "DF", 29, "Pakhtakor", 3],
    ["Farrukh Sayfiev", "DF", 35, "Neftchi", 4],
    ["Rustam Ashurmatov", "DF", 30, "Esteghlal", 5],
    ["Akmal Mozgovoy", "MF", 27, "Pakhtakor", 6],
    ["Otabek Shukurov", "MF", 29, "Baniyas", 7],
    ["Jamshid Iskanderov", "MF", 32, "Neftchi", 8],
    ["Odiljon Khamrobekov", "MF", 30, "Tractor", 9],
    ["Jaloliddin Masharipov", "FW", 32, "Esteghlal", 10],
    ["Oston Urunov", "FW", 25, "Persepolis", 11],
    ["Abduvokhid Nematov", "GK", 25, "Nasaf", 12],
    ["Sherzod Nasrullaev", "DF", 27, "Pakhtakor", 13],
    ["Eldor Shomurodov", "FW", 30, "Roma", 14],
    ["Umar Eshmurodov", "DF", 33, "Nasaf", 15],
    ["Botirali Ergashev", "GK", 30, "Neftchi", 16],
    ["Dostonbek Khamdamov", "FW", 29, "Pakhtakor", 17],
    ["Abdulla Abdullaev", "DF", 28, "Dibba", 18],
    ["Azizjon Ganiev", "MF", 28, "Al Bataeh", 19],
    ["Azizbek Amonov", "MF", 28, "Dinamo Samarkand", 20],
    ["Igor Sergeev", "FW", 33, "Persepolis", 21],
    ["Abbosbek Fayzullaev", "MF", 22, "Basaksehir", 22],
    ["Sherzod Esanov", "MF", 23, "FC Buxoro", 23],
    ["Bekhruz Karimov", "DF", 18, "Surkhon", 24],
    ["Avazbek Ulmasaliev", "DF", 26, "Olmaliq", 25],
    ["Jakhongir Urozov", "DF", 22, "Dinamo Samarkand", 26],
  ],
  /** Guardian WC2026 guide, Jun 2026 */
  "Colombia": [
    ["David Ospina", "GK", 37, "Atlético Nacional", 1],
    ["Daniel Muñoz", "DF", 30, "Crystal Palace", 2],
    ["Jhon Lucumí", "DF", 27, "Bologna", 3],
    ["Santiago Arias", "DF", 34, "Independiente", 4],
    ["Kevin Castaño", "MF", 25, "River Plate", 5],
    ["Richard Ríos", "MF", 26, "Benfica", 6],
    ["Luis Díaz", "FW", 29, "Bayern Munich", 7],
    ["Jorge Carrascal", "MF", 28, "Flamengo", 8],
    ["Jhon Córdoba", "FW", 33, "Krasnodar", 9],
    ["James Rodríguez", "MF", 34, "Minnesota United", 10],
    ["Jhon Arias", "MF", 28, "Palmeiras", 11],
    ["Camilo Vargas", "GK", 37, "Atlas", 12],
    ["Yerry Mina", "DF", 31, "Cagliari", 13],
    ["Gustavo Puerta", "MF", 22, "Racing Santander", 14],
    ["Juan Portilla", "MF", 27, "Athletico Paranaense", 15],
    ["Jefferson Lerma", "MF", 31, "Crystal Palace", 16],
    ["Johan Mojica", "DF", 33, "Mallorca", 17],
    ["Willer Ditta", "DF", 28, "Cruz Azul", 18],
    ["Juan Camilo ‘Cucho’ Hernández", "FW", 27, "Real Betis", 19],
    ["Juan Quintero", "MF", 33, "River Plate", 20],
    ["Jaminton Campaz", "FW", 26, "Rosario Central", 21],
    ["Deiver Machado", "DF", 32, "Nantes", 22],
    ["Davinson Sánchez", "DF", 29, "Galatasaray", 23],
    ["Álvaro Montero", "GK", 31, "Vélez Sarsfield", 24],
    ["Luis Suárez", "FW", 28, "Sporting", 25],
    ["Carlos Andrés Gómez", "FW", 23, "Vasco da Gama", 26],
  ],
}
