import type { RosterTuple } from '../player-types'

export const GROUP_E_SQUADS: Record<string, RosterTuple[]> = {
  Germany: [
    ['Manuel Neuer', 'GK', 39, 'Bayern Munich', 1], ['Marc-André ter Stegen', 'GK', 33, 'Barcelona', 2],
    ['Jonathan Tah', 'DF', 29, 'Leverkusen', 3], ['Antonio Rüdiger', 'DF', 31, 'Real Madrid', 4],
    ['Nico Schlotterbeck', 'DF', 25, 'Dortmund', 5], ['David Raum', 'DF', 26, 'Leipzig', 6],
    ['Benjamin Henrichs', 'DF', 27, 'Leipzig', 7], ['Robin Gosens', 'DF', 30, 'Fiorentina', 8],
    ['Joshua Kimmich', 'MF', 30, 'Bayern Munich', 9], ['Jamal Musiala', 'MF', 22, 'Bayern Munich', 10],
    ['Florian Wirtz', 'MF', 22, 'Leverkusen', 11], ['Pascal Groß', 'MF', 33, 'Brighton', 12],
    ['Robert Andrich', 'MF', 30, 'Leverkusen', 13], ['Kai Havertz', 'FW', 26, 'Arsenal', 14],
    ['Niclas Füllkrug', 'FW', 31, 'Dortmund', 15], ['Leroy Sané', 'FW', 29, 'Bayern Munich', 16],
    ['Serge Gnabry', 'FW', 29, 'Bayern Munich', 17], ['Timo Werner', 'FW', 28, 'Tottenham', 18],
    ['Deniz Undav', 'FW', 28, 'Stuttgart', 19], ['Maximilian Beier', 'FW', 22, 'Dortmund', 20],
  ],
  'Curaçao': [
    ['Trevor Doornbusch', 'GK', 26, 'HHC Hardenberg', 1], ['Eloy Room', 'GK', 34, 'NAC Breda', 2],
    ['Juriën Gaari', 'DF', 26, 'Almere City', 3], ['Ridgeciano Haps', 'DF', 31, 'Inter Miami', 4],
    ['Juriën Gaari', 'DF', 26, 'Almere City', 5], ['Sherel Floranus', 'DF', 27, 'Las Vegas Lights', 6],
    ['Cuco Martina', 'DF', 35, 'RKC Waalwijk', 7], ['Juriën Gaari', 'DF', 26, 'Almere City', 8],
    ['Leandro Bacuna', 'MF', 33, 'Watford', 9], ['Brandley Kuwas', 'MF', 31, 'Almere City', 10],
    ['Elson Hooi', 'MF', 29, 'ADO Den Haag', 11], ['Gyrano Kerk', 'MF', 28, 'Zürich', 12],
    ['Roly Bonevacia', 'MF', 33, 'Western Sydney', 13], ['Gervane Kastaneer', 'FW', 28, 'Burton Albion', 14],
    ['Jarchinio Antonia', 'FW', 35, 'Sparta Rotterdam', 15], ['Shanon Carmelia', 'FW', 27, 'Helmond Sport', 16],
    ['Juriën Gaari', 'FW', 26, 'Almere City', 17], ['Rangelo Janga', 'FW', 29, 'NAC Breda', 18],
    ['Gervane Kastaneer', 'FW', 28, 'Burton Albion', 19], ['Leandro Bacuna', 'FW', 33, 'Watford', 20],
  ],
  'Ivory Coast': [
    ['Badra Ali Sangaré', 'GK', 37, 'Horoya', 1], ['Yahia Fofana', 'GK', 24, 'Angers', 2],
    ['Ousmane Diomandé', 'DF', 21, 'Sporting CP', 3], ['Eric Bailly', 'DF', 30, 'Besiktas', 4],
    ['Wilfried Zaha', 'DF', 32, 'Galatasaray', 5], ['Ghislain Konan', 'DF', 29, 'Al-Fayha', 6],
    ['Serge Aurier', 'DF', 32, 'Hearts', 7], ['Ismaël Koné', 'DF', 22, 'Watford', 8],
    ['Franck Kessié', 'MF', 28, 'Al Ahli', 9], ['Sébastien Haller', 'MF', 30, 'Borussia Dortmund', 10],
    ['Jean-Philippe Krasso', 'MF', 27, 'Sunderland', 11], ['Ibrahim Sangaré', 'MF', 26, 'Nottingham Forest', 12],
    ['Jean Michaël Seri', 'MF', 33, 'Hull City', 13], ['Nicolas Pépé', 'FW', 29, 'Trabzonspor', 14],
    ['Simon Adingra', 'FW', 22, 'Brighton', 15], ['Amad Diallo', 'FW', 22, 'Manchester United', 16],
    ['Wilfried Zaha', 'FW', 32, 'Galatasaray', 17], ['Jonathan Bamba', 'FW', 28, 'Lens', 18],
    ['Evann Guessand', 'FW', 23, 'Nice', 19], ['Karim Konaté', 'FW', 22, 'Red Bull Salzburg', 20],
  ],
  Ecuador: [
    ['Hernán Galíndez', 'GK', 35, 'Aucas', 1], ['Alexander Domínguez', 'GK', 37, 'LDU Quito', 2],
    ['Piero Hincapié', 'DF', 23, 'Leverkusen', 3], ['Felix Torres', 'DF', 28, 'Santos Laguna', 4],
    ['Robert Arboleda', 'DF', 33, 'São Paulo', 5], ['Angelo Preciado', 'DF', 26, 'Genk', 6],
    ['Pervis Estupiñán', 'DF', 27, 'Brighton', 7], ['Hernán Galíndez', 'DF', 35, 'Aucas', 8],
    ['Moisés Caicedo', 'MF', 23, 'Chelsea', 9], ['Carlos Gruezo', 'MF', 29, 'San Jose Earthquakes', 10],
    ['Kendry Páez', 'MF', 18, 'Strasbourg', 11], ['Jhegson Méndez', 'MF', 27, 'LDU Quito', 12],
    ['Alan Franco', 'MF', 28, 'Atlético Mineiro', 13], ['Enner Valencia', 'FW', 35, 'Internacional', 14],
    ['Jordy Caicedo', 'FW', 26, 'Siloé', 15], ['Jordy Alcívar', 'FW', 25, 'LDU Quito', 16],
    ['Michael Estrada', 'FW', 28, 'CSKA Sofia', 17], ['Jordy Caicedo', 'FW', 26, 'Siloé', 18],
    ['Ángel Mena', 'FW', 36, 'León', 19], ['Jordy Alcívar', 'FW', 25, 'LDU Quito', 20],
  ],
}