import type { Metadata } from 'next'
import { LegalLayout, legalStyles } from '@/components/legal/LegalLayout'
import { absoluteUrl } from '@/lib/site'
import { appPath } from '@/lib/urls'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Terms of Service for MatchMind — AI football intelligence for World Cup 2026 fans.',
  alternates: {
    canonical: absoluteUrl('/terms'),
  },
  openGraph: {
    url: absoluteUrl('/terms'),
    title: 'Terms of Service | MatchMind',
    description:
      'Terms of Service for MatchMind — AI football intelligence for World Cup 2026 fans.',
  },
}

const { h2, p, ul } = legalStyles

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" updated="June 7, 2026">
      <p style={p}>
        These Terms of Service (&quot;Terms&quot;) govern your use of MatchMind, operated by BlindspotLab. By
        accessing or using MatchMind, you agree to these Terms.
      </p>

      <h2 style={h2}>The service</h2>
      <p style={p}>
        MatchMind is an AI-powered football intelligence application for World Cup 2026 fans. It provides stats,
        analysis, predictions, and related information grounded in data stored in MongoDB and processed with AI
        models. MatchMind is provided for informational and entertainment purposes.
      </p>

      <h2 style={h2}>Accounts</h2>
      <ul style={ul}>
        <li>You must provide accurate account information and keep your credentials secure</li>
        <li>You are responsible for activity under your account</li>
        <li>Usernames must be unique and must not impersonate others or violate applicable law</li>
        <li>We may suspend or terminate accounts that violate these Terms or abuse the service</li>
      </ul>

      <h2 style={h2}>Acceptable use</h2>
      <p style={p}>You agree not to:</p>
      <ul style={ul}>
        <li>Use MatchMind for unlawful, harmful, or fraudulent purposes</li>
        <li>Attempt to gain unauthorized access to systems, data, or admin features</li>
        <li>Scrape, overload, or interfere with the service or its infrastructure</li>
        <li>Misrepresent AI-generated outputs as guaranteed facts, betting advice, or professional counsel</li>
      </ul>

      <h2 style={h2}>AI-generated content</h2>
      <p style={p}>
        Responses from MatchMind are generated by artificial intelligence and may be incomplete, outdated, or
        incorrect. You should verify important information independently. MatchMind does not guarantee the accuracy
        of predictions, statistics, or analysis.
      </p>

      <h2 style={h2}>Intellectual property</h2>
      <p style={p}>
        MatchMind, its branding, and original content are owned by BlindspotLab unless otherwise noted. Open-source
        components remain subject to their respective licenses. You may not copy, resell, or commercially exploit the
        service without permission.
      </p>

      <h2 style={h2}>Third-party services</h2>
      <p style={p}>
        MatchMind integrates with third-party services including Google, MongoDB, and email providers. Your use of
        those services may be subject to their separate terms and policies.
      </p>

      <h2 style={h2}>Disclaimer of warranties</h2>
      <p style={p}>
        MatchMind is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, express or
        implied, including fitness for a particular purpose, accuracy, or uninterrupted availability.
      </p>

      <h2 style={h2}>Limitation of liability</h2>
      <p style={p}>
        To the fullest extent permitted by law, BlindspotLab and its contributors will not be liable for any
        indirect, incidental, special, consequential, or punitive damages arising from your use of MatchMind.
      </p>

      <h2 style={h2}>Changes</h2>
      <p style={p}>
        We may modify these Terms or the service at any time. Continued use after changes are posted constitutes
        acceptance of the updated Terms.
      </p>

      <h2 style={h2}>Privacy</h2>
      <p style={p}>
        Our{' '}
        <a href={appPath('/privacy')} style={{ color: 'var(--gold)' }}>
          Privacy Policy
        </a>{' '}
        explains how we handle personal data and is incorporated into these Terms by reference.
      </p>
    </LegalLayout>
  )
}