/**
 * Guardian WC2026 team guides (48 nations).
 * Source: https://interactive.guim.co.uk/docsdata/1_ZAfmUkTZ4BvDgvhEGaEruakfu4aWIIjjzXaMAiT1yc.json
 * @see https://www.theguardian.com/football/2026/jun/06/world-cup-2026-squads-guide
 * Auto-generated by scripts/generate-guardian-profiles.ts
 */

export type GuardianTeamGuide = {
  coach: string
  bio: string
  strengths: string
  weaknesses: string
  playerPick: string
  byline: string
  group: string
  fifaRanking?: number
}

export const GUARDIAN_TEAM_GUIDES: Record<string, GuardianTeamGuide> = {
  "Algeria": {
    coach: "Vladimir Petkovic",
    bio: "One of this World Cup’s great unknowns. Qualifying was a cakewalk – but against generally poor opposition. Read the team guide here.",
    strengths: "The squad boasts plenty of technical ability and Afcon highlighted just how good they can be at their best.",
    weaknesses: "The Afcon quarter-final collapse against Nigeria remains fresh in minds. Was it an aberration or a sign of how this team performs under pressure?",
    playerPick: "Riyad Mahrez",
    byline: "Maher Mezahi for DZfoot",
    group: "J",
    fifaRanking: 28
  },
  "Argentina": {
    coach: "Lionel Scaloni",
    bio: "World Cup and Copa América holders travel with a squad of familiar faces but perhaps not with players in peak physical condition. Read the team guide here.",
    strengths: "Almost all of the class of 2022 is still around, including Messi.",
    weaknesses: "Several players had injury setbacks at the end of very demanding seasons with their clubs.",
    playerPick: "Lionel Messi",
    byline: "Gastón Pestarino, Hernán Claus and Joaquín Zabala for Olé",
    group: "J",
    fifaRanking: 1
  },
  "Australia": {
    coach: "Tony Popovic",
    bio: "At their sixth successive finals, the Socceroos arrive with an experienced core, young attacking talent and designs on a first knockout win. Read the team guide here.",
    strengths: "Popovic improved the team in qualifying and has made them tougher to beat, while Irankunda leads a dangerous counterattacking unit.",
    weaknesses: "The new coach is eager to shake off the ‘underdogs’ tag, but it may prove tough with a lack of high-profile names in a transitional squad.",
    playerPick: "Jackson Irvine",
    byline: "Joey Lynch, Jo Khan, Martin Pegan and Mike Hytner",
    group: "D",
    fifaRanking: 27
  },
  "Austria": {
    coach: "Ralf Rangnick",
    bio: "Rangnick's high-pressing unit know exactly who they are. This is a side built not on stardom but on familiarity, trust and collective movement. Read the team guide here.",
    strengths: "Continuity: Austria’s plan has been remarkably stable for years. Rangnick has had time to imprint his ideas.",
    weaknesses: "If the structure slips even slightly, the aggressive counter-pressing approach can leave them exposed. Pre-tournament injury to Christoph Baumgartner is a huge blow.",
    playerPick: "Konrad Laimer",
    byline: "Andreas Hagenauer and Martin Schauhuber for Der Standard",
    group: "J",
    fifaRanking: 24
  },
  "Belgium": {
    coach: "Rudi Garcia",
    bio: "A time of transition for the Red Devils. Qualifying went smoothly but was never particularly eye-catching. Read the team guide here.",
    strengths: "De Bruyne, Doku and Lukaku offer a serious attacking edge, though the latter played only 64 minutes for Napoli this season.",
    weaknesses: "The defence is, except for Courtois, the weak point with the golden generation of Alderweireld, Kompany, Vermaelen and Vertonghen long gone.",
    playerPick: "Kevin De Bruyne",
    byline: "Written by Ludo Vandewalle for Het Nieuwsblad",
    group: "G",
    fifaRanking: 9
  },
  "Bosnia and Herzegovina": {
    coach: "Sergej Barbarez",
    bio: "Surprise qualifiers who stunned Italy in the playoffs, Barbarez’s intense and unpredictable side could win over neutrals. Read the team guide here.",
    strengths: "Aggressive defending, direct, passionate football and quick transitions, plus a huge young talent in Alajbegovic.",
    weaknesses: "Intensity can go too far, with a loss of shape and discipline; unlikely to be able to dominate games in their group.",
    playerPick: "Edin Dzeko",
    byline: "Sasa Ibrulj for Skaut Sport",
    group: "B",
    fifaRanking: 64
  },
  "Brazil": {
    coach: "Carlo Ancelotti",
    bio: "Five-time champions have turned to Ancelotti, who has built an attacking side eager to end years of underachievement. Read the team guide here.",
    strengths: "Built around Vinícius, the team has a solid spine which allows room for attacking flair in an aggressive 4-2-4 formation.",
    weaknesses: "The full-backs do not match up to former greats, while 34-year-old Neymar may struggle to contribute fully due to injuries.",
    playerPick: "Vinícius Júnior",
    byline: "Gustavo Faldon for Estadão",
    group: "C",
    fifaRanking: 6
  },
  "Canada": {
    coach: "Jesse Marsch",
    bio: "Marsch has turned the co-hosts into a solid and settled team, and worked to develop the mentality to handle pressure. Read the team guide here.",
    strengths: "Consistent 4-4-2 approach built on pressing from the front and pace out wide, all backed by a resilient defensive unit.",
    weaknesses: "Fitness fears over star man Davies, a competitive group and the burden of never having won a World Cup match.",
    playerPick: "Alphonso Davies",
    byline: "Alexandre Gangué-Ruzic and Kristian Jack for Onesoccer",
    group: "B",
    fifaRanking: 30
  },
  "Cape Verde": {
    coach: "Pedro 'Bubista' Leitão Brito",
    bio: "An eclectic group of players, the Blue Sharks are swimming in completely uncharted waters as they make their World Cup debut. Read the team guide here.",
    strengths: "A settled squad has been together for the best part of half a decade. Physical and happy to defend but blessed with technical forwards too.",
    weaknesses: "Key defender Logan Costa has been out with an anterior cruciate ligament injury all season",
    playerPick: "Dailon Livramento",
    byline: "Alasdair Howorth",
    group: "H",
    fifaRanking: 67
  },
  "Colombia": {
    coach: "Néstor Lorenzo",
    bio: "Experienced squad endured a rollercoaster qualifying campaign, beating Brazil and Argentina but losing to a poor Bolivia side. Read the team guide here.",
    strengths: "Goals shouldn't be a problem. Suárez is coming off a prolific season in Portugal with Sporting and only Argentina scored more in Conmebol qualifying.",
    weaknesses: "Tournament football leaves no room for the inconsistency that has become a hallmark of this side.",
    playerPick: "Luis Díaz",
    byline: "José Orlando Ascencio for El Tiempo",
    group: "K",
    fifaRanking: 13
  },
  "Croatia": {
    coach: "Zlatko Dalic",
    bio: "Semi-finalists in 2018 and 2022. Likely to revert to a back four after recent wing-back experiment brought mixed results. Read the team guide here.",
    strengths: "Bags of experience and, as past World Cups have shown, a winning mentality. Modric remains a midfield maestro.",
    weaknesses: "Can the old guard still cut it? All that experience means plenty of miles in the legs and sapping temperatures ahead.",
    playerPick: "Luka Modric",
    byline: "Alex Holiga for Telesport",
    group: "L",
    fifaRanking: 11
  },
  "Curaçao": {
    coach: "Dick Advocaat",
    bio: "The smallest nation by population and area to reach a World Cup, Advocaat’s side will seek to make a splash beyond their surprise qualification. Read the team guide here.",
    strengths: "Advocaat’s return is a huge bonus; the vastly experienced head coach has led the team’s improvement and brought in players from the island’s diaspora.",
    weaknesses: "The team’s possession-based style may need to be overhauled in a tough group, and kicking off against Germany is a particularly daunting test.",
    playerPick: "Leandro Bacuna",
    byline: "Arthur Renard",
    group: "E",
    fifaRanking: 82
  },
  "Czech Republic": {
    coach: "Miroslav Koubek",
    bio: "Having squeezed in via the playoffs, Koubek’s well-drilled side have hopes of advancing from a middling group. Read the team guide here.",
    strengths: "The spine of the side has plenty of experience, led by Soucek in midfield, while Schick scored 16 Bundesliga goals this season.",
    weaknesses: "A serious lack of technical players, with the team relying too heavily on physicality, work rate, aggression and set pieces.",
    playerPick: "Patrik Schick",
    byline: "Jan Palicka for Seznamzpravy.cz",
    group: "A",
    fifaRanking: 40
  },
  "DR Congo": {
    coach: "Sébastien Desabre",
    bio: "Pragmatic, detail-obsessed coach has the Leopards purring, with a united squad built around a clear collective identity. Read the team guide here.",
    strengths: "Extremely difficult to break down and mentally tough as they come. Resilience defined their qualification campaign.",
    weaknesses: "Rarely dominate games and struggle to create freely in open play. Preparations have been disrupted by Ebola outbreak in country.",
    playerPick: "Yoane Wissa",
    byline: "Louis Mukoma Fargues for Leopardsfoot.com",
    group: "K",
    fifaRanking: 46
  },
  "Ecuador": {
    coach: "Sebastián Beccacece",
    bio: "At their fifth World Cup, this may be El Tri’s strongest squad, seeking to win their first knockout game after qualifying in impressive fashion. Read the team guide here.",
    strengths: "A defence marshalled by Pacho and Hincapié conceded just five goals in 18 qualifiers and Beccacece has introduced a Bielsa-esque pressing mentality.",
    weaknesses: "Scoring remains a problem and beyond veteran striker Enner Valencia, attacking options are talented but raw and unproven at the highest level.",
    playerPick: "Moisés Caicedo",
    byline: "Juan José Palacios for Studio Fútbol",
    group: "E",
    fifaRanking: 23
  },
  "Egypt": {
    coach: "Hossam Hassan",
    bio: "Salah led the way through qualifying but limitations of the side were exposed at Afcon, where Senegal inflicted a semi-final defeat. Read the team guide here.",
    strengths: "Cohesive, often hard to score against and emotionally committed.",
    weaknesses: "Can look blunt if opponents double up on Salah and the midfield cannot pass through the press.",
    playerPick: "Mohamed Salah",
    byline: "Saher Ahmed for Kingfut.com",
    group: "G",
    fifaRanking: 29
  },
  "England": {
    coach: "Thomas Tuchel",
    bio: "Cruised through qualifying but the opposition was hardly taxing. So it's the usual question: how will they fare when they come up against the best in a knockout tie? Read the team guide here.",
    strengths: "They have enviable attacking options, a host of No 10s and in Rice one of the best midfielders in the world.",
    weaknesses: "There are question marks over the defensive options and, as ever, fitness concerns over key players.",
    playerPick: "Harry Kane",
    byline: "David Hills",
    group: "L",
    fifaRanking: 4
  },
  "France": {
    coach: "Didier Deschamps",
    bio: "France have attacking talents that are the envy of the world. But will Deschamps take the handbrake off and let them shine? Read the team guide here.",
    strengths: "The front four is a remarkable quartet, and the back four isn't bad either. Their bench might be the strongest at the tournament.",
    weaknesses: "A cynic might suggest the head coach's conservatism. More accurately, it's the challenge he faces in putting all the puzzle pieces together.",
    playerPick: "Kylian Mbappé",
    byline: "Written by Luke Entwistle for GFFN",
    group: "I",
    fifaRanking: 3
  },
  "Germany": {
    coach: "Julian Nagelsmann",
    bio: "Winners in 2014, Die Mannschaft crashed out at the group stage in the last two finals but have rebuilt well under tactical obsessive Nagelsmann. Read the team guide here.",
    strengths: "A blend of rising stars and reliable stalwarts, this squad has more than enough creative talent to take advantage of a decent group-stage draw.",
    weaknesses: "This is not yet a vintage Germany side and results have been inconsistent, while Neuer is back in goal after a reliable successor could not be found.",
    playerPick: "Florian Wirtz",
    byline: "Nico Horn, Oliver Fritsch and Christian Spiller for Die Zeit",
    group: "E",
    fifaRanking: 10
  },
  "Ghana": {
    coach: "Carlos Queiroz",
    bio: "A team littered with attacking talent that cruised through qualifying but their recent run of defeats is a concern. Read the team guide here.",
    strengths: "Have developed into a major threat from set pieces and in Semenyo the Black Stars have one of the most in-form attackers in European club football.",
    weaknesses: "Lack of elite defenders is a worry and goalkeeping unit lacks international experience.",
    playerPick: "Antoine Semenyo",
    byline: "Victor Atsu Tamakloe for Myjoyonline.com",
    group: "L",
    fifaRanking: 73
  },
  "Haiti": {
    coach: "Sébastien Migné",
    bio: "Grenadiers will be group outsiders after reaching their first World Cup since 1974 despite turmoil at home. Read the team guide here.",
    strengths: "Migné has built a disciplined side with the pace and skill to counter effectively, with Bellegarde and Isidor bringing proven quality.",
    weaknesses: "Instability has affected the team’s buildup, with key striker Nazon held up in Iran and Migné unable to visit the country he coaches.",
    playerPick: "Wilson Isidor",
    byline: "Pierre Richard Midy",
    group: "C",
    fifaRanking: 83
  },
  "Iran": {
    coach: "Amir Ghalenoei",
    bio: "Smooth sailing in qualifying – anything but easy since then. The conflict with the United States threw their involvement into doubt but Ghalenoei's side are all set to compete. Read the team guide here.",
    strengths: "Capable of mixing things up – in March friendlies they played a 3-6-1 against Nigeria and a 4-4-2 against Costa Rica.",
    weaknesses: "Ghalenoei and his staff will have to work hard to minimise disruption for the squad, which will be based in Mexico but will play three group games in the US.",
    playerPick: "Mehdi Taremi",
    byline: "Behnam Jafarzadeh for the Guardian",
    group: "G",
    fifaRanking: 20
  },
  "Iraq": {
    coach: "Graham Arnold",
    bio: "After a marathon journey to get here (they played 21 qualifiers, more than anyone else) Arnold's side are out to prove they belong on the world stage. Read the team guide here.",
    strengths: "As Arnold says, the pressure is on the other three teams in the group. Iraq have nothing to lose.",
    weaknesses: "Not exactly free-scoring. Breaking down three tough defences in the group will be a huge challenge.",
    playerPick: "Aymen Hussein",
    byline: "Hassanin Mubarak. Visit his substack here.",
    group: "I",
    fifaRanking: 57
  },
  "Ivory Coast": {
    coach: "Emerse Faé",
    bio: "The Elephants believe they can do what their golden generation failed to: reach the knockout stages, or as Faé has said: ‘Why not win it?’ Read the team guide here.",
    strengths: "Faé’s defence is settled but still flexible and did not concede in qualifying, and the coach has a wealth of attacking talent at his disposal.",
    weaknesses: "There are questions over midfield selection and their underwhelming Afcon defence has lowered previously high expectations this summer.",
    playerPick: "Nicolas Pépé",
    byline: "Prince Akabla for Le Kpakpato Sportif",
    group: "E",
    fifaRanking: 33
  },
  "Japan": {
    coach: "Hajime Moriyasu",
    bio: "Perennial dark horses capable of causing shocks, impressive warm-up results have fuelled belief they can break new ground by reaching the quarter-finals. Read the team guide here.",
    strengths: "Samurai Blue play as a cohesive unit, pressing from the front in Moriyasu’s settled system, and now have the squad depth to make a deeper run.",
    weaknesses: "Injury to Kaoru Mitoma is a blow and they have landed in a tough group with three experienced and physical opponents.",
    playerPick: "Takefusa Kubo",
    byline: "Takashi Ogami for Shukyu Magazine",
    group: "F",
    fifaRanking: 18
  },
  "Jordan": {
    coach: "Jamal Sellami",
    bio: "A first finals appearance for a team who qualified with a match to spare. Will likely sit deep in a back five. Read the team guide here.",
    strengths: "Will look to exploit quick transitions and the pace of star winger Mousa Al-Taamari.",
    weaknesses: "Injury has ruled out key striker Yazan A-Naimat, leaving a huge hole in attack. Big-game experience is in short supply.",
    playerPick: "Mousa Al-Tamari",
    byline: "Ayman Hijleh for Al-Ghad",
    group: "J",
    fifaRanking: 63
  },
  "Mexico": {
    coach: "Javier Aguirre",
    bio: "Playing in a third World Cup on home soil, El Tri are competitive and flexible but may struggle to meet fans’ high expectations. Read the team guide here.",
    strengths: "Flexible tactics, a tight defensive unit and an approach based on intensity, aggressive pressing and quick transitions.",
    weaknesses: "Pressure as co-hosts could affect even an experienced squad, while Aguirre’s pragmatic approach has drawn criticism.",
    playerPick: "Raúl Jiménez",
    byline: "Jesús Valdéz for Claro Sports",
    group: "A",
    fifaRanking: 14
  },
  "Morocco": {
    coach: "Mohamed Ouahbi",
    bio: "Atlas Lions made history as Africa’s first semi-finalists in Qatar and expect to make a similar impact after a recent coaching change. Read the team guide here.",
    strengths: "Ouahbi’s setup will create space for star player Hakimi, while reaching the last four in 2022 has boosted collective belief.",
    weaknesses: "The Afcon hosts struggled to cope under pressure, culminating in a farcical final, and will be under close scrutiny again this summer.",
    playerPick: "Achraf Hakimi",
    byline: "Amine El Amri for Skwad by 2M TV",
    group: "C",
    fifaRanking: 7
  },
  "Netherlands": {
    coach: "Ronald Koeman",
    bio: "Koeman has been set a target of reaching the semi-finals, but has been forced to prioritise strength and fitness over skill with a raft of injury issues. Read the team guide here.",
    strengths: "The Oranje smashed in 27 goals to qualify unbeaten, but it is their back four which looks most impressive on paper, marshalled by captain Van Dijk.",
    weaknesses: "Several key players have suffered from injury layoffs or lack of game time this season, and facing Japan first will test this team’s cohesion.",
    playerPick: "Virgil van Dijk",
    byline: "Marcel van der Kraan for De Telegraaf",
    group: "F",
    fifaRanking: 8
  },
  "New Zealand": {
    coach: "Darren Bazeley",
    bio: "The All Whites are the lowest-ranked team at the tournament but the squad has evolved from part-timers to professionals. Read the team guide here.",
    strengths: "There's no shortage of optimism – within the camp there's belief they can to make the knockout rounds for the first time.",
    weaknesses: "Star striker Wood has had an injury-plagued 2026 and recent friendly results have been mixed at best.",
    playerPick: "Chris Wood",
    byline: "Maree Mahony for RNZ",
    group: "G",
    fifaRanking: 85
  },
  "Norway": {
    coach: "Ståle Solbakken",
    bio: "Golden generation vibes for Haaland and friends. But expect Solbakken's side to prioritise effectiveness over aesthetics. Read the team guide here.",
    strengths: "Haaland will be eager to grab this opportunity on the world stage. The team averaged nearly five goals a game in qualifying.",
    weaknesses: "Tough group means they have to hit the ground running. First-choice goalkeeper has barely played for his club this season.",
    playerPick: "Erling Haaland",
    byline: "Simen Stamsø-Møller and Vegard Bjelland for TV 2 Norway",
    group: "I",
    fifaRanking: 31
  },
  "Panama": {
    coach: "Thomas Christiansen",
    bio: "La Marea Roja are hopeful of improving upon hapless 2018 showing after long development under former Leeds coach. Read the team guide here.",
    strengths: "Squad has been together a long time, has pace and is full of confidence. Solid recent showings in Gold Cup and Nations League.",
    weaknesses: "Tend to struggle against the bigger teams and several key players are now well into their 30s.",
    playerPick: "Michael Murillo",
    byline: "José Miguel Domínguez Flores for Chepebomba.com and the podcast Punto Y Pelota Mentira No Es",
    group: "L",
    fifaRanking: 34
  },
  "Paraguay": {
    coach: "Gustavo Alfaro",
    bio: "Alfaro has rebuilt the team around 'Paraguayan DNA – intensity and clean sheets' and hopes of progress are high after 12 years away. Read the team guide here.",
    strengths: "La Albirroja will rely on the assets that saw them through qualifying: playing a physical style with the tenacity to dig out unlikely results.",
    weaknesses: "Only two teams scored fewer goals in Conmebol qualifying and there may be an over-reliance on Enciso to create and take chances.",
    playerPick: "Julio Enciso",
    byline: "Christian Pérez and Óscar Gómez for VS Sports",
    group: "D",
    fifaRanking: 41
  },
  "Portugal": {
    coach: "Roberto Martínez",
    bio: "One last hurrah for Ronaldo but last year's Nations League winners have quality throughout and lofty ambitions. Read the team guide here.",
    strengths: "The core of the team is settled and the options varied and versatile. A squad still mourning Diogo Jota have a personal, collective mission.",
    weaknesses: "Few and far between but there's always a risk of Ronaldo's outsized influence becoming a problem.",
    playerPick: "Cristiano Ronaldo",
    byline: "Nuno Travassos for A Bola",
    group: "K",
    fifaRanking: 5
  },
  "Qatar": {
    coach: "Julen Lopetegui",
    bio: "The 2022 hosts stumbled through qualifying but could benefit from a much lower profile in these finals. Read the team guide here.",
    strengths: "Hugely experienced coach Lopetegui will put hard focus on soaking up pressure and looking to hit opponents on the break.",
    weaknesses: "Defence was a mess in qualifying, conceding 24 times in 10 games in the main section, while regional conflict badly disrupted preparation.",
    playerPick: "Akram Afif",
    byline: "John Duerden",
    group: "B",
    fifaRanking: 56
  },
  "Saudi Arabia": {
    coach: "Georgios Donis",
    bio: "The Green Falcons have had a chaotic buildup to the tournament, with Donis taking charge in April after the bitter exit of Hervé Renard. Read the team guide here.",
    strengths: "Expectations are low, so to some extent the pressure is off. Expect Donis to focus his efforts on defensive solidity.",
    weaknesses: "The team looks toothless up front: just seven goals were scored in 10 games in the main round of qualification.",
    playerPick: "Salem Al-Dawsari",
    byline: "John Duerden",
    group: "H",
    fifaRanking: 61
  },
  "Scotland": {
    coach: "Steve Clarke",
    bio: "Clarke’s side ended 28-year wait to qualify in cathartic style and will seek to reward travelling fans with a first trip to the knockouts. Read the team guide here.",
    strengths: "Built around key lieutenants like McTominay and Robertson, Scotland’s first-choice XI is organised and hugely experienced.",
    weaknesses: "The team lacks a reliable scorer, with Clarke often criticised for his caution, while Billy Gilmour’s injury will hurt a squad lacking depth.",
    playerPick: "Scott McTominay",
    byline: "Ewan Murray",
    group: "C",
    fifaRanking: 42
  },
  "Senegal": {
    coach: "Pape Thiaw",
    bio: "The Lions of Teranga arrive in North America in fine shape, thanks to a freshened-up frontline and a defence that is its usual sturdy self. Read the team guide here.",
    strengths: "Thiaw has developed a more flexible tactical approach, while speed in attack will cause teams plenty of problems.",
    weaknesses: "Recent tournament record, aside from the most recent Cup of Nations, is unimpressive.",
    playerPick: "Sadio Mané",
    byline: "Omar Kane for Taggat",
    group: "I",
    fifaRanking: 15
  },
  "South Africa": {
    coach: "Hugo Broos",
    bio: "Bafana Bafana have emerged from a stagnant period after hosting in 2010 and held off Nigeria in qualifying. Read the team guide here.",
    strengths: "International setup revitalised under Broos, knitted together by Mokoena in midfield, and built on well-drilled teamwork.",
    weaknesses: "A squad mainly made up of domestic players lacks wider experience and will rely heavily on counterattacks to create chances.",
    playerPick: "Teboho Mokoena",
    byline: "Yanga Sibembe for Daily Maverick",
    group: "A",
    fifaRanking: 60
  },
  "South Korea": {
    coach: "Hong Myung-bo",
    bio: "The Taegeuk Warriors went unbeaten to qualify for their 11th straight finals, but ambitions do not extend far beyond escaping their group. Read the team guide here.",
    strengths: "With a robust core, the team has a great spirit and a proper talisman in former Premier League golden boot winner Son.",
    weaknesses: "Uncertainty over ideal formation, with a late switch to 3-4-3 during qualifying, plus fears about form and fitness of key players.",
    playerPick: "Son Heung-min",
    byline: "Hyung Seo for Footballist",
    group: "A",
    fifaRanking: 25
  },
  "Spain": {
    coach: "Luis de la Fuente",
    bio: "Rightly among the favourites. De la Fuente has the perfect blend of youth and experience, prodigious talent and maturity. Read the team guide here.",
    strengths: "Lamine Yamal and Williams have injected freshness into a team that still dominates the ball. The frontline will be hard to contain.",
    weaknesses: "Are there any? The back four can have its moments but this is simply a fiercely competitive and united team.",
    playerPick: "Lamine Yamal",
    byline: "Nadia Tronchoni for El País",
    group: "H",
    fifaRanking: 2
  },
  "Sweden": {
    coach: "Graham Potter",
    bio: "Took two points from 18 in a disastrous qualifying campaign, but grasped their playoff chance under Potter and have the attacking talent to go further. Read the team guide here.",
    strengths: "Potter has two elite finishers at his disposal up front but will set up with a hard-working back five to complement the firepower in his squad.",
    weaknesses: "Isak endured a grim first season at Liverpool, and Potter has had limited time to apply his methods after taking over last October.",
    playerPick: "Alexander Isak",
    byline: "Samuel Parts for Fotbollskanalen",
    group: "F",
    fifaRanking: 38
  },
  "Switzerland": {
    coach: "Murat Yakin",
    bio: "Yakin is aiming for the 'best World Cup from a Swiss team' as he seeks to turn reliable regulars into contenders this summer. Read the team guide here.",
    strengths: "Comfortable in qualifying, topped their group with a mix of experience and fresh talent knitted together by Xhaka.",
    weaknesses: "Some tactical uncertainty over formation, and big expectations from fans despite their side lacking depth beyond the starting XI.",
    playerPick: "Granit Xhaka",
    byline: "Christian Finkbeiner and Lucas Werder for Blick",
    group: "B",
    fifaRanking: 19
  },
  "Tunisia": {
    coach: "Sabri Lamouchi",
    bio: "After six World Cups and six group-stage exits, the Eagles of Carthage seek to break new ground with an imposing team drawn from the country’s diaspora. Read the team guide here.",
    strengths: "Did not concede a goal in qualifying and have been tactically flexible under Lamouchi, who has pleased supporters with his desire to bring young talent through.",
    weaknesses: "Burnley’s Mejbri is the creative star of a low-key team lacking elite experience, who may find it difficult to play with freedom in a challenging group.",
    playerPick: "Hannibal Mejbri",
    byline: "Ahmed Adala for Radio Mosaïque FM",
    group: "F",
    fifaRanking: 45
  },
  "Turkey": {
    coach: "Vincenzo Montella",
    bio: "After a remarkable 22-year absence following their third-place finish in 2002, Montella's talented squad are primed to make an impact on their return to the world stage. Read the team guide here.",
    strengths: "Montella has built a harmonious squad with in-form players and two of Europe’s brightest attacking talents in the shape of Guler and Yildiz.",
    weaknesses: "Lack of a proven striker and big-game experience in some areas increases the risk of the wheels coming off as they did at Euro 2020.",
    playerPick: "Arda Guler",
    byline: "Emre Sarigul",
    group: "D",
    fifaRanking: 22
  },
  "United States": {
    coach: "Mauricio Pochettino",
    bio: "Expectations are low for the co-hosts after a turbulent buildup, but there is a path to the latter stages if Pochettino can harness his team’s abilities. Read the team guide here.",
    strengths: "The core of the squad are ‘glue guys’ with prior World Cup experience, while their head coach knows how to win knockout matches.",
    weaknesses: "Pochettino still seems unclear on his best team and tactical setup, leaving many home fans frustrated before a ball has been kicked.",
    playerPick: "Christian Pulisic",
    byline: "Jeff Rueter",
    group: "D",
    fifaRanking: 17
  },
  "Uruguay": {
    coach: "Marcelo Bielsa",
    bio: "The quarter-finals are the aim, but the buildup has been anything but smooth. Bielsa has been under pressure since a 5-1 loss to the USA in November. Read the team guide here.",
    strengths: "Brace yourselves for Bielsa-ball: expect La Celeste to press their opponents high up the field and chase the ball at all times.",
    weaknesses: "Uruguay do not have the scoring power of old. Hopes are being pinned on Darwin Núñez, who has struggled for form at Al-Hilal.",
    playerPick: "Federico Valverde",
    byline: "Luis Inzaurralde for El Observador",
    group: "H",
    fifaRanking: 16
  },
  "Uzbekistan": {
    coach: "Fabio Cannavaro",
    bio: "A historic first World Cup beckons. Cannavaro has stuck with the 5-2-3 system that powered the White Wolves through qualifying. Read the team guide here.",
    strengths: "Qualification was built off a solid defence that includes Khusanov, with just seven goals conceded in 10 games.",
    weaknesses: "Cannavaro was a legend as a player but his managerial career has been mixed. Goals are likely to be a problem.",
    playerPick: "Abdukodir Khusanov",
    byline: "Narzulla Saydullaev for Championat Asia",
    group: "K",
    fifaRanking: 50
  },
}

export function getGuardianTeamGuide(team: string): GuardianTeamGuide | undefined {
  return GUARDIAN_TEAM_GUIDES[team]
}
